### ISSUE TITLE
MethodNotFound exception when using obfuscated DLL in Progress OpenEdge

### ISSUE THREAD

**Issue by componentpro** [obfuscar/obfuscar#141]
I'm having issue that Progress OpenEdge throws "Method not found" exception when using a DLL obfuscated by obfuscar. Here is its link https://www.progress.com/openedge. The DLL can be downloaded from https://www.nuget.org/packages/ComponentPro.Pdf/

Any ideas what wrong with obfuscar?

**Comment by componentpro** [comment]
The following will reproduce the issue:
- Download and install: https://www.componentpro.com/trial-download?name=excel
- Install OpenEdge with the link above
- Run openedge with the following code:
oWorkbook = poManager:Workbooks:Add().
oWorkbook:Version = ComponentPro.Excel.ExcelVersion:Excel2016. 
            
oWorkbook:Worksheets:Clear().

**Comment by componentpro** [comment]
Hi, any updates on this issue?

**Comment by lextm** [comment]
Similar to other issues like #165 . Many .NET applications use reflection to load assemblies (OpenEdge might work in the same way), so they rely on certain names.

You have to exclude certain classes/methods so as to make it work.
