### ISSUE TITLE
Domain obfuscar.com can not be resolved.

### ISSUE THREAD

**Issue by nefcanto** [obfuscar/obfuscar#143]
Hi guys

I tried to reach documentation, and I got this error:

> ERR_NAME_NOT_RESOLVED

I also tried DNS in https://ping.eu/nslookup/ and seems that your DNS has problems.

I can't reach docs. Can you please investigate this?

**Comment by lextm** [comment]
The hosting provider experienced some issue. 

Temporarily you can visit http://obfuscar.readthedocs.io/en/latest/
