### ISSUE TITLE
Cannot Re-Sign Assemblies Using PFX?

### ISSUE THREAD

**Issue by protegesolutions** [obfuscar/obfuscar#146]
As far as I can tell re-signing assemblies with PFX files isn't supported. Can someone please confirm?

I tried to have a look at and fix/add this but the source seems to be missing some code (ilspy content).

**Comment by lextm** [comment]
The code does support the so-called key container, https://github.com/obfuscar/obfuscar/blob/master/Obfuscar/Project.cs#L126

Key containers seem to be related to PFX files. However, I never use it, so I don't know how it works either.

**Comment by protegesolutions** [comment]
In hindsight, it's probably obvious that passworded pfx can't be used as Obfuscar doesn't have a `KeyFilePassword` setting.

I'm getting around this by post-signing with SignTool. Not ideal but it works.

**Comment by lextm** [comment]
The functionality to use key container is restored in release 2.2.13.
