### ISSUE TITLE
Location of obfuscar.xml

### ISSUE THREAD

**Issue by protegesolutions** [obfuscar/obfuscar#147]
It seems that Obfuscar only looks for the config file in, say, the `bin/Release` folder. Is that right?

So assuming you maintain the config in your project folder, you need to copy it to the build folder. (Which is what the example project does.)

Wouldn't it be better to have Obfuscar look in the _project_ folder and take it's direction from there, including, say, only obfuscate on a `Release` build?

I know I can hack this together to get what I need, but it seems needlessly complicated. (The doco needs to specify what the base search folder is too probably.)

**Comment by lextm** [comment]
The example repo only shows one of the typical usage of Obfuscar command line.

The currently behavior has been there for a while, and I see no need to change it.

**Comment by protegesolutions** [comment]
Because Obfuscar's config path is the build `$TargetDir`, to reference a config file in the project folder - and therefore not have to copy it to the build folder - you can use `"$(Obfuscar)" ..\..\obfuscar.xml`.
