### ISSUE TITLE
Exited With Code 1

### ISSUE THREAD

**Issue by protegesolutions** [obfuscar/obfuscar#148]
Can we please have a glossary of errors? "Exited with code 1" isn't really very helpful.

What I'm seeing is a second project that I'm trying to get Obfuscar working with is throwing this error, tho the only difference I can see in my setup is that the code it's trying to obfuscate is different.

The _Obfuscated_ folder is created but it's empty.

The original assembly is UNSIGNED as I post-sign the obfuscated file using `SignTool` with a pfx.

Nothing I can see is different from another project I have working, or the Obfuscar example project, apart from project specific stuff.

The config file looks like this:

    <?xml version='1.0'?>
    <Obfuscator>
        <Var name="InPath" value="." />
        <Var name="OutPath" value=".\Obfuscated" />
        <Var name="HidePrivateApi" value="true" />
        <Module file="$(InPath)\MyLibrary.dll" />
    </Obfuscator>

**Comment by lextm** [comment]
The `Main` function tells it,

https://github.com/obfuscar/obfuscar/blob/master/Console/Program.cs

**Comment by protegesolutions** [comment]
Well, thanks for the tip. From that I discovered that Obfuscar:

1. Has option flags,
2. Emits info to the Console, and
3. It the error was caused by it not finding a `Newtonsoft.Json`.

So, thanks, but surely some doco mentioning this stuff would be prudent. There aren't even any default values listed for config settings.

**Comment by pulmuone** [comment]
obfuscar.xml Copy always

**Comment by lextm** [comment]
https://github.com/obfuscar/obfuscar/issues/397#issuecomment-1343903147 Follow this to learn the actual log entries.
