### ISSUE TITLE
AssemblySearchPath Recursion

### ISSUE THREAD

**Issue by protegesolutions** [obfuscar/obfuscar#149]
I worked out how to use `AssemblySearchPath` with packages but I had to explicitly define each reference path.

Like `SkipNamespace`, it would be better if recursion was supported for `AssemblySearchPath`.

So then one could define (with trailing "*"), say:

    <AssemblySearchPath path="..\..\..\packages*"/>

instead of:

    <AssemblySearchPath path="..\..\..\packages\Newtonsoft.Json.10.0.3\lib\net45" />
    <AssemblySearchPath path="..\..\..\packages\RestSharpSigned.105.1.0\lib\net45" />
    ...

Also, `AssemblySearchPath` simply isn't listed in the Configuration _Table Of Settings_ ...

PS I still think the Obfuscar root folder should be the project folder (`$ProjectDir`) rather than the build folder (`$TargetDir`); it just makes life easier.

**Comment by lextm** [comment]
As there can be multiple versions of the same NuGet packages, your proposed way is not a real solution.
