### ISSUE TITLE
test.bat fails to run due to unreferenced xunit.runner.console nuget package

### ISSUE THREAD

**Issue by contre** [obfuscar/obfuscar#150]
On a fresh clone of the repository, if you attempt to run the test.bat file after building the project and you have not used the xunit.runner.console nuget package version 2.2.0 in any other projects, you will get an error.

The project itself refers to the runner.visualstudio version which allows for it to be run from the VS IDE but it does not make the batch file work.

**Comment by lextm** [comment]
The batches are for AppVeyor only. Maybe I should move them to `appveyor.yml`.
