### ISSUE TITLE
Met an error about resolve dependency with specify library, with test project.

### ISSUE THREAD

**Issue by watsonsong** [obfuscar/obfuscar#152]
I am using the LiteNetLib and obfuscar, when I obfuscate my dll I met the following error:
`Unable t o resolve dependency: LiteNetLib.`
But when I use other nuget package it always OK.
 
I attach a test project for this issue.
[ObfuscarTest.zip](https://github.com/obfuscar/obfuscar/files/2292376/ObfuscarTest.zip)

Unzip and just run the 'pack.bat', you will see this error report.

**Comment by lextm** [comment]
If the dependent assembly is not copied to the output directory by MSBuild, then you need to add assembly search path,

http://docs.obfuscar.com/getting-started/configuration.html#assembly-search-path-2-2-5
