### ISSUE TITLE
Added support for signing assemblies with pfx files

### ISSUE THREAD

**Issue by alexgoaga** [obfuscar/obfuscar#153]
Hi,

I have added support for signing assemblies with a pfx file.

Please find attached the changed file.

 try
                {
[Project.cs.zip](https://github.com/obfuscar/obfuscar/files/2299870/Project.cs.zip)

                    if (Path.GetExtension(lKeyFileName)?.Equals(".pfx", StringComparison.InvariantCultureIgnoreCase) ?? false)
                    {
                        keyPair = GetStrongNameKeyPairFromPfx(lKeyFileName, vars.GetValue("KeyFilePassword", null));
                    }
                    else
                    {
                        keyPair = File.ReadAllBytes(vars.GetValue("KeyFile", null));
                    }
                }
                catch (Exception ex)
                {
                    throw new ObfuscarException(
                        String.Format("Failure loading key file \"{0}\"", vars.GetValue("KeyFile", null)), ex);
                }

 private static byte[] GetStrongNameKeyPairFromPfx(string pfxFile, string password)
        {
            X509Certificate2Collection certs = new X509Certificate2Collection();
            certs.Import(pfxFile, password, X509KeyStorageFlags.Exportable);
            if (certs.Count == 0)
                throw new ArgumentException("Invalid certificate", nameof(pfxFile));

           https://msdn.microsoft.com/en-us/library/aa730868(vs.80).aspx
            if (!(certs[0]?.PrivateKey is RSACryptoServiceProvider provider))
                throw new ArgumentException("Invalid private key certificate", na
[Project.cs.zip](https://github.com/obfuscar/obfuscar/files/2299872/Project.cs.zip)
meof(pfxFile));

            return provider.ExportCspBlob(true);
        }

Thanks,
Alex.

**Comment by lextm** [comment]
Duplicate to #146
