### ISSUE TITLE
Anonymous class obfuscation removes all the properties

### ISSUE THREAD

**Issue by darkeagle76** [obfuscar/obfuscar#154]
Hello
I used the obfuscator with "HidePrivateApi" set to true.
In my code there are some anonymous classes that were obfuscated but the obfuscator removes all the property of the internal call and this create an exception in the compiled program. 
There is a way to exclude anonymous classes from being obfuscated?
Thanks
D

**Comment by lextm** [comment]
Duplicate to #130

**Comment by guidomocha** [comment]
this worked for me:
```xml
<SkipType name="*AnonymousType*" skipProperties="true" skipMethods="true" skipFields="true" skipEvents="true" skipStringHiding="true" />
```
