### ISSUE TITLE
MalwareBytes: detecting adware?

### ISSUE THREAD

**Issue by ToddOwen** [obfuscar/obfuscar#155]
Hello there,
I have been using this for a while until the 26th where malware bytes detected adware within obfuscar:
![image](https://user-images.githubusercontent.com/9785280/44842288-5858d780-ac3d-11e8-904b-58d27c0c274c.png)
as you can see it is the same files I also ran all the files there through VirusTotal: https://www.virustotal.com/#/file/e6595ecab9460f362ba01bf5361407e05ed49af5748060d68c75949a6e0e2155/detection
and for reference, I scanned the latest copy and got a similar result: https://www.virustotal.com/#/file/52842e1d4269cec6077639b35dbb7498e050e2ef24fe3a5e574c279d03be05a0/detection

Any help would be appreciated :D

**Comment by lextm** [comment]
Thanks.Sounds like a false positive. I will see what I can do about it.

**Comment by lextm** [comment]
I shot MalwareBytes an email and they will work on it. Since It might take a while and unpredictable, I can only close this issue here now. Hope soon the update will arrive on every affected machines.
