### ISSUE TITLE
The problem when I process the code of 7zip.

### ISSUE THREAD

**Issue by watsonsong** [obfuscar/obfuscar#156]
I am using the c# code fome https://www.7-zip.org/sdk.html, embed the source code into my project directly. When I process obfuscate process for my DLL, I met this error:
`
SevenZip.Compression.LZ.IInWindowStream::SetStream[1]->WillRename:?
SevenZip.Compression.LZ.BinTree::SetStream[1]->Skipped:KeepPublicApi option in configuration
Inconsistent virtual method obfuscation state detected. Abort. Please review the following methods,
`

I think this is a famous library and the obfuscator should process this issue.

The interface code is like this:
`
interface IInWindowStream
{
	void SetStream(System.IO.Stream inStream);
	void Init();
	void ReleaseStream();
	Byte GetIndexByte(Int32 index);
	UInt32 GetMatchLen(Int32 index, UInt32 distance, UInt32 limit);
	UInt32 GetNumAvailableBytes();
}
`

But the implement code is like this:
`
public class BinTree : InWindow, IMatchFinder
{
    public new void SetStream(System.IO.Stream stream) { base.SetStream(stream); }
}
`

It hide the base class SetStream and implement the interface.

**Comment by lextm** [comment]
https://blog.lextudio.com/obfuscar-the-story-behind-inconsistent-virtual-method-obfuscation-state-detected-82c9f8c38667

It was well documented on CodePlex, but due to the shutdown of that site you can only refer to my blog post.
