### ISSUE TITLE
Obfuscar with .net core 2.1

### ISSUE THREAD

**Issue by SinghAashish** [obfuscar/obfuscar#157]
Hi,

Is it possible to use Obfuscar to obfuscate a DLL file created using .net core 2.1?

I had an existing DLL file which was obfuscating as expected while it was compiled using .net framework 4.6.1 however, it stopped obfuscating after we migrated our source code to .net core 2.1. Am I missing anything? How to make this work?

Thanks,

Aashish Singh.

**Comment by lextm** [comment]
Did you check #132 from [FAQ](https://github.com/obfuscar/obfuscar/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22faq+candidate%22)?

**Comment by SinghAashish** [comment]
Hi Lex,

I just had a look at #132 as suggested by you. However, my problem statement is a bit different. My problem statement is not related to the availability of all DLL files in a particular folder. In my case, obfuscation commands run successfully ; -

1>Note that Rollbar API is enabled by default to collect crashes. If you want to opt out, please run with -s switch
1>Loading project obfuscar.xml...Processing assembly: Runtime.Security, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
1>Loading assemblies...Extra framework folders: Done.
1>hiding strings...
1>Renaming:  fields...parameters...properties...events...methods...types...Done.
1>Saving assemblies...Done.
1>Writing log file...Done.
1>Completed, 1.58 secs.

In my obfuscator.xml file, I have also mentioned suppressing Ildasm and hiding strings like : -

<Var name="HideStrings" value="true" />
<Var name="SuppressIldasm" value="true" />

Still, when I try to open my obfuscated DLL file into ildasm through elevated Visual Studio 2017 developer command prompt, it opens the DLL file in ildasm and also shows sensitive information in plain text. Am I missing anything? Kindly suggest.

Aashish Singh

**Comment by lextm** [comment]
1. ILDASM attribute is practically a useless feature. It hides nothing at all. Obfuscar includes it to match other obfuscation tools, but you can safely forget about it.
1. String hiding is a reversible process, so "sensitive information" should never be stored as strings in your assemblies.

I have updated the documentation to reflect such, http://docs.obfuscar.com/getting-started/configuration.html#control-string-hiding
