### ISSUE TITLE
Dynamic dispatch broken after obfuscation

### ISSUE THREAD

**Issue by Huxlyx** [obfuscar/obfuscar#158]
Calling methods in obfuscated classes that make use of dynamic dispatch results in RuntimeBinderExceptions.

Consider the following class:
```
using System;

namespace ObfuscarDynDispatch
{
    public class ObfuscatedClass
    {
        public void DispatchThis(dynamic obj)
        {
            DispatchThat(obj);
        }

        private void DispatchThat(int i)
        {
            Console.WriteLine("It's an integer!");
        }

        private void DispatchThat(object o)
        {
            Console.WriteLine("Must be something else");
        }
    }
}
```
After obfuscation with default settings, each call to DispatchThis will result in
> Unhandled Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException:
> 'ObfuscarDynDispatch.ObfuscatedClass' does not contain a definition for 'DispatchThat'

Adding
```
<SkipMethod type="ObfuscarDynDispatch.ObfuscatedClass" rx="DispatchThat" />
```
to the module's configuration circumvents the issue but I guess this shouldn't fail in the first place.
Issue encountered with version 2.2.13.0

**Comment by lextm** [comment]
If I remember correctly, “dynamic dispatch” binds to the name, so it should break after obfuscation changes the name.

Like you discovered, skipping such is the only way.

Obfuscar won't attempt to locate all the name reference, as Mono Cecil does not report such references to it.
