### ISSUE TITLE
Obfuscar with Xamarin

### ISSUE THREAD

**Issue by alberk8** [obfuscar/obfuscar#159]
I have installed the latest version of obfuscar via nuget and recompile my project but it does not seems to be running obfuscar.  What do I need to get this working?.  Is there a working example for Xamarin? 

I am on Windows 10 with  Visual Studio 2017 version 15. 8.5 with Xamarin 4.11.0.776.

Thank you.

**Comment by lextm** [comment]
https://github.com/obfuscar/example

For typical project types, post build event is enough to obfuscate the assemblies.

Xamarin.Android compilation is more complex, where you might hook to another event.

Xamarin.iOS uses AOT, so you don't need Obfusar at all.
