### ISSUE TITLE
How does it work with Visual Studio for Mac

### ISSUE THREAD

**Issue by jianyunli** [obfuscar/obfuscar#160]
Hi 

I have a Mac and installed Visual studio for mac to develop Xamarin forms application. I installed obfuscar through nuget.

How can I use obfuscar in the next step?

thanks

**Comment by jianyunli** [comment]
Ok, I tried the following link
https://blog.lextudio.com/make-obfuscar-a-global-tool-in-net-core-1cc3ee2cfe30

however after running obfuscar , it says the .net core version 2.1.0 preview is not found. My mac has 2.1.2 installed. 

does this need update?

**Comment by lextm** [comment]
You can find the official example on GitHub,

https://github.com/obfuscar/example/blob/master/readme.md
