### ISSUE TITLE
Obfuscar 2.2.1.3 error while compiling .net core 2.1 BUG

### ISSUE THREAD

**Issue by dalopez24** [obfuscar/obfuscar#161]
I'm trying to obfuscate a .net core web app (only the .dll's) with a signied pfx file, the configuration looks like this: 

```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value=".\bin\Release\netcoreapp2.1" />
  <Var name="OutPath" value=".\bin\Release\netcoreapp2.1\Obfuscated" />
  <AssemblySearchPath path="C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.runtime.loader\4.0.0\lib\netstandard1.5" />
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="true" />
  
  <Var name="KeyContainer" value="VS_KEY_4C54F6E7AEDE1B72" />
 
  <Module file="$(InPath)\ApiProgram.dll" />
</Obfuscator>
```

Everything goes good until the obfuscated dll is replaced in the IIS. The code stops working and I get this error through the api: 

> An error occurred while starting the application.
> 
> .NET Core 4.6.26919.02 X64 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 2.1.1-rtm-30846    |    Microsoft Windows 10.0.17134    |   Need help? 

What i'm doing wrong, or this is a bug for the new version of .net core 2.1?

Greetings.

**Comment by lextm** [comment]
`<Var name="KeepPublicApi" value="false" />` is very bad for applications like ASP.NET Core, as many of the building blocks require your types (controllers/views) to follow the naming convention.

Once fully obfuscated with that option, all names are gone, and ASP.NET Core loader won't be able to properly initialize your application at all.

It is recommended to carefully analyze all types of your code base, and exclude the typical ones,

http://docs.obfuscar.com/getting-started/configuration.html#exclusion-rules-by-configuration
