### ISSUE TITLE
Error Code 255 On Compile

### ISSUE THREAD

**Issue by protegesolutions** [obfuscar/obfuscar#162]
The command "C:\VS\Projects\MyProject\MyProject\MyProject\packages\Obfuscar.2.2.12\build\..\tools\obfuscar.console.exe" obfuscar.xml" exited with code 255.

Or

The command "C:\VS\Projects\MyProject\MyProject\MyProject\packages\Obfuscar.2.2.12\build\..\tools\obfuscar.console.exe" obfuscar.xml" exited with code **-532462766**.

Cannot see any difference in my project from the example one. Can't find any reference to a "code 255" or "code -532462766". (Can't find any error code reference at all.)

**Comment by lextm** [comment]
Signing with `.pfx` requires special setup, http://docs.obfuscar.com/getting-started/configuration.html#signing-of-strongly-named-assemblies
