### ISSUE TITLE
Obfuscated exe triggering multiple false positives

### ISSUE THREAD

**Issue by Axemasta** [obfuscar/obfuscar#166]
I used obfuscar on a project at work that needed some sensitive code hiding, it worked well... too well!

The exe has tripped an alarm in SEP (Symantec Endpoint Protection) as a trojan. I uploaded the exe to [Virus Total](https://www.virustotal.com) and the exe triggered detections from 5/69 vendors.

I have since reproduced the issue with a more stripped down program and it is now triggering 3/69 detection engines. 

I have attached the source code without the built exe, you will have to build the exe yourself (since it might trip virus alarms). Simply run the project (it's a hello world console app), then upload the obfuscated exe to Virus Total, it will be detected as a virus.

Here is a link to the source code:
[Obfuscated Virus False Positive.zip](https://github.com/obfuscar/obfuscar/files/2690202/Obfuscated.Virus.False.Positive.zip)

**Comment by Axemasta** [comment]
Here is a screenshot from virus total

![virus total screenshot](https://user-images.githubusercontent.com/33064621/50150784-e6bd9b80-02b6-11e9-8a8b-4a2cb8345442.png)

**Comment by lextm** [comment]
For such you have to report to the vendors and let them fix the false positives. Similar to #155 .

**Comment by Axemasta** [comment]
Yes I have already reported false positives to specifically Symantec. I will do so with the other vendors. 
My only issue is that different vendors flag different malware for different programs. I have tried to obfuscate a few different exe's and they all seem to trip different wires.

I wondered if you had experience with this issue before because I suspect obfuscating exe's in the future will just cause more grief!

**Comment by lextm** [comment]
Unfortunately the nature of obfuscation is that such false positives can happen. Anti-virus can easily report what they could not fully understand as viruses.

Big obfuscation vendors might have the resources to work closely with anti-virus vendors to address such, but this is an open source project, without such luxury.

**Comment by lextm** [comment]
Alternatively, buy a code sign certificate to sign your binaries and then usually anti-virus software won't report any like that.
