### ISSUE TITLE
After ofuscation .exe doesn't work anymore

### ISSUE THREAD

**Issue by edsonharantes** [obfuscar/obfuscar#167]
## Problem

I have 6 .dll files and 1 .exe file to be ofuscated, after the ofuscation, the exe file doesn't work anymore, no error messages, nothing, just don't open.

## Config

I'm using two separate config files, one to .dll and another for .exe file, but the configurations are the same, only the modules are different.

Var name="InPath" value="."
Var name="SolutionDir" value="C:\Users\Usuario\source\repos\teste\testes\" 
Var name="OutPath" value="$(SolutionDir)\Obfuscated" 
Var name="LogFile" value="$(SolutionDir)\mapping\mapping.txt" 
Var name="KeepPublicApi" value="false" 
Var name="HidePrivateApi" value="true" 
Var name="ReuseNames" value="false" 

Module file="$(InPath)\bin\teste.exe" 

**When I use KeepPublicApi set to "true" and HidePrivateApi set to "false" the exe works perfectly** but this is the least safest method (is it not?), wanted to hide everything, or just the private api, but this doesn't work either =/ 

## Resources

I'm using the nugget package on visual studio 2017 Enterprise

**Comment by xx7Ahmed7xx** [comment]
Hello, I also have same problem with my assembly after obfuscating the .dll file, Now it doesn't open, I don't understand the tip you showed above, I tried it but it keeps searching for things (as in the tip) and then nothing useful..

**Comment by KapsbergerS** [comment]
Analogically, It breaks the app:
`Var name="HidePrivateApi" value="true"`
Error:
Item has already beed added. Key in dictionary: '' Key being added '-'.
