### ISSUE TITLE
Certificate doesn't exist. Exit.

### ISSUE THREAD

**Issue by doggy8088** [obfuscar/obfuscar#169]
When I run `dist.pack.bat`, I got the following error:

```log
powershell -file release.ps1
MSBuild doesn't exist. Exit.

powershell -file sign.ps1
Test-Certificate : Cert:\CurrentUser\my\46B0B01ABEEC5A041CA86E6B288A866BC7349EAD
位於 G:\Projects\obfuscar\sign.ps1:1 字元:14
+ ... foundCert = Test-Certificate -Cert Cert:\CurrentUser\my\46B0B01ABEEC5 ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Cert:\CurrentUs...88A866BC7349EAD
   :String) [Test-Certificate]，ArgumentException
    + FullyQualifiedErrorId : InvalidCertPath,Microsoft.CertificateServices.Comma
   nds.TestCertificate

Certificate doesn't exist. Exit.
```

![image](https://user-images.githubusercontent.com/88981/50749519-5dc4cf00-127a-11e9-8054-4c5024847cc5.png)

What is this certificate for?

**Comment by lextm** [comment]
You can ignore the certificate error, as it is used to sign the NuGet package.

Try to open Obfuscar.sln in Visual Studio and compile. That should work if you have VS2017/2019 installed.

**Comment by doggy8088** [comment]
I just realized that it has a submodule `ilspy`.

So here are the steps I built successfully.

```sh
git submodule update --init --recursive
```

Or git clone with `--recurse-submodules` option.

```sh
git clone --recurse-submodules https://github.com/obfuscar/obfuscar.git
```

**Comment by doggy8088** [comment]
The following command fix my msbuild problem if I don't use Visual Studio to build projects.

```sh
dotnet restore -r win
msbuild
```
