### ISSUE TITLE
SkipEnums=true skips all fields

### ISSUE THREAD

**Issue by WildRevenger** [obfuscar/obfuscar#170]
When using the following configuration option:
`<SkipEnums value='true' />`

Obfuscar will also skip all fields.

This weird behaviour can also be observed in Mapping.txt:

> System.Threading.Tasks.Task [myModule]System.Threading.Tasks.Task MyModuleClass::_myTask skipped:  enum rule in configuration

**Comment by lextm** [comment]
Fixed in 2.2.15 release.
