### ISSUE TITLE
HideStrings does not work in .Net core 2.1 App but in assembly

### ISSUE THREAD

**Issue by wolfgangschneider** [obfuscar/obfuscar#173]
Hi
I have a siple solutio with two projects:

* One project is type netcoreapp2.1 (The App)
* The othe one is type netstandard2.0 (The Assembly)

both project have exactly the same class tht should be obfuscated.
``` 
    [System.Reflection.ObfuscationAttribute()]
    internal class ClassToObfuscareInDLL
    {
        public string GetStrProp => "Hello World";

        [System.Reflection.ObfuscationAttribute(Exclude = false)]
        public string GetStr()
        {
            return "Hallo Function";
        }
        [System.Reflection.ObfuscationAttribute(Exclude = false)]
        public string GetStr2()
        {
            return "Das Haus vom Nokolaus";
        }
    }

```

obfuscate.xamle looks
```
<?xml version='1.0'?>

<Obfuscator>
  <Var name="InPath" value=".\bin\Debug\netcoreapp2.1" />
  <Var name="OutPath" value=".\bin\Debug\netcoreapp2.1\Obfuscator_Output" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="MarkedOnly" value="true" />
  
  <!-- <Var name="KeyFile" value=".\test.snk" /> -->
<!--  <Module file="$(InPath)\BasicExampleExe.exe" />-->
  <Module file="$(InPath)\TestObfuscare.dll" />
  <Module file="$(InPath)\TestObfuscareDll.dll" />

</Obfuscator>  
```

All function names are obfuscated in Assembly and in App but not the strings

![image](https://user-images.githubusercontent.com/15703770/51188779-ea0c6d00-18de-11e9-8149-f4d3092550ae.png)

![image](https://user-images.githubusercontent.com/15703770/51188848-10320d00-18df-11e9-9a5d-0d528e0a4944.png)

**Comment by newhillchan** [comment]
I found the same problem. Checked the source codes, 

var encoding = new TypeReference("System.Text", "Encoding", library.MainModule,
                    library.MainModule.TypeSystem.CoreLibrary).Resolve();
                if (encoding == null)
                {
                    _disabled = true;
                    return;
                }

It always return null. I followed mono codes and found it is a bug of Mono. On my machine, mono can not resolve the correct assembly, but ILSpy can. (in BaseAssemblyResolver.Resolve will get System.Runtime for dotnet 4.0 but not for dotnet core, which will find no System.Text in it)

**Comment by liugt34** [comment]
in vs2017 ,open the property of the project,and use
obfuscar.console obfuscar.xml replace ${Obfuscar}  obfuscar.xml

**Comment by wolfgangschneider** [comment]
Hi
I try out obfuscar.console obfuscar.xml but same result. (menwhely i use .net core 3.1 and obfuscar 2.2.26)

![image](https://user-images.githubusercontent.com/15703770/90649599-334f3c00-e23b-11ea-8e5c-c77c8831178a.png)
 assembly wors like a sharm 
![image](https://user-images.githubusercontent.com/15703770/90649760-5d086300-e23b-11ea-94c2-7629f811a285.png)

But main application  not
![image](https://user-images.githubusercontent.com/15703770/90649976-93de7900-e23b-11ea-9d54-f583dd96eba4.png)


Please help
