### ISSUE TITLE
ystem.BadImageFormatException: Corrupted .resources file.

### ISSUE THREAD

**Issue by Xhonor** [obfuscar/obfuscar#174]
Hello. When you try to use obfuscator, this error occurs. How to be?
What's wrong?
```
Unhandled exception: System.BadImageFormatException: Corrupted .resources file. Failed to read resources from file due to invalid header data. Try re-creating the .resources file. ---> System.IO.EndOfStreamException: Reading after the end of the stream is not possible.
    in System.IO .__ Error.EndOfFile ()
    in System.IO.MemoryStream.InternalReadInt32 ()
    in System.Resources.ResourceReader._ReadResources ()
    in System.Resources.ResourceReader.ReadResources ()
    --- End tracing internal exception stack ---
    in System.Resources.ResourceReader.ReadResources ()
    in Obfuscar.Obfuscator.GetXamlDocuments (AssemblyDefinition library)
    in Obfuscar.Obfuscator.RenameTypes ()
    in Obfuscar.Obfuscator.RunRules ()
    in Obfuscar.Program.Main (String [] args)
```

Thanks in advance for your help.

**Comment by lextm** [comment]
If possible, send the assembly you attempted to obfuscate to me via support@lextm.com .

Based on the call stack, this assembly stores its resource files in a way that .NET Framework cannot understand. So there is little Obfuscar can help.

**Comment by paullomeira** [comment]
Dear @lextm, i have the same issue. Can I help to solve it?

Unhandled exception: System.BadImageFormatException: Corrupted .resources file. Failed to read resources from file due to invalid header data. Try re-creating the .resources file. ---> System.IO.EndOfStreamException: Reading after the end of the stream is not possible.
    in System.IO .__ Error.EndOfFile ()
    in System.IO.MemoryStream.InternalReadInt32 ()
    in System.Resources.ResourceReader._ReadResources ()
    in System.Resources.ResourceReader.ReadResources ()
    --- End tracing internal exception stack ---
    in System.Resources.ResourceReader.ReadResources ()
    in Obfuscar.Obfuscator.GetXamlDocuments (AssemblyDefinition library)
    in Obfuscar.Obfuscator.RenameTypes ()
    in Obfuscar.Obfuscator.RunRules ()
    in Obfuscar.Program.Main (String [] args)

**Comment by lextm** [comment]
Similar to other issues related to how ILSpy code used in this project parsing resource files, so the new setting in #324 should have addressed it.
