### ISSUE TITLE
null.referenceexception in all case

### ISSUE THREAD

**Issue by dronamiusSlIVA** [obfuscar/obfuscar#179]
my code is 10,000 lines. The program is quite complicated. But when you protect your software, it falls. I removed the function to hide strings. It did not help. Your software does not work in my case = (

**Comment by dronamiusSlIVA** [comment]
http://prntscr.com/mdkue4

**Comment by dronamiusSlIVA** [comment]
UPD
I downloaded version 2.6.6 and it all worked. thank you for your hard work <3

**Comment by lextm** [comment]
#172
