### ISSUE TITLE
Unable to compile dll (.Net framework 4.7.1)

### ISSUE THREAD

**Issue by bhairav-thakkar** [obfuscar/obfuscar#180]
I am using Visual Studio 2017 with .Net framework 4.7.1 and Obfuscar 2.2.15

I have a multiple project solution with 1 main executable and number of dlls. When I attempt to obfuscate the exe file, it works, but when I try to compile the dll, obfuscar fails. The error I get is:

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
7>     at Ricciolo.StylesExplorer.MarkupReflection.XmlBamlReader.get_Value()
7>     at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
7>     at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
7>     at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
7>     at Obfuscar.Obfuscator.GetXamlDocuments(AssemblyDefinition library)
7>     at Obfuscar.Obfuscator.RenameTypes()
7>     at Obfuscar.Obfuscator.RunRules()
7>     at Obfuscar.Program.Main(String[] args)

I tried switching off all flags.. Just the  input directory and output directory were specified. Still the same issue.

**Comment by lextm** [comment]
Duplicate to #179
