### ISSUE TITLE
 Could not load file or ass embly 'Mono.Options, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' Even i installed Mono.Options

### ISSUE THREAD

**Issue by gopal-k** [obfuscar/obfuscar#182]
When run the Obfuscar.Console.exe system throws the below error

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or ass
embly 'Mono.Options, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' or o
ne of its dependencies. The system cannot find the file specified.
   at Obfuscar.Program.Main(String[] args)

Note: I have installed Mono.Options , Mono.Options, Mono.Security from Nuget Package Manager .

Also i want weather this application is capable to obfustcate the .Net core 2.2 dlls ?

Someone please help me on this

**Comment by lextm** [comment]
In general, the only supported option to use Obfuscar (NuGet package) is demonstrated in the sample project,

https://github.com/obfuscar/example
