### ISSUE TITLE
Variable name change using Obfuscar in my dll

### ISSUE THREAD

**Issue by gopal-k** [obfuscar/obfuscar#183]
I have created the xml file with

<Obfuscator>
  <Var name="InPath" value="\path" />
  <Var name="OutPath" value="\path\output" />
  <Var name="KeyFile" value="$(InPath)\test.snk" />

  <Module file="$(InPath)\XYZSync.dll" >
    <Include path="$(InPath)\LicenseXML.xml" />
  </Module>
    
  
</Obfuscator>

**LicenseXML.xml file is below** 

<?xml version='1.0'?>
<Include>
   <Var name="KeepPublicApi" value="false" />
   <Var name="HidePrivateApi" value="false" />
  <Var name="ReuseNames" value="false" />
  <Var name='signatureToVerify,' value='ABCDEFGHIJKLMN' />
  <Var name='ValidateLicense,' value='XYZABCDE' />
</Include>

I want to change the vraiable name signatureToVerify to ABCDEFGHIJKLMN
and the method name ValidateLicense to XYZABCDE

but this will not work

After processing from Obfuscar still i get the same variable and method name in my dll

**Comment by lextm** [comment]
Obfuscar does not support setting your own names for obfuscated items.
