### ISSUE TITLE
Error on obfuscating a DLL 

### ISSUE THREAD

**Issue by mstrumia** [obfuscar/obfuscar#185]
Hi,
when I try to obfuscate a dll developed with Visual Studio, I get this error message:

"An error occurred during processing:
Failed to get type definitions for CreoParamLm, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f4e4fd84ef410cf6
Cannot clean pool"

I didn't find any info searching with Google for this typology of error, do you have any idea?
Thanks in advance.

**Comment by lextm** [comment]
The actual error message is right above the exception message in console output, https://github.com/obfuscar/obfuscar/blob/784529c9d67a8bb16ec023237b3f1562e2cb0f0c/Obfuscar/AssemblyInfo.cs#L522

**Comment by mstrumia** [comment]
Thank you very much, I will try to solve the problem.
