### ISSUE TITLE
(DE) Obfuscation Help [restore]

### ISSUE THREAD

**Issue by StreamXL** [obfuscar/obfuscar#188]
Hello, I can not remember my project data, is there any possibility of obfuscation, to return again.

That I can look at the source code?

Is there a script or an option to clean the file?

Many greetings

![1](https://user-images.githubusercontent.com/31142317/54397264-2f1e0700-46b6-11e9-94c8-deae573724cb.png)

**Comment by lextm** [comment]
http://docs.obfuscar.com/getting-started/basics.html#caveat
