### ISSUE TITLE
Does obfuscar support cross assembly obfuscation?

### ISSUE THREAD

**Issue by vishnuraom** [obfuscar/obfuscar#189]
Cross Assembly Obfuscation allows renaming of external references thus dramatically increasing the number of obfuscated constructs. Given a set of assemblies that interface each other, Agile.NET will rename classes, methods and fields referenced from other assemblies uniformly. For example, if class A declared in assembly A is referenced from assembly B and Agile.NET renames class A to A1, it will also rename B's external reference from A to A1.
-from [http://secureteam.net/acode-features-detailed](url)

**Comment by lextm** [comment]
http://docs.obfuscar.com/tutorials/basics.html

The sample already shows that.
