### ISSUE TITLE
Issue after obfuscating

### ISSUE THREAD

**Issue by aurangzeb-khan** [obfuscar/obfuscar#190]
My project is .NET Core 2.2 web.
I have installed the obfuscar through Nuget. 
Successfully obfuscated through post build with following config.xml;

name="InPath" value=".\bin\Release\netcoreapp2.2"
name="OutPath" value="$(InPath)\ReadyForDeployment"
name="KeepPublicApi" value="false"
name="HidePrivateApi" value="true"
name="RenameProperties" value="true"
name="RenameEvents" value="true"
name="RenameFields" value="true"
name="HideStrings" value="true"
name="OptimizeMethods" value="true"
Module file="$(InPath)\MyProject.dll"

But issues still persist like following line is not returning proper response after obfuscation;
return Ok(new { message = "Authorization successful" , token = tokenString, userName = verifiedUser.UserName });

Its returning only {} => Empty Object

**Comment by lextm** [comment]
Similar to #165 and other posts. You need to manually add skip rules to avoid obfuscating certain things.
