### ISSUE TITLE
Anonymous Types

### ISSUE THREAD

**Issue by fperez-eypscap** [obfuscar/obfuscar#191]
Hello, I am having issues skipping anonymous types with the latest version. Perhaps you missed the comment on #154 after the issue was closed. Could you review this please? Thanks

**Comment by aurangzeb-khan** [comment]
Adding this line inside the config file solved the issue for me;

`SkipType name="*AnonymousType*" skipProperties="true" skipMethods="true" skipFields="true" skipEvents="true" skipStringHiding="true"`

**Comment by GF-Huang** [comment]
I don't know why not add a feature to skip anonymous like `<Var name="SkipAnonymous" value="true" />`.

**Comment by lextm** [comment]
Duplicate to #130
