### ISSUE TITLE
.net versions supported

### ISSUE THREAD

**Issue by WGMaker** [obfuscar/obfuscar#192]
I can't find which .net versions are supported. I am especially interested in .net 4.7 and .net core 2.2

**Comment by monty241** [comment]
We have used it on both with success. Is not yet as advanced as crypto obfuscator but you can easily add logic.

**Comment by WGMaker** [comment]
Thanks. I will give it a try in both. (your name looks as if you’re Dutch, maybe you are like me)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
