### ISSUE TITLE
mono ?

### ISSUE THREAD

**Issue by WGMaker** [obfuscar/obfuscar#193]
With another obfuscator we had a lot of problems with a .net 4.7 program that runs perfectly without obfuscation. Any positive or negative experience with DotRefiner regarding mono?

**Comment by lextm** [comment]
Other obfuscation tools are not discussed here.

**Comment by WGMaker** [comment]
Sorry, I mixed up names, I meant to ask this for obfuscar. .. will post again.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
