### ISSUE TITLE
Exclude backing field on automatic properties

### ISSUE THREAD

**Issue by KristianWedberg** [obfuscar/obfuscar#196]
# Feature request
Backing fields on automatic properties (which get the name `<OriginalName>k_BackingField`) 
are obfuscated, even if the auto property is explicitly excluded. This is:

- Pointless since the auto property will still show the original name
- Problematic when needing access to the backing field, e.g. for reflection, or certain debugger 
  scenarios that won't work with a renamed backing field

There are work-arounds:
- Exclude the whole class/struct 
  - Also excludes other members
- Change auto property to explicit property with your own backing field, and exclude your backing field
  - A lot more typing
- Use C# 7.3 and also exclude the backing field
  - Doesn't work on earlier language versions. Requires explicitly excluding both the property 
    and the backing field.

Given the work-arounds, this is obviously not a critical feature. If it's relatively easy to do though, it would be great if obfuscar was enhanced to automatically exclude the backing field if the auto property is excluded.

# Current behavior (version 2.2.14)

The backing field `<MyProperty>k_BackingField` is obfuscated:

```C#
[Obfuscation(Exclude = true)]
public T MyProperty { get; set; }
```

# Desired behavior

The backing field `<MyProperty>k_BackingField` is **not** obfuscated:

```C#
[Obfuscation(Exclude = true)]
public T MyProperty { get; set; }
```

**Comment by wegylexy** [comment]
Moreover, when ReuseNames is true, all auto-properties share the same exact field, even different types, which breaks everything.

**Comment by wegylexy** [comment]
Maybe somewhere in `AssemblyInfo.cs` emitting field names without the prefix.

**Comment by lextm** [comment]
This requires some special resolution to find the exact backing fields of the auto properties, but currently no plan to implement that.

Pull requests are welcome.
