### ISSUE TITLE
Outputs "Hiding strings" even when disabled

### ISSUE THREAD

**Issue by breyed** [obfuscar/obfuscar#197]
If you disable string hiding in `obfuscar.xml` like this:

``` xml
<Var name="HideStrings" value="false" />
```

When you obfuscate, the output still shows "Hiding strings...". This makes it seem like the configuration option is being ignored.

**Comment by lextm** [comment]
Such output only indicates the obfuscator is in hiding string phase. All other phases use similar output lines.

No plan to change it.
