### ISSUE TITLE
Unity 2018.2: XCode error when building for iOS (IL2CPP) with .NET 4.x using obfuscated C# DLL 

### ISSUE THREAD

**Issue by RuiBEAT** [obfuscar/obfuscar#201]
Hello,

I have been using Obfuscar with success for managed DLLs obfuscation that I'm using from Unity 2018.2 (using .NET 2.0). Recently, I have been forced to update my project Scripting Runtime version and Api Compatibility Level to .NET 4.x due some external dependencies requirements. Since then I haven't been able to build my Unity project for iOS due a compiling time semantic issue with the IL2CPP generated code. Every time it throws the same error on the <PrivateImplementationDetails> .cctor() for the managed DLL.

```cpp
// System.Void <PrivateImplementationDetails>{DD48BE6E-5DB1-4824-AEC7-412718C95E39}.81E3B0DD-52D3-43EB-8D19-FBBCC40F54CB::.cctor()
extern "C" IL2CPP_METHOD_ATTR void U381E3B0DDU2D52D3U2D43EBU2D8D19U2DFBBCC40F54CB__cctor_m3364342854 (RuntimeObject * __this /* static, unused */, const RuntimeMethod* method)
{
	static bool s_Il2CppMethodInitialized;
	if (!s_Il2CppMethodInitialized)
	{
		il2cpp_codegen_initialize_method (U381E3B0DDU2D52D3U2D43EBU2D8D19U2DFBBCC40F54CB__cctor_m3364342854_MetadataUsageId);
		s_Il2CppMethodInitialized = true;
	}
	int32_t V_0 = 0;
	{
		StringU5BU5D_t1281789340* L_0 = (StringU5BU5D_t1281789340*)SZArrayNew(StringU5BU5D_t1281789340_il2cpp_TypeInfo_var, (uint32_t)0);
		((U381E3B0DDU2D52D3U2D43EBU2D8D19U2DFBBCC40F54CB_t4239457874_StaticFields*)il2cpp_codegen_static_fields_for(U381E3B0DDU2D52D3U2D43EBU2D8D19U2DFBBCC40F54CB_t4239457874_il2cpp_TypeInfo_var))->set__2(L_0);
		ByteU5BU5D_t4116647657* L_1 = (ByteU5BU5D_t4116647657*)SZArrayNew(ByteU5BU5D_t4116647657_il2cpp_TypeInfo_var, (uint32_t)0);
		ByteU5BU5D_t4116647657* L_2 = L_1;
		RuntimeFieldHandle_t1871169219  L_3 = { reinterpret_cast<intptr_t> (U381E3B0DDU2D52D3U2D43EBU2D8D19U2DFBBCC40F54CB_t4239457874_____0_FieldInfo_var) };
		RuntimeHelpers_InitializeArray_m4077124945(NULL /*static, unused*/, (RuntimeArray *)(RuntimeArray *)L_2, L_3, /*hidden argument*/NULL);
		((U381E3B0DDU2D52D3U2D43EBU2D8D19U2DFBBCC40F54CB_t4239457874_StaticFields*)il2cpp_codegen_static_fields_for(U381E3B0DDU2D52D3U2D43EBU2D8D19U2DFBBCC40F54CB_t4239457874_il2cpp_TypeInfo_var))->set__1(L_2);
		V_0 = 0;
		goto IL_0040;
	}

IL_0025:
	{
		ByteU5BU5D_t4116647657* L_4 = ((U381E3B0DDU2D52D3U2D43EBU2D8D19U2DFBBCC40F54CB_t4239457874_StaticFields*)il2cpp_codegen_static_fields_for(U381E3B0DDU2D52D3U2D43EBU2D8D19U2DFBBCC40F54CB_t4239457874_il2cpp_TypeInfo_var))->get__1();
		int32_t L_5 = V_0;
		ByteU5BU5D_t4116647657* L_6 = ((U381E3B0DDU2D52D3U2D43EBU2D8D19U2DFBBCC40F54CB_t4239457874_StaticFields*)il2cpp_codegen_static_fields_for(U381E3B0DDU2D52D3U2D43EBU2D8D19U2DFBBCC40F54CB_t4239457874_il2cpp_TypeInfo_var))->get__1();
		int32_t L_7 = V_0;
		NullCheck(L_6);
		int32_t L_8 = L_7;
		uint8_t L_9 = (L_6)->GetAt(static_cast<il2cpp_array_size_t>(L_8));
		int32_t L_10 = V_0;
		NullCheck(L_4);
		(L_4)->SetAt(static_cast<il2cpp_array_size_t>(L_5), (uint8_t)(((int32_t)((uint8_t)((int32_t)((int32_t)((int32_t)((int32_t)L_9^(int32_t)L_10))^(int32_t)((int32_t)170)))))));
		int32_t L_11 = V_0;
		V_0 = ((int32_t)il2cpp_codegen_add((int32_t)L_11, (int32_t)1));
	}

IL_0040:
	{
		int32_t L_12 = V_0;
		ByteU5BU5D_t4116647657* L_13 = ((U381E3B0DDU2D52D3U2D43EBU2D8D19U2DFBBCC40F54CB_t4239457874_StaticFields*)il2cpp_codegen_static_fields_for(U381E3B0DDU2D52D3U2D43EBU2D8D19U2DFBBCC40F54CB_t4239457874_il2cpp_TypeInfo_var))->get__1();
		NullCheck(L_13);
		if (((((int32_t)L_12) < ((int32_t)(((int32_t)((int32_t)(((RuntimeArray *)L_13)->max_length))))))? 1 : 0))
		{
			goto IL_0025;
		}
	}
	{
		return;
	}
}
```
The **RuntimeFieldHandle_t1871169219** is not defined (the RuntimeHelpers_InitializeArray_m4077124945 doesn't seem to be defined either...). I double checked the obfuscar config (although it is not modified with respect to when it was functional for .NET 2.0) and I have been playing with the project settings (enabling "unsafe" code, disabling code stripping, etc...) without success.

If I set my "RootNamespace*" for being skipped from obfuscation, the "PrivateImplementationDetails" doesn't get generated on the assembly, and everything works just fine, but if I enable obfuscation for anything, this class is built in the DLL, and the same error is thrown from XCode when building a iOS release: **20897:3: Unknown type name 'RuntimeFieldHandle_t1871169219'**.

Building an Android release works just fine (as well as does the desktop version).

Any clue that can shed light on this matter, please?

Thanks in advance,

**Comment by lextm** [comment]
I don't have a Unity environment to test, so it is not trivial to me what might be the cause.

Can you disable string hiding and try again?

**Comment by RuiBEAT** [comment]
Thanks for the quick response.

You nailed it, disabling string hiding fixes the problem.

**Comment by lextm** [comment]
String hiding weaves some extra code into the assemblies, which sounds like IL2CPP cannot handle properly.

I am not sure if string hiding is in fact needed for Unity apps, as IL2CPP should obfuscate things automatically.

**Comment by RuiBEAT** [comment]
Yeah, but I'm using the same DLL managed assembly for several architectures, and not all of them use IL2CPP. I'm interested in obfuscate things for this assembly, but not for all the source code.

Until now I was able to keep using only one managed DLL even using IL2CPP. With the .NET 4.x seems this is not possible anymore (because of the string hidding as you said), but anyways, I could use different assemblies if I want to keep strings hidden on other scripting backends different from IL2CPP.

Thank you,

**Comment by rozatlab** [comment]
Apologies if this is an obvious question, is the "string hiding" you mentioned disabling in Unity or in Xcode? After a fair amount of searching I haven't been able to find it. I'm having an issue building to iOS that this may help. Appreciate any advice!

**Comment by RuiBEAT** [comment]
> Apologies if this is an obvious question, is the "string hiding" you mentioned disabling in Unity or in Xcode? After a fair amount of searching I haven't been able to find it. I'm having an issue building to iOS that this may help. Appreciate any advice!

@rozatlab  Not Unity or Xcode. The "string hiding" I have switched off is an _Obfuscar_ setting on the xml configuration file.

`<Var name="HideStrings" value="false" />`
