### ISSUE TITLE
keyFile="auto" option not working

### ISSUE THREAD

**Issue by schlabm** [obfuscar/obfuscar#202]
Per the following:
[Obfuscar Documentation](https://docs.obfuscar.com/getting-started/configuration.html#signing-of-strongly-named-assemblies)
The KeyFile option allow for use of special key name "auto" is not supported. Using configuration of
   `<Var name="KeyFile" value="auto"/>`
output is
An error occurred during processing:
Failure loading key file "auto"

**Comment by lextm** [comment]
Thanks for reporting this. The relevant code must be deleted by mistake.

**Comment by lextm** [comment]
You might try 2.2.19 release now.

**Comment by schlabm** [comment]
Thank you, we'll take a look at it.
