### ISSUE TITLE
Optimal settings

### ISSUE THREAD

**Issue by MagnusH68** [obfuscar/obfuscar#203]
I develop and sell a .NET library in .NET Framework 4.6, .NET Core 2.0 and .NET Standard 2.0, and need an obfuscator. Will Obfuscar be a good choise, and if so what would the optimal settings be?

I want to obfuscate as much as possible except whatever is needed by the users of the API obviously like public classes, or classes used in XML serialization. String obfuscation is ok, I don't have any performance tasks related to strings.

**Comment by lextm** [comment]
You might follow our documentation to do an evaluation,

https://docs.obfuscar.com/
