### ISSUE TITLE
Error when linking to obfuscated libraru

### ISSUE THREAD

**Issue by MagnusH68** [obfuscar/obfuscar#205]
I have a .NET Framework 4.6 library that is ofcuscated with obfuscar, but when I try to use it from a WPF application I get this error: 
`Unknown build error, 'Cannot resolve dependency to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve `event.'`

Linking to the same library but non-obfuscated works.

**Comment by lextm** [comment]
Sounds like string hiding feature adds a reference to `System.Private.CoreLib` for some reason. 

Please disabling string hiding and try again.

**Comment by MagnusH68** [comment]
I got this error when compiling, I got rid of the compile error by setting SuppressIldasm = false, but then I got a "missing System.Private.CoreLib" when starting the application. Setting HideStrings to false solved that.

HideStrings is a feature I would like to use though!

**Comment by lextm** [comment]
Besides, it is strange why `System.Private.CoreLib` appears here. A typical .NET Framework/WPF project only uses `mscorlib`, or `System.Runtime`.

**Comment by Tyr3al** [comment]
I have go the same problem, when I obfuscate my netstandard2.0 library and try to use it in an standard netframework 4.7.2 project. 
When I turn of "HideStrings" it works.

**Comment by huyhu** [comment]
I have the same problem, HideStrings didn't work for me. Any update on this?

**Comment by RobertHudjakov** [comment]
Have the problem when using the dotnet global tool. My library will reference System.Private.CoreLib.

![image](https://user-images.githubusercontent.com/43573408/80479344-8da85200-8957-11ea-9e67-f566e74df8a8.png)

This causes the issue:
<p>&nbsp; &nbsp; &lt;Exec Command=&quot;dotnet tool install --global Obfuscar.GlobalTool --version 2.2.25&quot; IgnoreExitCode=&quot;true&quot;/&gt;</p>
<p>&nbsp; &nbsp; &lt;Exec Command=&quot;Obfuscar.Console -s obfuscation.xml &quot; WorkingDirectory=&quot;$(OutDir)&quot; /&gt;</p>

This works fine:
<p>&nbsp; &nbsp; &lt;Exec Command=&quot;%userprofile%\.nuget\packages\obfuscar\2.2.25\tools\Obfuscar.Console -s obfuscation.xml &quot; WorkingDirectory=&quot;$(OutDir)&quot; /&gt;</p>

HideStrings did not help.

**Comment by meum** [comment]
I had the same problem and the solution provided by @RobertHudjakov works.

It seems that using the obfuscar global tool adds a reference to System.Private.CoreLib, but using the nuget version of obfuscar does not.

**Comment by ggaller** [comment]
The problem begins with this [line](https://github.com/obfuscar/obfuscar/blob/d11f455af81a20209a0d746077447f50f7074f92/Obfuscar/Obfuscator.cs#L1518).  
The type `System.Text.Encoding` is resolved from assembly `System.Private.CoreLib` and when we call `ImportReference` later the reference to the `System.Private.CoreLib` adding to our assembly.
I don't know how to fix this behaviour.

**Comment by lextm** [comment]
The solution is to use .NET SDK Global Tools only on .NET Core assemblies. In other cases, use the Obfuscar NuGet package.

Its core assembly resolution mechanism is affected by .NET Core runtime, so won't work well with .NET Framework assemblies.
