### ISSUE TITLE
StripAfterObfuscation on ObfuscationAttribute not honored

### ISSUE THREAD

**Issue by gunsh** [obfuscar/obfuscar#212]
Even though **ObfuscationAttribute** works great, the property **StripAfterObfuscation** does not seem to be honored. The default value of this property is **true** so Obfuscar should strip this attribute from obfuscated code.

**Comment by gunsh** [comment]
@lextm I see this happening again after upgrading to 2.2.29 from 2.2.28. I haven't had the time to check but perhaps it is worth adding a test making sure this keeps on working in the future. Something must have broken.

**Comment by lextm** [comment]
The test case has been added a long while ago, 

https://github.com/obfuscar/obfuscar/blob/master/Tests/ObfuscationAttributeTests.cs#L196

Probably something else happens now, but you need to provide more information.

**Comment by gunsh** [comment]
My own test failed after upgrading. I verified by decompiling using DotPeek and the code was obfuscated but the attribute was still there. As soon as I downgraded, things were back to normal.

I will investigate and try to reproduce.
