### ISSUE TITLE
Skip property from generics

### ISSUE THREAD

**Issue by fabriciomurta** [obfuscar/obfuscar#214]
I think I hit a bug in Obfuscar while upgrading from 2.2.10 to 2.2.22 where an interface's property is not properly handled, so I get `Method X in type Y from assembly Z does not have an implementation` error while trying to build applications that links against the obfuscated lib.

The problem here is I can't seem to be able to properly skip ignoring the type so that it is not crunched out by Obfuscar.

This more or less reproduces the scenario:

**file1.cs**
```csharp
namespace My.Application.Here
{
    public interface IIface
    {
            string Error { get; set; }
            bool Success { get; set; }
    }
}
```

**file2.cs**
```csharp
namespace My.Application.Here
{
    public class Implemme<T> : IIface
    {
            public string Error { get; set; }
            public bool Success { get; set; }
    }
}
```

So, what I would get when I try to reference this from outside is something like:

`Method 'get_Error' in type My.Application.Here.a from assembly 'MyAssembly, Verison=1.0.0.0, (...)' does not have an implementation`

Adding this to `obfuscar.xml` didn't help:

```xml
<SkipProperty type="My.Application.Here.Implemme" name="Error" />
```

I suspect that's because I should prepend/append something as `Implemme` is a generic type. Should I just use a regexp (that may potentially hit stuff I didn't want to if the names get similar), or is there a way to ensure I only get the very type (and its possible type specifications)?

**Comment by lextm** [comment]
Please provide a complete sample project.

**Comment by fabriciomurta** [comment]
I can't promptly write a dummy solution to reproduce the issue, I was actually just looking into ways to properly override the default behavior at least to get going.

I walked back between versions and 2.2.20 works for me (so introduced with 2.2.21 if that helps). I'll close this issue now and reopen when I have time to provide a test case.

**Comment by fabriciomurta** [comment]
not too big a diff between versions .20 and .21... the commit 3bd00128cc0bc938a1474a56aafae32bd263d9f7 is really likely to be the one that introduced the issue for me.
