### ISSUE TITLE
Custom Button Click

### ISSUE THREAD

**Issue by veyiwah123** [obfuscar/obfuscar#215]
```
public class CustomButton : Button
    {
    }
```

```
<Window x:Class="Test.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:UsersControl="clr-namespace:Test.UsersControl"
        mc:Ignorable="d">
    <Grid>
       <UsersControl:CustomButton Click="btnMessage_Click"/>
    </Grid>
</Window>
```
  ```
public partial class MainWindow : Window
    {        
     private void btnMessage_Click(object sender, RoutedEventArgs e)
        {
            MessageBox.Show("Hello");
        }
   }
```

```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value=".\in" />
  <Var name="OutPath" value=".\out" />
  
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="RenameProperties" value="false" />
  
  <Module file="$(InPath)\Test.exe" />
</Obfuscator>
```

Exception
System.Windows.Markup.XamlParse
CLR20r3
mscorlib

**Comment by veyiwah123** [comment]
```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value=".\in" />
  <Var name="OutPath" value=".\out" />
  
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="RenameProperties" value="false" />
  
  <Module file="$(InPath)\Test.exe" />
</Obfuscator>
```

**Comment by lextm** [comment]
What exactly does the exception say? For WPF project, it is recommended that you exclude anything related to the user interface from renaming, as obfuscating on them can break XAML/BAML side.

**Comment by veyiwah123** [comment]
> What exactly does the exception say? For WPF project, it is recommended that you exclude anything related to the user interface from renaming, as obfuscating on them can break XAML/BAML side.

  Problem event name:	CLR20r3
  Problem signature 01:	Test.exe
  Problem signature 02:	1.0.0.0
  Problem signature 03:	5d16bfe0
  Problem signature 04:	mscorlib
  Problem signature 05:	4.7.2558.0
  Problem signature 06:	59d412f7
  Problem signature 07:	6d2
  Problem signature 08:	ac
  Problem signature 09:	System.Windows.Markup.XamlParse
  OS version:	6.1.7601.2.1.0.256.48
  Language code:	1049
  More information 1:	0a9e
  More information 2:	0a9e372d3b4ad19135b953a78882e789
  More information 3:	0a9e
  More information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by veyiwah123** [comment]
Full project
[TestClick.zip](https://github.com/obfuscar/obfuscar/files/3341308/TestClick.zip)

**Comment by lextm** [comment]
Where is your obfuscation configuration file?

**Comment by lextm** [comment]
You set `<Var name="KeepPublicApi" value="false" />` so that `CustomButton` is renamed. However, Obfuscar does not modify the BAML and when `XamlParse` tries to process `<UsersControl:CustomButton Click="btnMessage_Click"/>` it cannot find where `CustomButton` is.

Please exclude CustomButton from obfuscation.

**Comment by veyiwah123** [comment]
> You set `<Var name="KeepPublicApi" value="false" />` so that `CustomButton` is renamed. However, Obfuscar does not modify the BAML and when `XamlParse` tries to process `<UsersControl:CustomButton Click="btnMessage_Click"/>` it cannot find where `CustomButton` is.
> 
> Please exclude CustomButton from obfuscation.

KeepPublicApi changes do not affect the result
Not. If you look in the reflector.

2 test

1) Click in simple button
```
<Button Click="btnMessage_Click" Content="Simple" Margin="0,150,0,0"/>
 <local:CustomButton Content="Custom" Margin="0,0,0,200"/>
```
2) Click in custom button
<Button Content="Simple" Margin="0,150,0,0"/>
 <local:CustomButton Click="btnMessage_Click" Content="Custom" Margin="0,0,0,200"/>

In both cases there is NO name change.
`internal class CustomButton : Button 
{     
    // Methods     public CustomButton(); 
}
`
In both cases, the name changes.
`private void A(object, RoutedEventArgs) 
{     
    MessageBox.Show(DFC15DA2-06EF-4470-B8C3-B6759E287474.B());
}`

And now the differences

(1)Click in simple button

```
[DebuggerNonUserCode, GeneratedCode("PresentationBuildTasks", "4.0.0.0"), EditorBrowsable(EditorBrowsableState.Never)]
void IComponentConnector.Connect(int num1, object obj1)
{
    if (num1 == 1)
    {
        ((Button) obj1).Click += new RoutedEventHandler(this.A);
    }
    else
    {
        this.A = true;
    }
}
```

(2)Click in custom button
```
[DebuggerNonUserCode, GeneratedCode("PresentationBuildTasks", "4.0.0.0"), EditorBrowsable(EditorBrowsableState.Never)]
void IComponentConnector.Connect(int, object)
{
    this.A = true;
}
```

**Comment by lextm** [comment]
Duplicate to #551
