### ISSUE TITLE
Could not load file or assembly 

### ISSUE THREAD

**Issue by leminhthanh1998** [obfuscar/obfuscar#220]
Hi!
I have a wpf project target on .net framework 4.6.1 and it 's using Microsoft.AspNetCore.WebUtilities.
After using obfuscar, it has this error: 
` An unhandled exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies`
And this is my config.xml:
```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value="." />
  <Var name="OutPath" value=".\Obfuscator_Output" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="UseUnicodeNames" value="true" />
  <Var name="HideStrings" value="true" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="true" />
  <Module file="$(InPath)\Test.exe" />
</Obfuscator>
```

**Comment by lextm** [comment]
https://docs.obfuscar.com/support/faq.html#how-to-troubleshoot-resolutionexception-or-assemblyresolutionexception

**Comment by leminhthanh1998** [comment]
Excuse me sir!
My exe file is in the same folder with dll file, so I try to use 
`<AssemblySearchPath path="." />`
and 
`<AssemblySearchPath path=".\Microsoft.AspNetCore.Http.Abstractions.dll" />`
but it still has that error
