### ISSUE TITLE
Renaming resources breaks application

### ISSUE THREAD

**Issue by Mecanik** [obfuscar/obfuscar#222]
I believe this is related to the issue from 2016: https://github.com/obfuscar/obfuscar/issues/83

However in my case, a win forms app with .net 4.5, having multiple resource files to allow language selection, obsfuscar breaks it.

The stranger things is I set:

```
  <Var name="HideStrings" value="false" />
 <Var name="RenameProperties" value="false" />
```

However the obfuscator still does it! 

Here are some logs:

Skipped Types:

Renamed Resources:

APPLICATION.en_locale.resources ->  . .resources
APPLICATION.NAMESPACE.resources ->  . .resources
APPLICATION.Settings.resources ->  . .resources
APPLICATION.spn_locale.resources ->  . .resources
APPLICATION.Properties.Resources.resources ->  .​.resources

Skipped Resources:

APPLICATION.chi_locale.resources (no clear new name)
APPLICATION.rus_locale.resources (no clear new name)
APPLICATION.vit_locale.resources (no clear new name)

**Comment by Mecanik** [comment]
Documentation is very poor as well, you cannot ignore resources. Or string. Or anything else, nothing works literally like in the documentation....

Someone give some assistance please ?

**Comment by lextm** [comment]
Thanks for reporting this. This might be a bug, as the original developers didn't test again such cases.

I am currently occupied by other stuffs so investigation on this can take long.

You might try other open source obfuscation tool, or send me a pull request if you happen to fix it.

**Comment by Mecanik** [comment]
Trust me if I could fix this I would... but I do not even have the patience. I worked so hard to release something ASAP and this was a massive surprise for me...

Is there literally no way to just completely ignore resources ? ( .resx )

**Comment by Mecanik** [comment]
New logs...

```
Hiding strings...
1>  
1>  Unhandled Exception: System.NotSupportedException: Cannot read resources that depend on serialization.
1>     at System.Resources.ResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
1>     at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
1>     at System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
1>     at System.Resources.ResourceReader.ResourceEnumerator.get_Current()
1>     at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
1>     at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
1>     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
1>     at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
1>     at Obfuscar.Obfuscator.GetXamlDocuments(AssemblyDefinition library) in F:\obfuscar\Obfuscar\Obfuscator.cs:line 706
1>     at Obfuscar.Obfuscator.RenameTypes() in F:\obfuscar\Obfuscar\Obfuscator.cs:line 506
1>     at Obfuscar.Obfuscator.RunRules() in F:\obfuscar\Obfuscar\Obfuscator.cs:line 130
1>     at Obfuscar.Program.Main(String[] args) in F:\obfuscar\GlobalTools\Program.cs:line 115
1>  Renaming:  fields...Parameters...Properties...Events...Methods...Types...
```

**Comment by Mecanik** [comment]
By some miracle, I was able to compile again. However the issue from my initial post remains, the resources get so messed up that when I try to find a resource during runtime the application will fail.

In my case, locale resources ( strings ):

`_res_man = new ResourceManager("APPLICATION.en_locale", Assembly.GetExecutingAssembly());`

This will fail after obfuscation.

**Comment by Mecanik** [comment]
Just another update, I found out that if I remove "ResXFileCodeGenerator" from Properties -> Custom tool, obfuscator will ignore that resource.

Thus allowing my app to work later on when I search for a resource. If there is a solution for this please let me know.

**Comment by Mecanik** [comment]
To clarify the following are the issues:

- APPLICATION.chi_locale.resources are being renamed to ".resource" thus you cannot reference to them anymore during runtime
- There is no "easy" way to ignore resources or customize their obfuscation

The best solution would be to encrypt the data in the resource but either keep it's name or give it some UID that you can use later in ResourceManager to access it. 

I cannot believe that nobody used resources before and has not hit this issue.

**Comment by Mecanik** [comment]
Anybody ?

**Comment by Mecanik** [comment]
Same issue affects other applications that have multiple .resx files: https://github.com/ravibpatel/AutoUpdater.NET/issues/307

We need a solution...

**Comment by LeandroSeg** [comment]
Same Problem Here, same error!   :(

**Comment by tewarid** [comment]
I am having a similar issue with a Windows Forms application, that I was able to fix by configuring obfuscar to ignore the internal Resources class thus

```xml
  <Module file="$(InPath)/MyApp.exe">
    <SkipType name="MyAppDefaultNamespace.Properties.Settings" skipProperties="true" />
    <SkipType name="MyAppDefaultNamespace.Properties.Resources" skipProperties="true" />
```

**Comment by BBUBBA** [comment]
Same trouble too....
T.T

**Comment by phl025** [comment]
I have an issue with multiples Windows Forms application using localized resources.

* Firts test :
Renamed Resources:
User_Functions.User.resources -> A.C.resources
GdP_Analyser.About.resources -> A.U.resources
GdP_Analyser.Info_Message.resources -> A.v.resources
GdP_Analyser.Main_Windows.resources -> A.W.resources
GdP_Analyser.Properties.Resources.resources -> a.A.resources
Skipped Resources:

* with skiptype :
Renamed Resources:
GdP_Analyser.Properties.Resources.resources -> A.w.resources
Skipped Resources:
User_Functions.User.resources (type rule in configuration ([GdP_Analyser]User_Functions.User))
GdP_Analyser.About.resources (type rule in configuration ([GdP_Analyser]GdP_Analyser.About))
GdP_Analyser.Info_Message.resources (type rule in configuration ([GdP_Analyser]GdP_Analyser.Info_Message))
GdP_Analyser.Main_Windows.resources (type rule in configuration ([GdP_Analyser]GdP_Analyser.Main_Windows))

` <Module file="$(InPath)\GdP_Analyser.exe">`
`	<SkipType name="User_Functions.User" skipProperties="true" />`
`	<SkipType name="GdP_Analyser.About" skipProperties="true" />`
`	<SkipType name="GdP_Analyser.Info_Message" skipProperties="true" />`
`	<SkipType name="GdP_Analyser.Main_Windows" skipProperties="true" />`
`

**Comment by lextm** [comment]
Duplicate to #208
