### ISSUE TITLE
EnumMember Attributes removed during obfusaction

### ISSUE THREAD

**Issue by HeathJared** [obfuscar/obfuscar#224]
We have a large application with several `Enum` decorated with `[EnumMember]` which are used for serialization. After obfuscation, all `[EnumMember]` attributes are removed causing serialization and de-serialization to fail.

Obfuscar 2.2.24.0 (latest at the time) was install via NuGet Package.

I have not been able to test if 2.2.23.0 has this issue (before the Mono.Cecil update).

---

As a hunch, it may be related to `[AttributeUsage]` attributes when loading (and filtering) custom attributes. For example:

`[DataMember]` attributes work.
```
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
    public sealed class DataMemberAttribute : Attribute
```

`[EnumMember]` attributes do not work.
```
    [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    public sealed class EnumMemberAttribute : Attribute
```

If custom attributes are being filtered by `AttributeTargets.Property` then `[EnumMember]` will not be picked up. 

---

The project is obfuscated with the following flags:

```
  <Var name="KeepPublicApi" value="false" />
  <Var name="ReuseNames" value="false" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="HideStrings" value="true" />
  <Var name="SuppressIldasm" value="true" />  
```

Here is a simplified example of the issue:

Original Class

```
using System.Runtime.Serialization;
​
[DataContract]
public enum SuppressionType
{
    [EnumMember(Value = "none")] None,
    [EnumMember(Value = "partial")] Partial,
    [EnumMember(Value = "low")] Low,
    [EnumMember(Value = "high")] High
}
```

Produced Output:

```
using System;
using System.Runtime.Serialization;

[DataContract]
public enum dy
{
    qA,
    qa,
    qB,
    qb
}
```

The decompiled code was produced using the ILSPY tool.

As you can see, all enum fields are missing the `[EnumMember]` attribute and our serialization and de-serialization process fails.

**Comment by Jascen** [comment]
I'm not familiar enough with the Obfuscar codebase to determine if this is 100% correct, but I was able to track down that EnumMember still exists with proper values within the AssemblyDefinition by the time 'info.Definition.Write(outName, parameters);' is called from inside 'SaveAssemblies()'.

**Comment by HeathJared** [comment]
This may be an issue with ILSpy and ASP.NET Core binders. Closing this until I have more information.

**Comment by HeathJared** [comment]
Confirmed that this was not an issue with Obfuscar. Updating ILSpy shows the EnumMember attributes.

For anyone else having this issue with .NET Core 2.2, our solution was to add a custom configuration binder. Specifically, adding support for EnumMember and DataMember in this method:

```
         private static void BindProperty(PropertyInfo property, object instance, IConfiguration config, BinderOptions options)
        {
            // We don't support set only, non public, or indexer properties
            if (property.GetMethod == null ||
                (!options.BindNonPublicProperties && !property.GetMethod.IsPublic) ||
                property.GetMethod.GetParameters().Length > 0)
            {
                return;
            }

            var propertyValue = property.GetValue(instance);
            var hasSetter = property.SetMethod != null && (property.SetMethod.IsPublic || options.BindNonPublicProperties);

            if (propertyValue == null && !hasSetter)
            {
                // Property doesn't have a value and we cannot set it so there is no
                // point in going further down the graph
                return;
            }

            // PATCH STARTS HERE

            if (property.PropertyType.IsEnum)
            {
                if (propertyValue == null) return;

                var memberName = propertyValue.ToString();
                var sectionKey = property.PropertyType.GetMember(memberName).FirstOrDefault()?.GetCustomAttribute<EnumMemberAttribute>()?.Value ?? memberName;
                propertyValue = BindInstance(property.PropertyType, propertyValue, config.GetSection(sectionKey), options);
            }
            else
            {
                var sectionKey = property.GetCustomAttribute<DataMemberAttribute>()?.Name ?? property.Name;
                propertyValue = BindInstance(property.PropertyType, propertyValue, config.GetSection(sectionKey), options);
            }

            // PATCH ENDS HERE

            if (propertyValue != null && hasSetter)
            {
                property.SetValue(instance, propertyValue);
            }
        }
```

This was forked from the [ConfigurationBinder.Bind(instance)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationbinder.bind?view=aspnetcore-2.2) methods.
