### ISSUE TITLE
Unit testing with Moq

### ISSUE THREAD

**Issue by gunsh** [obfuscar/obfuscar#227]
I have created a repo demonstrating the issue: https://github.com/gunsh/obfuscar-moq-issue

The solution has just one unit test project using Moq from NuGet. The project has 3 build configurations. Debug and Release are not obfuscated and pass all tests. The ReleaseObfuscar obfuscates the test assembly and passes 2 out of 4 tests. One of the tests makes sure the test is actually performed on an obfuscated assembly. The other 3 tests actually demonstrate the problem.

There are 3 identical public interfaces: ITest1, ITest2 and ITest3, each with a single string property. Here are the specifics:
1. ITest1 is decorated with [Obfuscation] - passes the test.
2. ITest2 is identical to ITest1 except it is NOT decorated with [Obfuscation] - fails the test.
3. ITest3 is identical to ITest1, decorated with [Obfuscation] but has a single (unused) derived class Test3 - fails the test.

All 3 tests are identical. Each is using a different ITest interface. A mock object is created, property is assigned value and then tested.

With obfuscation ON, only test 1 passes while 2 and 3 fail.

I might understand why test 2 is failing but I am totally confused that 3 is failing as well. The mere fact that a class exists that derives from an interface makes it special so that the test would fail.

I am not quite sure if this is a Moq issue or an Obfuscar issue or something that relates to both combined. I would appreciate any insight.

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.
