### ISSUE TITLE
How does one debug \Obfuscar.console.exe exited with code 1?

### ISSUE THREAD

**Issue by Quazaka** [obfuscar/obfuscar#228]
I am getting the error 
`""C:\repo\X\packages\Obfuscar.2.2.24\build\..\tools\obfuscar.console.exe" obfuscar.xml" exited with code 1.	`
I am unsure how i would debug what i have done wrong here.
Besides, how does this work with the ClickOnce publish functionality in Visual studio?

The content of my obfuscar.xml file is 
```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value=".\bin\Release\" />
  <Var name="OutPath" value=".\Obfuscator_Output" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="KeyFile" value=".\ObsfuKey.snk" />

  <Module file="$(InPath)\Test.exe" />
</Obfuscator>
```
I have the ObsfuKey.snk next to my obfuscar.xml
Post-build event:
    "$(Obfuscar)" obfuscar.xml

**Comment by MusaSakkaf** [comment]
seriously!
what is the solution for that issue?
