### ISSUE TITLE
Obfuscation fails for generic + nested classes

### ISSUE THREAD

**Issue by MirandaDotNet** [obfuscar/obfuscar#229]
Hi,
We had the following source code (which resided in the same file):
`
public class Test<T>
{
       private T[] _entries;

       public IEnumerator<T> GetEnumerator()
       {
           for (int i = 0; i < _entries.Length; ++i)
               yield return _entries[i];
       }

   }

   public class Test2<A> :Test<A>
   {
       private A[] _entries;

       public IEnumerator<A> GetEnumerator()
       {
           for (int i = 0; i < _entries.Length; ++i)
               yield return _entries[i];
       }

   }`

When we obfuscated it, we were unable to run it, because of the error message something like The method 'A.A`2[System.Decimal,System.Decimal].A' is not a property accessor.

On further digging we discovered that if we leave only one class Test in the file, it gets fully obfuscated (the name 'Test' gets changed) even though it is public and we excluded public from obfuscation.

This led us to the following commit: https://github.com/obfuscar/obfuscar/commit/3bd00128cc0bc938a1474a56aafae32bd263d9f7.
While debugging we discovered that the public class with nested type and generic property (because nested type is generated by .net for yield and enumerator) gets renamed anyways. Moreover it gets renamed on "analysis" stage, not on "rename" stage which the code would suggest.

We reverted the commit on our side and obfuscation works. However this is not the solution, because we dont know the intent of the fix.

Regards,
Marina

**Comment by lextm** [comment]
You should be using 2.2.23 now, which no longer includes that commit.
