### ISSUE TITLE
Obfuscate Across Assemblies

### ISSUE THREAD

**Issue by BobbyShoe** [obfuscar/obfuscar#237]
Is there a way to Obfuscate code across assemblies?  So for example assume I have EXE A and DLL B.  B is only used by A for scope of the obfuscation.  So as an example all public function calls could be obfuscated in DLL B, but the same obfuscation mappings would need applied in calls from EXE A to DLL B.

**Comment by lextm** [comment]
https://docs.obfuscar.com/tutorials/basics.html
