### ISSUE TITLE
not able to upgrade to .net core 2.2

### ISSUE THREAD

**Issue by samdubey** [obfuscar/obfuscar#239]

**Comment by samdubey** [comment]
It does not work for .NET Core 2.2 obfuscation
it works for .net core 2.1

**Comment by samdubey** [comment]
![image](https://user-images.githubusercontent.com/4013722/67382850-caac1a00-f5ab-11e9-887e-e803ca8f9eb6.png)

**Comment by lextm** [comment]
https://github.com/obfuscar/example

You use the wrong package.
