### ISSUE TITLE
GetGenericName() creates conflicting names

### ISSUE THREAD

**Issue by frblondin** [obfuscar/obfuscar#242]
I am testing Obfuscar with a large solution containing many projects (mix of VB and C# projects, total of 1 million lines of code). I am getting an error 

The error is:
```
Obfuscar.ObfuscarException: Failed to get type definitions for WizInterfaces, Version=8.13.0.0, Culture=neutral, PublicKeyToken=bce3f989f4a9ff0b ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Obfuscar.AssemblyInfo.Graph..ctor(IEnumerable`1 items)
   at Obfuscar.AssemblyInfo.GetAllTypeDefinitions()
   --- End of inner exception stack trace ---
   at Obfuscar.AssemblyInfo.GetAllTypeDefinitions()
```

My understanding is that [this line](https://github.com/obfuscar/obfuscar/blob/93e772d02d2017de30afb1e3d333194c2c2e53fe/Obfuscar/Helpers/TypeReferenceExtensions.cs#L74) creates names that are conflicting with other names generated for types in `Obfuscar.RenameTypes`. I am not clear yet as of how to create a simple reproduction scenario. I don't know neither how setting a value for `Mono.Cecil.TypeReference.Name` impacts the values set to `Mono.Cecil.TypeDefinition.Name`. As apparently it can be conflicting, the fix seems to be to apply the smae logic defined [here](https://github.com/obfuscar/obfuscar/blob/93e772d02d2017de30afb1e3d333194c2c2e53fe/Obfuscar/Obfuscator.cs#L583) within `TypeReferenceExtensions.cs`.

If I comment out [this line](https://github.com/obfuscar/obfuscar/blob/93e772d02d2017de30afb1e3d333194c2c2e53fe/Obfuscar/Helpers/TypeReferenceExtensions.cs#L74) the error is fixed.

What do you think?

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.
