### ISSUE TITLE
Obfuscar - System.TypeLoadException while loading obfuscated DLLs through open source Obfuscar tool

### ISSUE THREAD

**Issue by talelejagdish** [obfuscar/obfuscar#246]
I have 6 DLLs in my application. When I am loading that DLLs from my test application then my test application is crashing and I can see unhanded exception in event viewer. Please note that all 6 DLLS are obfuscated through Obfuscar.

Exception Info: System.TypeLoadException at Test.CreateSampleTest()

After analyzing issue, I have created 3 non-obfuscated DLLS out of 6 and application is working fine after repplacing that non obfuscated DLLs.

However, I could't able identified which method / class having problem while loading obfuscated DLLs from event viewer trace logs. I have even tried Fusion Log Viewer but it is not helped me.

Delivering 3 non-obfuscated DLLs out of6 to customer is opening 50% source code to customer. I could not skipped those 3 DLLs. However, I could not identified which class / method should be skipped to resolve issue by going through event viewer log. I could not even provide sample code because I don't know the root cause of issue and from where it is coming.

For your information, we have ipc / .net remoting code inside that DLLs. Also we have lot of serialize classes.

Can you please help me?

     1. Identify exact problematic DLL?
     2. How to identity root cause of issue?
     3. Why obfuscar is not working in this case?

Following is my obfuscar configuration -

  ```
<Var name="InPath" value="Some Path" />
  <Var name="OutPath" value="Path" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="ReuseNames" value="false" />
  <Var name="UseUnicodeNames" value="true" />
  <Var name="HideStrings" value="false" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SkipEnums" value="true" />
  <Var name="SuppressIldasm" value="true" />
  <Var name="RegenerateDebugInfo" value="true" />
  <Var name="XmlMapping" value="true" />
```

**Comment by lextm** [comment]
It is your own responsibilities to troubleshoot,

https://docs.obfuscar.com/support/faq.html#how-to-troubleshoot-typeloadexception-during-reflection

**Comment by talelejagdish** [comment]
It would be very helpful to us if you would help us to identify root cause of this issue.

I have already done with my research and I have already gone through this link. This link is not helpful to me. It is saying that you should skip problematic type. This is not feasible solution for our production deployment.

This same source is getting obfuscated through [preemptive ](https://www.preemptive.com/products/dotfuscator/overview) solution with same configuration. Therefore, some doubts came in mind that whether I am missing some configuration and you can guide me to correct that configuration.

If you want then I can share obfuscar logs.

**Comment by lextm** [comment]
You might consider support services from LeXtudio,

https://support.lextudio.com/services/consulting.html

As far as I know, many users do use the "not feasible solution" for their production deployment, including LeXtudio Inc.

If you prefer to use a commercial tool like PReEmptive, go for it.
