### ISSUE TITLE
Does obfuscar support TargetFrameworkVersion 4.5?

### ISSUE THREAD

**Issue by tewarid** [obfuscar/obfuscar#252]
I am obfuscating a .net framework application that targets framework 4.6.1. A referenced assembly that I am also trying to obfuscate doesn't seem to get obfuscated when its TargetFrameworkVersion is set to 4.5. Change its TargetFrameworkVersion to 4.6.1 and obfuscation works as expected. Does obfuscar support TargetFrameworkVersion 4.5?

**Comment by lextm** [comment]
Can you provide a sample to reproduce this?

**Comment by tewarid** [comment]
Please see assemblies in WindowsFormsApp1/WindowsFormsApp1/bin/Debug/Obfuscator_Output directory in [WindowsFormsApp1.zip](https://github.com/obfuscar/obfuscar/files/4046857/WindowsFormsApp1.zip). I am using dotPeek to decompile.

It may not have anything to do with .NET FW version. It looks like I am seeing the behavior with debug configuration but not release.
