### ISSUE TITLE
[Question] F# .NET core support?

### ISSUE THREAD

**Issue by Naxaliav** [obfuscar/obfuscar#253]
Hello,
does **obfuscar** support ``F# .NET Core``? Cuz, I cant use it even on fresh ``F# .NET Core`` project.
Are there any plans for ``F# .NET Core`` support?

Regards,
GM

**Comment by lextm** [comment]
Obfuscar can obfuscate the F# compiler, so I won't doubt that it supports F# in all possible cases.

However, how to use it on F# projects is not what I am interested in, as I don't write much F#. You are welcome to explore that and come back with your findings.

**Comment by Naxaliav** [comment]
Resolved. For some reason FSharp.Core.dll was not being copied to bin folder, thats why I wouldnt able to obfuscate. F# obfuscation works as intended.
