### ISSUE TITLE
Appears to be Incompatible w/ .NET Core 3.1 Global Tools

### ISSUE THREAD

**Issue by thenadz** [obfuscar/obfuscar#255]
After successful global tool install, invoking obfuscar.console results in the following error when only .NET Core 3.1.1 is installed.
> It was not possible to find any compatible framework version
> The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
>   - The following frameworks were found:
>       3.1.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> 
> You can resolve the problem by installing the specified framework and/or SDK.
> 
> The specified framework can be found at:
>   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=debian.10-x64

**Comment by lextm** [comment]
Sounds like a design limitation of .NET Core Global Tools.

You should be able to install .NET Core 2.1 runtime to resolve this issue.

**Comment by thenadz** [comment]
Surely the proposed fix is not to install a separate older .NET Core runtime..? That is a viable workaround assuming that obfuscation run from Core 2.x runtime will succeed on .NET Core 3.x bytecode, but workaround != fix.
