### ISSUE TITLE
Does Obfuscar support multi project referenced themselves.

### ISSUE THREAD

**Issue by omeercoskun** [obfuscar/obfuscar#256]
My service is webapi project. This project referenced another project. Is my config true ? Should i obfuscate all these projects in the service project?
I run obfuscar with this config but my api did not work properly.
![image](https://user-images.githubusercontent.com/5605738/73433737-5f19db80-4356-11ea-9a00-a5b884f730bf.png)

I have an error in a simple get method.
![image](https://user-images.githubusercontent.com/5605738/73434109-29c1bd80-4357-11ea-8fbc-f95369fd913f.png)

**Comment by lextm** [comment]
The exception indicates that something in your code is being loaded via reflection (by name). However, your Obfuscar configuration can force a lot to be renamed.

My suggestion is that you debug and see what names must be kept, and then use skip rules to maintain them during obfuscation,

https://docs.obfuscar.com/getting-started/configuration.html#exclusion-rules-by-configuration
