### ISSUE TITLE
Obfuscating causes SW to throw null reference

### ISSUE THREAD

**Issue by MagnusH68** [obfuscar/obfuscar#261]
I have a big project which I obfuscate, but one part of the code throws a null-reference exception when obfuscated, but if I skip obfuscating everything works. 

Most parts of the project works though, and I have verified that it is obfuscated.

I use the following settings (and in/out etc which I left out)
`
  <Var name="KeepPublicApi" value="true" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="UseUnicodeNames" value="true" />
  <Var name="HideStrings" value="false" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="false" />
`

If I set HidePrivateApi to false than it works, but than nothing will get obfuscated. Any suggestions on how to fix?

**Comment by lextm** [comment]
Obfuscation might slightly change the way your app works (if you check the opened issues), so such exceptions are not unexpected.

However, without accessing your project (assemblies and maybe source code) it is impossible to debug further.

A quick suggestion is to switch to other obfuscation tools.

**Comment by MagnusH68** [comment]
I disagree: obfuscation should not change the way your app works in any way, only make it harder to reverse engineer the code. 

The source code is commercial source code so I can't share it, but its some classes and helpers that basically read and write XML according to a specified scheme.
