### ISSUE TITLE
BadImageFormatException with .net core 3.1

### ISSUE THREAD

**Issue by Jarh000** [obfuscar/obfuscar#264]
Unhandled Exception: System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.  

How to use with .net core 3.1? 
Is supported?

**Comment by lextm** [comment]
Which file did you try to obfuscate? Keep in mind some files are not managed assemblies. See posts such as https://stackoverflow.com/questions/59818364/how-to-run-ildasm-on-net-core-exe-assembly#comment107195727_59818364

**Comment by Jarh000** [comment]
> Which file did you try to obfuscate? Keep in mind some files are not managed assemblies. See posts such as https://stackoverflow.com/questions/59818364/how-to-run-ildasm-on-net-core-exe-assembly#comment107195727_59818364

Is a exe generated by a consolo application in net core 3.1, try to obfuscate get this error System.BadImageFormatException: Format of the executable (.exe)

**Comment by lextm** [comment]
That's expected. That .exe is not a managed assembly like I said. You should obfuscate the .dll files.

**Comment by Jarh000** [comment]
Hi lex Li and thank for answer, 

I stop using exe file to try to obfuscate, instead of that I create an example with a simple class library that generate dll and I am trying to obfuscate.

The code is a simple static class.

namespace Cadena
{
  public static class Help
  {
        public static string MyString= "My string";
  }
}

The tool obfuscate correctly  namespace (Cadena), class name (Help),  property name (MyString) but no obfuscate the value for "My string" that is the value that i need to be obfuscate.

In config.xml file have this parameter active
<Var name="HideStrings" value="true" />  but it doesn't work.

I hope you can guide me what i am doing bad,  what parameter do I need or something additional.

Thanks in advance. 

P.D. Your tool is amazing

**Comment by lextm** [comment]
Recorded in https://docs.obfuscar.com/support/faq#how-to-troubleshoot-badimageformatexception
