### ISSUE TITLE
conflicts between force and skip

### ISSUE THREAD

**Issue by mtnjustme** [obfuscar/obfuscar#265]
skiptype might conflict with force, and too with KeepPublicApi or HidePrivateApi causing the program to get a "Inconsistent virtual method obfuscation state detected. Abort. Please review the following methods" will rename error, the thing is, sometimes the whole program needs to be obfuscated, means HidePrivateApi = true, KeepPublicApi = false, but some specific methods need to be skipped fully, as they're serialized, therefore i think tags should be added to both the skip and the force functions, determining their priorities over others.

**Comment by lextm** [comment]
You have to give a more concrete example on what's the matter. There is no plan to add any complexity here in a simple obfuscation tool, unless it turns out to be really necessary.
