### ISSUE TITLE
different settings for different namespaces

### ISSUE THREAD

**Issue by mtnjustme** [obfuscar/obfuscar#266]
some namespaces are serialized, maybe in methods or events specifically, so their value of RenameEvents or whatever should be specifically false for them, insead of going through all the events and namespaces and methods in the skip and force for each module file.
would be cool that the basic functions would be able to be namespaces targeted (optionally)

**Comment by lextm** [comment]
Can you provide a concrete example?

**Comment by mtnjustme** [comment]
for example, one namespace is being serialized in its methods, so changing the methods names would result in an error, but its events aren't serialized, so changing them won't effect anything.
but you can't disable methods name changing only for this specific namespace without disabling for all the others too, the only way you'd be able to do that is separate the namespaces to different files and perform different obfuscating routine on each, or run it twice on the same file with a different routine in each.
it'd be useful to do it in such a way:
renameevent()
<
forcenamespace(x)
skipnamespace(x)
>

etc.
instead of doing it in modulefile, which is mostly useless if looking for a satisfying result.

**Comment by lextm** [comment]
I still cannot understand how that can be useful. By saying examples, I meant concrete examples that can be made test cases, like https://github.com/obfuscar/obfuscar/tree/master/Tests

Rules should be made every simple, as Obfuscar was designed that way. If you find needs to do complex obfuscation, then decorating the classes/methods with attributes would be a more proper option to go.

**Comment by mtnjustme** [comment]
i gave you enough information already, logically i've explained it all.
decorating the whole file is possible, i forgot to mention it when i said run it twice or separate namespaces, however, what if you'd want to make changes to your decorations easily? you'd need to go through each file and make those changes instead of having it as a single config option, knowing where you have it, and disabling/enabling it would be easy, since namespaces are dependent on one another so redecorating your whole project over and over again, you call that simple?
and it should be optional, just as they are in modules, tell me, what do those skip and force options help in the main module? its useless, its too general.
i've placed this issue to help you to make this project better, i ain't gonna give you my projects that i've used obfuscar in as i dont want to share the codes, and i ain't gonna create a new test project just for it, even a blind person would see the issue in it, if it interests you then make a test project on your own, and you probably dont even need to, since you run test builds on obfuscar everyday occasionally, so its just to test if the feature works and publish it (with a patch note in the wiki near module file to say that now it supports skip and force in rename, etc., the real desperate ones who waste a lot of time on it would find that patch note anyway).
you're right that decorating is possible, but is it the proper way to go, well, i'd prefer having anything related to obfuscar stay in the xml file, thanks for your time.
