### ISSUE TITLE
ILRepack and Obfuscar

### ISSUE THREAD

**Issue by Baltasarq** [obfuscar/obfuscar#270]
I've used Obfuscar in my project (EXE file + DLL, both C#), and it works great.
I don't like to distribute two files, so I used ILRepack, as usual, in order to create a single EXE from both files.
The problem is that ILRepack got confused with the obfuscation, complaining that type A exists in both assemblies. I tried with the /internalize option, that renames the type in the DLL, but then the produced executable fails.
What is the recommended action for this?
Does Obfuscar support repackaging in one assembly?
Thanks,
-- Baltasar

**Comment by lextm** [comment]
Merge first and then obfuscate.
