### ISSUE TITLE
Produces corrupt assembly if HideStrings=true and assembly does not contain any string literals

### ISSUE THREAD

**Issue by s-rech** [obfuscar/obfuscar#276]
Here is how to reproduce the error:
- Create a .NET project without any string literals 
- Obfuscate the output with setting HideStrings=true

**Result**: Assembly cannot be loaded, because of some weird COM-Exception.

**Reason**:
In class "Obfuscator.StringSqueeze" method "Squeeze", the field definition "DataConstantField" is set to an empty array. This leads results in an invalid assembly, because the field is not set to any data section at all.
Solution would be to completely skip creation of the hide string section in this case. As an alternative, setting the field to a dummy one byte array would also work.

**Comment by IngridtRodriguez** [comment]
Is it resolve?

**Comment by MartenF** [comment]
This problem is still present because the pull request #277 was never merged. @s-rech never signed the CLA, but it's a simple 2 line fix.
The COM-Exception is "Record not found on lookup. (Exception from HRESULT: 0x80131130)" btw for people running into the same problem and try googling.
