### ISSUE TITLE
"Format of the executable (.exe) or library (.dll) is invalid."

### ISSUE THREAD

**Issue by guaicaiboshi** [obfuscar/obfuscar#280]
win 10 x64, .netCore 3.1 Independent operation.
 I downloaded your code, upgraded Obfuscar and GlobalTools to 3.1,  and then debug the call to get an exception[ Obfuscar\AssemblyInfo.cs]: "Format of the executable (.exe) or library (.dll) is invalid."

obfuscar.xml
<?xml version="1.0" encoding="utf-8" ?>
<Obfuscator>
  <Var name="InPath" value="Input" />
  <Var name="OutPath" value="Output" />
  <Var name="ReuseNames" value="false" />
  <Var name="HideStrings" value="false" />
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="true" />

  <Module file="$(InPath)\SensorBroker.Web.Host.exe" />
</Obfuscator>

SensorBroker.Web.Host.exe is I want to confuse program, he is a. NetCore3.1 run independently generated an exe.

**Comment by lextm** [comment]
#264
