### ISSUE TITLE
Failed to resolve assembly: 'System.Private.ServiceModel, Version=4.1.2.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

### ISSUE THREAD

**Issue by guaicaiboshi** [obfuscar/obfuscar#281]
I have a .NETCore 3.1 library that is ofcuscated with obfuscar, But it failed.
D:\test\obfuscar-master\GlobalTools\bin\Release\netcoreapp3.1\publish>run.bat
Loading project obfuscar.xml...
An error occurred during processing:
Unable to find assembly:  Input\SensorBroker.Application.dll
Failed to resolve assembly: 'System.Private.ServiceModel, Version=4.1.2.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

I used DNGuard HVM Trial to encrypt this assembly without any problems.

 
  </Var name="InPath" value="Input" />
  </Var name="OutPath" value="Output" />
  </Var name="ReuseNames" value="false" />
  </Var name="HideStrings" value="false" />
  </Var name="KeepPublicApi" value="false" />
  </Var name="HidePrivateApi" value="true" />

  </Module file="$(InPath)\SensorBroker.Application.dll" />

**Comment by lextm** [comment]
Duplicate to #132
