### ISSUE TITLE
Unable to resolve dependency:  PresentationCore

### ISSUE THREAD

**Issue by itsho** [obfuscar/obfuscar#285]
Hi.

Not sure if related to #271 or not, but here goes:

When trying to obfuscate a WPF project I'm **sometimes** getting this:
```
 Loading project ..\..\obfuscar.xml...
  Processing assembly: ProjName1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  Processing assembly: ProjName2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  Processing assembly: ProjName3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  Loading assemblies...Extra framework folders: 
  An error occurred during processing:
  Unable to resolve dependency:  PresentationCore
```

Is there a way to get detailed log?

thanks.

**Comment by lextm** [comment]
If your WPF projects target .NET Core, then it is a duplicate.

**Comment by itsho** [comment]
No, I'm not targeting .NET core

**Comment by itsho** [comment]
My current conclusion that it is something to do with the environment since it's only occurring on SOME machines.

**Comment by techaimail** [comment]
We have the same problem with .NET 5 for windows XAML-WPF app.

```
1>Loading assemblies...Extra framework folders: Done.
1>Hiding strings...
1>
1>Unhandled Exception: System.NotSupportedException: This .resources file should not be read with this reader. The resource reader type is "System.Resources.Extensions.DeserializingResourceReader, System.Resources.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51".
1>   at System.Resources.ResourceReader._ReadResources()
1>   at System.Resources.ResourceReader.ReadResources()
1>   at Obfuscar.Obfuscator.GetXamlDocuments(AssemblyDefinition library)
1>   at Obfuscar.Obfuscator.RenameTypes()
1>   at Obfuscar.Obfuscator.RunRules()
1>   at Obfuscar.Program.Main(String[] args)
1>Renaming:  fields...Parameters...Properties...Events...Methods...Types...
```

**Comment by virzak** [comment]
Just add this to the xml file as a band-aid solution for now:

```xml
  <AssemblySearchPath path="C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.0" />
```

**Comment by itsho** [comment]
I've found the source of the problem.

the sln is composed of multiple csproj, and all of them were targeting .NET 4.6.1
but many of the csproj still contained reference to older .NET framework(s):
* `<RequiredTargetFramework>3.0</RequiredTargetFramework>`
* `<RequiredTargetFramework>3.5</RequiredTargetFramework>`
* `<RequiredTargetFramework>4.0</RequiredTargetFramework>`

after removing all of them, the issue is resolved.

**Comment by NonicaTeam** [comment]
> Just add this to the xml file as a band-aid solution for now:
> 
> ```
>   <AssemblySearchPath path="C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.0" />
> ```

What if the folder cannot be found in other computers when distributing? Could that impact dll loading or the setting/reference is only used for obfuscating the dll? Obfuscar documentation does not seem to be 100% clear about that...

**Comment by lextm** [comment]
@techaimail what you hit was #268, which is irrelevant.

**Comment by lextm** [comment]
@NonicaTeam Obfuscar/Mono Cecil needs to know all referenced assemblies during obfuscation. That's unfortunately a requirement of IL manipulation.

When the program is executed at runtime, the same reference must be handled differently by .NET/.NET Framework (some are just shims). That's a very complex mechanism which Obfuscar documentation won't be able to cover. It's usually transparent to developers and end users.
