### ISSUE TITLE
Incompatibility with .NET Core 3.1

### ISSUE THREAD

**Issue by stamy0** [obfuscar/obfuscar#286]
After downloading Obfuscar as a global tool with the following command:
`dotnet tool install --global Obfuscar.GlobalTool --version 2.2.26`

I have received this error:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.6 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=centos.7-x64
```

As installing .NET Core 2.1 is not a viable option for me, is there any other solution for this issue?

**Comment by lextm** [comment]
I wonder why installing .NET Core 2.1 runtime on a machine for development is not "viable". So far, so plan to change anything.

**Comment by stamy0** [comment]
Well, I guess thats a no, along with this issue #187
