### ISSUE TITLE
.Net 5.0 

### ISSUE THREAD

**Issue by FallenDev** [obfuscar/obfuscar#287]
Writing an application in C# WPF on framework .Net 5.0 Preview 7.

On compile I'm seeing:
1>Unhandled Exception: System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
1>   at Mono.Cecil.PE.ImageReader.ReadOptionalHeaders(UInt16& subsystem, UInt16& dll_characteristics)
1>   at Mono.Cecil.PE.ImageReader.ReadImage()
1>   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
1>   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
1>   at Obfuscar.AssemblyInfo.LoadAssembly(String filename)
1>   at Obfuscar.AssemblyInfo.FromXml(Project project, XElement reader, Variables vars)
1>   at Obfuscar.Project.FromXmlReadNode(XElement reader, Project project)
1>   at Obfuscar.Project.FromXml(XDocument reader, String projectFileDirectory)
1>   at Obfuscar.Obfuscator.LoadFromReader(XDocument reader, String projectFileDirectory)
1>   at Obfuscar.Obfuscator..ctor(String projfile)
1>   at Obfuscar.Program.Main(String[] args)

My question is, do you think perhaps it's just not compiling due to a newer framework? 
My obfuscar.xml is pretty basic, just an inpath, outpath two files and hideprivate/keeppublic.

**Comment by FallenDev** [comment]
Looking at past issues, looks like this may have already been decided not to proceed with fixing this issue. However, if you ever do decide to. .Net 5.0 is the new standard moving forward. Whereas Microsoft has merged .Net and .Net Core as one standard. It could offer as a learning experience for myself or others if we can spend a few weeks walking through and understanding the code. Might actually be stable for awhile if we could get it to that point.

**Comment by lextm** [comment]
Duplicate to #264 .

Too many developers like you didn't even release the .exe generated is not a managed assembly, but a native one. Obfuscar will never support such files, and you should obfuscate only managed assemblies (most of the .dll files generated by .NET Core tooling).

**Comment by FallenDev** [comment]
No, I did realize that. Your assumption is wrong. This post command was trying to pull in a .dll not an .exe. Directions were followed and it still did not like it. It's fine, I found another obfuscator that worked. Even more so now that I see the developer here attacks developers who offer suggestions.

**Comment by zlatkolakisic** [comment]
@FallenDev which obfuscator did you switch to?
