### ISSUE TITLE
Unable to resolve dependency Microsoft.AspNetCore.Mvc.Razor

### ISSUE THREAD

**Issue by accarvajal** [obfuscar/obfuscar#289]
Hi,

I have a .NET Core 2.2 class library project with few dependencies:

```
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="6.1.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="8.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.ResponseCaching" Version="2.2.0" />
    <PackageReference Include="Obfuscar" Version="2.2.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="reCAPTCHA.AspNetCore" Version="2.2.3" />
    <PackageReference Include="Telerik.Reporting.OpenXmlRendering" Version="14.1.20.618" />
    <PackageReference Include="Telerik.Reporting.Services.AspNetCore" Version="14.1.20.618" />
    <PackageReference Include="Telerik.UI.for.AspNet.Core" Version="2020.2.617" />
  </ItemGroup>
</Project>
```

The obfuscar.xml file:

```
<Obfuscator>
  <Var name="OutPath" value="bin\Debug\netcoreapp2.2" />
  <Module file="SicotX.Startup.dll" />
</Obfuscator>
```

When project compiles, it throws a dependency error:

1>Loading project D:\Proyectos\Repositorios\Enterprise\SicotX.Startup\SicotX.Startup\obfuscar.xml...Processing assembly: SicotX.Startup, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
1>Loading assemblies...Extra framework folders:
1>An error occurred during processing:
1>Unable to resolve dependency:  Microsoft.AspNetCore.Mvc.Razor

Project is referencing such assembly version and it works fine, however when I look at the nugets folder, I don't see such version.

![image](https://user-images.githubusercontent.com/20478780/90570632-befe9500-e175-11ea-9cdd-3a2c2618f105.png)

I'm not sure what could be the cause of the issue.

Thanks for any help

**Comment by lextm** [comment]
Duplicate to #132

**Comment by lextm** [comment]
I posted a comment there https://github.com/obfuscar/obfuscar/issues/132#issuecomment-371606089 Follow it to obfuscate the target assembly in the self-contained deployment folder is the simplest way to make sure all dependencies are there.
