### ISSUE TITLE
ASP.NET Core not working with a class library dependency obfuscated

### ISSUE THREAD

**Issue by accarvajal** [obfuscar/obfuscar#290]
Hi,

I have a .Net Core 2.2 class library configured to obfuscate which is used as an assembly dependency for an asp.net core 2.2 web application. I copied dll obfuscated and mapping files to the destination folder into web app, however the web app now is not working since is not recognizing methods, etc. from the obfuscated class library. I don't know what I'm doing wrong or how to do for it to work.

Thanks for any help.

**Comment by lextm** [comment]
https://docs.obfuscar.com/support/faq.html#how-to-troubleshoot-typeloadexception-during-reflection
