### ISSUE TITLE
xamarin.android run white screen after use obfuscar

### ISSUE THREAD

**Issue by jingliancui** [obfuscar/obfuscar#294]
Is this is a bug or other things?

**Comment by lextm** [comment]
https://docs.obfuscar.com/support/faq.html#how-to-troubleshoot-typeloadexception-during-reflection

If certain names are critical, then you have to leave them untouched. Well known limitation of obfuscation.

**Comment by jingliancui** [comment]
Awesome! You are right! Some class must be untouched.

**Comment by jingliancui** [comment]
@lextm  Sorry for reopen this issue, after config some classes "not to obfuscate".
App run normally when in release mode using vs' "start without debugging" .
Then going to archive it to apk file.
It run with write screen and logcat print this like "...  has died: fore top "
Then I set this config to .csproj file `<AndroidEnableAssemblyCompression>false</AndroidEnableAssemblyCompression>` and redo the achive apk operation.
App run normally finally.
Is it something need to update about this https://github.com/xamarin/xamarin-android/pull/4686
