### ISSUE TITLE
Linux Build Systems  - executable for *nix 

### ISSUE THREAD

**Issue by TWhidden** [obfuscar/obfuscar#295]
Our CI process sits on a GitLab runner under Linux.   This tool has a target for windows, but would be nice to have a linux ready executable also included in the nuget package.  Do you think there will be support for this in the future?

![image](https://user-images.githubusercontent.com/9921122/92983421-20a1de80-f458-11ea-9726-86bacdfcae37.png)

**Comment by lextm** [comment]
There is a .NET Core global tool version, but it has several known issues,

https://docs.obfuscar.com/getting-started/basics.html#net-core-global-tools

**Comment by DeafMan1983** [comment]
issues?

I have tested Obfuscar under Ubuntu 18.04 and I don't have any issues.?..

**Comment by lextm** [comment]
@DeafMan1983 You can find relevant discussions from https://github.com/obfuscar/obfuscar/issues?q=is%3Aissue+global
