### ISSUE TITLE
WPF - ViewModel Command not firing

### ISSUE THREAD

**Issue by Jacquers** [obfuscar/obfuscar#297]
I'm using the ViewModel pattern in WPF and once obfuscated the commands don't work anymore. With ILSPY I can see it's due to the command name in xaml not matching the renamed command in the viewmodel anymore.

Basic example attached.

Options used:

KeepPublicApi" value="false"
HidePrivateApi" value="true"
RenameProperties" value="true"
RenameEvents" value="true"
RenameFields" value="true"
UseUnicodeNames" value="true"
HideStrings" value="true"
OptimizeMethods" value="false"
SuppressIldasm" value="true"

[WPFViewModelTest.zip](https://github.com/obfuscar/obfuscar/files/5251508/WPFViewModelTest.zip)

**Comment by lextm** [comment]
https://docs.obfuscar.com/support/faq.html#how-to-troubleshoot-typeloadexception-during-reflection

**Comment by Jacquers** [comment]
I didn't get a type load exception. I assume Obfuscar doesn't support WPF / Xaml properly?

**Comment by lextm** [comment]
WPF and XAML eat up those exceptions, but the root cause is exactly the same. You cannot obfuscate certain class/method names, as reflection is broken by new names.

**Comment by Jacquers** [comment]
Is it not possible to fix it so the command binding get's renamed in the xaml / baml? Normal button clicks seem to work fine after obfuscation.

**Comment by lextm** [comment]
Since it requires significant efforts, this obfuscator does not attempt to modify BAML, so it won't fix any binding for you. You can feel free to switch to other obfuscators that do so.

**Comment by Jacquers** [comment]
Found that this one works: https://github.com/mkaring/ConfuserEx

Maybe a combined effort on one project instead of two different ones could work? :)
