### ISSUE TITLE
PublishSingleFile setup

### ISSUE THREAD

**Issue by lastlink** [obfuscar/obfuscar#301]
* I'm having difficulties getting obfuscar working with dotnet core and publish singlefile. Ideally I'd like to obfuscate the main dll for my project before it is embedded into the dotnet core PublishSingleFile single .exe. I installed the obfuscate global tool then use a different obfuscate.xml for each runtime and publish PublishSingleFile using a custom variable rId to triggler different commands in the post build. when I set the output for obfuscar the same as the input I get an error. Maybe this is due to trying to override the same file obfuscar is using and I shoudl use a copy command after to update the original dll.

` Unhandled Exception: System.IO.IOException: The process cannot access the file 'xxx\bin\Release\netcoreapp3.1\linux-arm\main.dll' because it is being used by another process.`

Here's my work so far.

* setup
`dotnet tool install Obfuscar.GlobalTool --tool-path tools --version 2.2.18`

**.csproj** post build 
```xml
<PropertyGroup>
    <rId Condition="$(rId) == ''">win-x64</rId>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="$(ConfigurationName) == Release">
    <Exec Command="if '$(rId)' == 'win-x64' ..\tools\obfuscar.console ..\obfuscar-win-x64.xml&#xD;&#xA;if '$(rId)' == 'linux-arm' ..\tools\obfuscar.console ..\obfuscar-linux-arm.xml" />
  </Target>
```

obfuscar example file **obfuscar-win-x64**
```xml
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value=".\bin\Release\netcoreapp3.1\win-x64" />
  <!-- <Var name="OutPath" value="$(InPath)" /> -->
  <Var name="OutPath" value="$(InPath)\ReadyForDeployment" />
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="UseUnicodeNames" value="true" />
  <Var name="HideStrings" value="true" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="true" />
  <Module file="$(InPath)\main.dll" />
</Obfuscator>
```

* publish cmds
```sh
dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true
dotnet publish -c Release -r linux-arm -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true /p:rId=linux-arm 
```

**Comment by lastlink** [comment]
ok if I add this step to the post build it seems to be there.

`copy "$(TargetDir)ReadyForDeployment\main.dll" "$(TargetDir)main.dll" /y`

this seems to run before optimizing assemblies, but when I run the published single .exe and check in the temp folder, the main.dll is not obfuscated. maybe I should use the pre-build event....
* e.g. c:\Users\{Local Username}\AppData\local\temp\.net\{Name of executable} from https://docs.microsoft.com/en-us/visualstudio/ide/reference/pre-build-event-post-build-event-command-line-dialog-box?view=vs-2019

**Comment by lastlink** [comment]
Figured out, for the main app you have to delete and obfuscate the output to the obj\Release folder. For imported local projects, you need to obfuscate their bin\release dll that's used in the single .exe

**Comment by lextm** [comment]
Thanks for sharing the solution.

**Comment by GF-Huang** [comment]
@lastlink Thanks for sharing the solution! But does it also works for .net 5 single file exe? Because there's some differences between .net core 3.x and .net 5. 

> Bundling all application-dependent files into a single binary provides an application developer with the attractive option to deploy and distribute the application as a single file. This deployment model has been available since .NET Core 3.0 and has been enhanced in .NET 5.0. Previously in .NET Core 3.0, when a user runs your single-file app, .NET Core host first extracts all files to a temporary directory before running the application. .**NET 5.0 improves this experience by directly running the code without the need to extract the files from the app.**

references: https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file

**Comment by lastlink** [comment]
@GF-Huang 
Really it just has to be tested, obfuscating the files, then examining the bundled dlls. It almost seems more difficult to determine now a successful obfuscation if they aren't extracting a location, may be similar to a zip where it runs the files directly in the zip. I suspect the behavior is still the same, I've had a issue in the dotnet sdk for a while https://github.com/dotnet/sdk/issues/14327.

To test in dotnet 5 you'd have to copy the dlls from the single exe and examine their contents. I haven't experimented with it yet.

**Comment by GF-Huang** [comment]
I found that latest [ILSpy](https://github.com/icsharpcode/ILSpy/releases/tag/v7.0-preview2) supports to decompile .net 5 single file exe. I think this should be help to check is it obfuscating successful.

**Comment by haftsad** [comment]
Just use it after target Compile in obj folder and replace obfuscated file.

**Comment by GF-Huang** [comment]
@lastlink Could you provide a complete example?

**Comment by lastlink** [comment]
My example I've posted I've only tested in .net 3. So if you're using 5 you'll have to do your own testing.

**Comment by GF-Huang** [comment]
> Figured out, for the main app you have to delete and obfuscate the output to the obj\Release folder. For imported local projects, you need to obfuscate their bin\release dll that's used in the single .exe

What the mean of **"you have to delete and obfuscate the output to the obj\Release folder"**?

**Comment by guidomocha** [comment]
readers can refer to https://github.com/obfuscar/obfuscar/issues/314 for the solution.
