### ISSUE TITLE
How to skip mixed-mode assemblies in this case?

### ISSUE THREAD

**Issue by rafak360** [obfuscar/obfuscar#302]
I'm getting a `System.NotSupportedException: Writing mixed-mode assemblies is not supported` regarding this exception, at the obfuscar FAQ it says:

> Usually such exceptions happen when mixed-mode assemblies (from C++/CLI) are being obfuscated. Mono Cecil does not support such. Please skip them.

I made a simple C++ CLR Windows Forms .NET Framework 4.5 for obfuscar testing purposes which there's only 1 Form with a namespace named ObfuscarTest.

I took a look at: https://docs.obfuscar.com/getting-started/configuration.html
but I'm not sure how to properly skip mixed-mode assemblies. I assume System, Microsoft and my ObfuscarTest namespaces are suppose to be mixed-mode assemblies, so I set them up on my obfuscar.xml file:

```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value="Directory omitted." />
  <Var name="OutPath" value=".\Obfuscator_Output" />
  <Module file="$(InPath)\ObfuscarTest.exe" >
    <SkipNamespace name="System*" />
    <SkipNamespace name="Microsoft*" />
    <SkipNamespace name="ObfuscarTest" />
  </Module>
</Obfuscator>
```

I still get the exception though, how to skip mixed-mode assemblies?

**Comment by chenjing1294** [comment]
The same error occurs when I post in the following way, confusing one of the dll files:
`dotnet publish -c Release --runtime win-x64 -p:PublishReadyToRun=true --self-contained true`

**Comment by lextm** [comment]
No bandwidth to work on this. Mono Cecil needs to be improved first to skip such references.

**Comment by DanteMarshal** [comment]
> <SkipNamespace name="Microsoft*" />

I have the same problem, What's the reason behind that ?

**Comment by rafak360** [comment]
@DanteMarshal I had to use a better one: https://github.com/mkaring/ConfuserEx that solved the issue.
