### ISSUE TITLE
Fails on .net 5 single file

### ISSUE THREAD

**Issue by jjxtra** [obfuscar/obfuscar#303]
When attempting to obfuscate a .net 5 exe built with single file turned on and native assemblies embedded, obfuscation fails with error: `Unhandled exception. System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid`

**Comment by lextm** [comment]
Because that "single file" is not a .NET assembly, but a package of stuffs.

**Comment by jjxtra** [comment]
Thanks for the response. It would be nice to know if there is a way to hook into obfuscar sooner in the pipeline so it can obfuscate the assemblies before they are packaged into the exe. Maybe msbuild or some hook is possible?

**Comment by xiaoyuvax** [comment]
i found out that the process can proceed after removing the linux executable entry file from the xml config of Obfuscar, the rest dlls can be normally obfuscated. 
but i have no idea whether these obfuscated files,which overwrote the original through post-buid event command would have been packaged into the output single bundle file. 
can someone give a way to verify it?

**Comment by lextm** [comment]
@xiaoyuvax That's exactly #264
