### ISSUE TITLE
Hidestrings not working on .Net 5

### ISSUE THREAD

**Issue by peerem** [obfuscar/obfuscar#304]
HideStrings does not working with .Net 5, all strings are visible in ILSpy. If we switch back to netstandard2.1 all works fine.

**Comment by lextm** [comment]
Related to #318

**Comment by zziger** [comment]
Any news on this?

**Comment by Mitkari** [comment]
I have tested and this works for ASP.NET Core 5.0
Add the following lines AssemblySearchPath where dotnet version is 5 or above.(e.g 5.0.16, 5.0.17 etc)
<AssemblySearchPath path="C:\Program Files\dotnet\shared\microsoft.netcore.app\5.0.17" />
  <AssemblySearchPath path="C:\Program Files\dotnet\shared\microsoft.aspnetcore.app\5.0.17" />
in obfuscar_config.xml.
e.g.

<Obfuscator>
  <Var name="InPath" value=".\bin\Release\net5.0" />
  <Var name="OutPath" value=".\bin\obfuscated" />
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="HideStrings" value="true" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameFields" value="true" /> 
  <AssemblySearchPath path="C:\Program Files\dotnet\shared\microsoft.netcore.app\5.0.17" />
  <AssemblySearchPath path="C:\Program Files\dotnet\shared\microsoft.aspnetcore.app\5.0.17" />
  <Module file="$(InPath)\abc.dll" />
 </Obfuscator>
