### ISSUE TITLE
Obfuscar doesn't work with .net 5?

### ISSUE THREAD

**Issue by xiaoyuvax** [obfuscar/obfuscar#307]
Following stach trace shown when compile my project with .net5:

 System.BadImageFormatException: executable(.exe)or library(.dll) format invalid.
1>   at Mono.Cecil.PE.ImageReader.ReadOptionalHeaders(UInt16& subsystem, UInt16& dll_characteristics)
1>   at Mono.Cecil.PE.ImageReader.ReadImage()
1>   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
1>   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
1>   at Obfuscar.AssemblyInfo.LoadAssembly(String filename)
1>   at Obfuscar.AssemblyInfo.FromXml(Project project, XElement reader, Variables vars)
1>   at Obfuscar.Project.FromXmlReadNode(XElement reader, Project project)
1>   at Obfuscar.Project.FromXml(XDocument reader, String projectFileDirectory)
1>   at Obfuscar.Obfuscator.LoadFromReader(XDocument reader, String projectFileDirectory)
1>   at Obfuscar.Obfuscator..ctor(String projfile)
1>   at Obfuscar.Program.Main(String[] args)

**Comment by lextm** [comment]
You hit either #264 or #303.
