### ISSUE TITLE
Obfuscar 2.2.29 breaks Linq Query 

### ISSUE THREAD

**Issue by SWH-WGross** [obfuscar/obfuscar#310]
Doing a Linq query which refers to an internal property of a breaks because the property used in teh query doen exist anymore.

Example repo: https://github.com/SWH-WGross/ObfuscarProblem.git

If the program isn't obfscated it runs until it throws the NotImplemtedException. If obfuscated The LINQ query complains of a missing property. 

Unbehandelte Ausnahme: System.ArgumentException: Die MyClass.A-Methode ist kein Eigenschaftenaccessor.
   bei System.Linq.Expressions.Expression.GetProperty(MethodInfo mi)
   bei System.Linq.Expressions.Expression.Property(Expression expression, MethodInfo propertyAccessor)
   bei Program.Main()

The reason seems to be that the obfuscation replaces the property with a field and a method to read the value but LINQ searches for a property. 

Making the property public of Excluding from Obfuscation helps. 

Is this an expected behavior?
Is there a config parameter to change the specific way how properties obfuscation is done?

**Comment by lextm** [comment]
It is too difficult for the renaming algorithm to locate all references of a name (in this case a name referred in LINQ expressions), so like you discovered the only workaround is to exclude the name from being renamed.

**Comment by guidomocha** [comment]
I have same issue. In my project there is a lot of linq query and it is not possible to exclude one by one. is there any solution to exclude properties that is used within expressions?

**Comment by guidomocha** [comment]
finally is disabled `RenameProperties` option.

**Comment by coader** [comment]
I  use public property name, but obfuscar rewrite linq query and use it's generated private name
![image](https://user-images.githubusercontent.com/3700498/157359787-b69796a0-7f5a-4195-b385-c6745ebc5d9f.png)
![image](https://user-images.githubusercontent.com/3700498/157359834-131fc1d6-725e-47cb-899c-28d3abf771ff.png)
![image](https://user-images.githubusercontent.com/3700498/157359850-62759e86-9134-4aec-8933-be58d583bf51.png)
![image](https://user-images.githubusercontent.com/3700498/157359873-dc8138a3-64d9-4380-b451-7bedc3ea25be.png)

now i got this error:
ail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentException: The method 'A.a`2[System.Int64,System.String].A' is not a property accessor (Parameter 'members[0]')
         at System.Linq.Expressions.Expression.GetProperty(MethodInfo mi, String paramName, Int32 index)
         at System.Linq.Expressions.Expression.ValidateAnonymousTypeMember(MemberInfo& member, Type& memberType, String paramName, Int32 index)
         at System.Linq.Expressions.Expression.ValidateNewArgs(ConstructorInfo constructor, ReadOnlyCollection`1& arguments, ReadOnlyCollection`1& members)
         at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments, IEnumerable`1 members)
         at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments, MemberInfo[] members)

**Comment by coader** [comment]
it seems new {e.TemplateId,...} is anonymouse type, and can't call constructor after rewrite

**Comment by lextm** [comment]
Related to #130.

**Comment by coader** [comment]
> It is too difficult for the renaming algorithm to locate all references of a name (in this case a name referred in LINQ expressions), so like you discovered the only workaround is to exclude the name from being renamed.

if not change property to method, this problem should be resolved

![Image](https://github.com/user-attachments/assets/8d7c654b-77eb-4403-944b-6332d512ef81)

it's internal bool property, but now change to method, but linq still use propertyaccessor to visit it,

**Comment by lextm** [comment]
@coader Then you might give the 2.2.41 release a try by setting `RenameProperties` to `true` and `KeepProperties` to `true`.
