### ISSUE TITLE
Is it supports .NET 5 single file exe?

### ISSUE THREAD

**Issue by GF-Huang** [obfuscar/obfuscar#314]

**Comment by angrywasp** [comment]
Yes

**Comment by lextm** [comment]
Duplicate to #301

**Comment by GF-Huang** [comment]
Why not add a doc to describe about single file publish?

**Comment by lextm** [comment]
Pull requests are welcome.

**Comment by GF-Huang** [comment]
But I am still trying and never succeeded.

**Comment by random-internet-guy** [comment]
Build, obfuscate then publish to single exe with the —no-build option. Done

**Comment by GF-Huang** [comment]
> Build, obfuscate then publish to single exe with the —no-build option. Done

How to do in VS IDE without command line?

**Comment by random-internet-guy** [comment]
That’s up to you to figure out. Or use the command line

**Comment by random-internet-guy** [comment]
> # After some research, a solution was found.
> `Project\Properties\PublishProfiles\FolderProfile.pubxml`:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
>   <PropertyGroup>
>     <Configuration>Release</Configuration>
>     <Platform>Any CPU</Platform>
>     <PublishDir>..\publish\</PublishDir> 
>     <PublishProtocol>FileSystem</PublishProtocol>
>     <TargetFramework>net5.0-windows</TargetFramework>
>     <RuntimeIdentifier>win-x64</RuntimeIdentifier>
>     <SelfContained>false</SelfContained>
>     <PublishSingleFile>True</PublishSingleFile>
>     <PublishReadyToRun>False</PublishReadyToRun>
>   </PropertyGroup>
> </Project>
> ```
> 
> `obfuscar.xml`:
> 
> ```
> <?xml version="1.0" encoding="utf-8" ?>
> <Obfuscator>
>   <Var name="InPath" value=".\obj\Release\net5.0-windows\win-x64" />
>   <Var name="OutPath" value=".\obj\Release\net5.0-windows\win-x64\Obfuscated" />
>   
>   
>   <AssemblySearchPath path="C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.7" />
>   
>   <AssemblySearchPath path=".\bin\Release\net5.0-windows" />
> 
>   <Module file="$(InPath)\YourProjectOutput.dll" />
> </Obfuscator>
> ```
> 
> `Project.csproj`:
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk">
>   ...
> 
>   
>   <Target Name="Obfuscation" AfterTargets="AfterCompile" Condition="'$(PublishProtocol)'!=''">
>     <Message Text="Obfuscating" Importance="high" />    
>     <Exec Command="obfuscar.console.exe obfuscar.xml" />
>     <Exec Command="COPY $(ProjectDir)$(IntermediateOutputPath)Obfuscated\$(TargetFileName) $(ProjectDir)$(IntermediateOutputPath)$(TargetFileName)" />
>   </Target>
> </Project>
> ```
> 
> ### Done, Publish and enjoy.

Did you actually try this or run a decompiler over the resulting binary? Because I may be wrong, but I believe this will just obfuscate the main project assembly and not any referenced assemblies

**Comment by GF-Huang** [comment]
Yes, I only need obfuscate the main project.

**Comment by xiaoyuvax** [comment]
Can be solved by obfuscate each dependent project one by one with this same solution.
