### ISSUE TITLE
Removing DebuggerDisplay when obfuscating?

### ISSUE THREAD

**Issue by himpactz** [obfuscar/obfuscar#317]
I just realize that the DebuggerDisplay directive is still available in the obfuscated file. Is there a way to remove it? 

DebuggerDisplay often contains detail on the class. For example, the original property name still exists in the formatted string. 

`[DebuggerDisplay("DBTable({Name}, {TableType}, Cols={Columns.Count}, Rows={Rows.Count})")]`

**Comment by lextm** [comment]
It is not a feature that can be easily supported as you might want to leave this attribute on certain elements while removing it on others, which requires a very complex configuration system.

You'd better develop your own post-processing tool using Mono Cecil to perform the actual cleanup for your own assemblies (and probably share it with others on GitHub).

**Comment by TonyValenti** [comment]
@himpactz - Here's an alternative solution you might consider:
```
[DebuggerDisplay("{GetDebuggerDisplay(),nq}")]
public class DisplayClass { //All class inherit from this.

public string GetDebuggerDisplay(){
  var ret = "OBFUSCATED";
#if DEBUG
  ret = GetDebuggerDisplayInternal();
#endif

 return ret;
}

protected virtual string GetDebuggerDisplayInternal(){
  return "Override This for a Good display";
}

}

```

Create a base class called ```DisplayClass``` with a ```string GetDebuggerDisplay()``` method.  Decorate

**Comment by himpactz** [comment]
@TonyValenti - I drop the ball on this and forgot to thank you. 

Your approach works! I recently, I've found that you can put the #if DEBUG directive around the [DebuggerDisplay()] to make it not available during release.

Thanks!
