### ISSUE TITLE
HideStrings does not work in .Net core 3.1 App

### ISSUE THREAD

**Issue by Cuse499** [obfuscar/obfuscar#318]
HideStrings is not working using obfuscar 2.2.29 on any of my netcore31 wpf apps. Digging into the source I see the "encoding" variable fails to resolve System.Text.Encoding and stays null, as mentioned in #173:

> var encoding = new TypeReference("System.Text", "Encoding", library.MainModule,
> library.MainModule.TypeSystem.CoreLibrary).Resolve();
> if (encoding == null)
> {
> _disabled = true;
> return;
> }

The good news is I may have found a fix. I pulled down the code base and targeted all projects to just use netcore31 including obfuscar.console. Then running obfuscar.console against my netcore31 wpf apps worked as expected, the encoding variable resolves fine, and HideStrings actually works. It appears that the type resolving issue is targeting related.

**Comment by lextm** [comment]
Related to #157 .

The resolution of `System.Text.Encoding` is necessary for string hiding, but it cannot be easily implemented when .NET Core/Standard projects are being obfuscated.

Your workaround probably allows `System.Text` assembly to be linked so that the resolution starts to work. This should work for some application types (WPF) but might not for others.

**Comment by alberk8** [comment]
I have tested and this works for ASP.NET Core 5.0 add the following lines `AssemblySearchPath`  where 5.0.19 is the dotnet version.

```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value=".\bin\release\net5.0" />
 
  <Var name="OutPath" value="obj\release\net5.0\x64" />
  <Var name="HidePrivateApi" value="true" />

  <Var name="HideStrings" value="true" />
  <Var name="UseUnicodeNames" value="false" />

  <AssemblySearchPath path="c:\progra~1\dotnet\shared\microsoft.netcore.app\5.0.15" />
  <AssemblySearchPath path="c:\progra~1\dotnet\shared\microsoft.aspnetcore.app\5.0.15" />
  <Module file="$(InPath)\WebApp.dll" />
</Obfuscator>
```

**Comment by lextm** [comment]
To summarize, Obfuscar needs to explicit locate the core assemblies and then enables string hidding.

For different .NET Core versions (3.1->8.0) you need to point to different folders.

If the project targets .NET 5, then the following snippet might help
``` xml
<AssemblySearchPath path="C:\Program Files\dotnet\shared\microsoft.netcore.app\5.0.17" />
<AssemblySearchPath path="C:\Program Files\dotnet\shared\microsoft.aspnetcore.app\5.0.17" />
```

You can figure out the right paths for other .NET Core versions.

**Comment by lextm** [comment]
Related to #553
