### ISSUE TITLE
Service does not start after simple obfuscation

### ISSUE THREAD

**Issue by amoltarte** [obfuscar/obfuscar#320]
Hi!
I have a Windows Service built in Visual Studio 2019, .Net Framework 4.7.2, Windows 10 x64
It runs properly without obfuscation.
But after obfuscation, it does not start.
![Clipboard01](https://user-images.githubusercontent.com/8025714/108199191-a4b46c80-7142-11eb-89f9-bb4762231448.jpg)

I am using very simple configuration...

`<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value=".\input" />
  <Var name="OutPath" value=".\output" />
  <Module file="$(InPath)\FileName.exe" />
</Obfuscator>`

What could be wrong? Please help.

**Comment by lextm** [comment]
https://docs.obfuscar.com/support/faq.html#how-to-troubleshoot-typeloadexception-during-reflection
