### ISSUE TITLE
UWP support?

### ISSUE THREAD

**Issue by jtorjo** [obfuscar/obfuscar#321]
Hi guys,

1. Is the UWP platform supported? 
2. If so, how easy is it to obfuscate a big project?

I have a rather large project (200K LOC) that I would like to obfuscate.  

From some of the questions here, it seems you may be supporting UWP, somewhat.

**Comment by lextm** [comment]
UWP apps distributed via the store does not require obfuscation in general.

**Comment by jtorjo** [comment]
I know, but I don't distribute via the store.

**Comment by lextm** [comment]
There are quite a few issues on UWP/WPF apps,

https://github.com/obfuscar/obfuscar/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%3AWPF%2FUWP

But currently on plan to improve in those areas.

**Comment by jtorjo** [comment]
@lextm Thank you! I've already looked into a paid solution.
