### ISSUE TITLE
Add a switch to disable XAML related code and suppress relevant exceptions

### ISSUE THREAD

**Issue by lextm** [obfuscar/obfuscar#324]
.NET Core seems to introduce many more exceptions related to resources files, so the current code does not work well.

The plan is to add a switch to disable all XAML related code (anyway the XAML support so far is broken and limited).

**Comment by lextm** [comment]
Related items are, #308 #208

**Comment by lextm** [comment]
The new setting is `AnalyzeXaml`.

**Comment by lextm** [comment]
@softlion Already in https://docs.obfuscar.com/getting-started/configuration.html

**Comment by softlion** [comment]
It works correctly but seems to forget to obfuscate a good bunch of internal classes. I will check that today more in-depth to understand why.
