### ISSUE TITLE
ObfuscateAssemblyAttribute is not supported

### ISSUE THREAD

**Issue by lextm** [obfuscar/obfuscar#326]
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.obfuscateassemblyattribute?view=net-5.0

This attribute might be useful.

**Comment by GilesDMiddleton** [comment]
Shouldn't ObfuscateAssemblyAttribute override MarkedOnly, and allow for exclusions to be specified?

i.e.
Use case:

- My XML file specifies assembly A, B and C.
- I want the 99% of A obfuscated, but only 10% of B and C.
- So I set MarkedOnly=true in my XML file 
- I use attributes for each class/member I want to obfuscate in Assembly B and C.
- I add the ObfuscateAssemblyAttribute to assembly A.
- I exclude only a few classes from assembly A

Thus I expect automatic obfuscation of most of Assembly A, except where exlcude=true has been used.
And then I expect only specific classes/methods in B & C where excllude=false has been used.

Or have I misunderstood the fundamental processing?

**Comment by lextm** [comment]
It's currently an uncharted territory right now.

**Comment by lextm** [comment]
Initial support was shipped in release [2.2.31](https://github.com/obfuscar/obfuscar/releases/tag/2.2.31). Currently no plan to move on to more complicated scenarios.
