### ISSUE TITLE
How to skip types inherit from specified type or implement specified interface?

### ISSUE THREAD

**Issue by GF-Huang** [obfuscar/obfuscar#330]
I want to skip all class which implement `INotifyPropertyChanged`.

**Comment by lextm** [comment]
You might use the forked version from 3shape, which automatically skips all such types,

https://github.com/3shape/obfuscar

But that feature isn't yet considered in this repo.

**Comment by teremyx** [comment]
> 
> 
> You might use the forked version from 3shape, which automatically skips all such types,
> 
> https://github.com/3shape/obfuscar
> 
> But that feature isn't yet considered in this repo.

Does the typeinherits-Feature also consider Interfaces?
Sadly it is not documented, although one could easily test it or look at the source code.
