### ISSUE TITLE
Is it supports .net5?

### ISSUE THREAD

**Issue by GeorgeAlexandria** [obfuscar/obfuscar#332]
Hello, I'm try to use obfuscar 2.2.30 to obfuscate the couple of .net5 projects. Unfortunately, I received `System.InvalidOperationException: Need valid file attribute` on compiled assemblies.

Here you can find a simple project to repo [ConsoleApp1.zip](https://github.com/obfuscar/obfuscar/files/6769624/ConsoleApp1.zip) and bellow you may look at the exception with stacktrace:

```
...\repos\ConsoleApp1> & '.\Obfuscar.Console.exe' '.\test.xml'
Note that Rollbar API is enabled by default to collect crashes. If you want to opt out, please run with -s switch
Loading project .\test.xml...
Unhandled Exception: System.InvalidOperationException: Need valid file attribute.
   at Obfuscar.AssemblyInfo.FromXml(Project project, XElement reader, Variables vars)
   at Obfuscar.Project.FromXmlReadNode(XElement reader, Project project)
   at Obfuscar.Project.FromXml(XDocument reader, String projectFileDirectory)
   at Obfuscar.Obfuscator.LoadFromReader(XDocument reader, String projectFileDirectory)
   at Obfuscar.Obfuscator..ctor(String projfile)
   at Obfuscar.Program.Main(String[] args)
``` 

If I miss something, please let me know about it.

**Comment by lextm** [comment]
The exception indicates invalid configuration file. You can learn the configuration from https://docs.obfuscar.com/getting-started/configuration.html

**Comment by GeorgeAlexandria** [comment]
@lextm, I'm sure, that the configuration file is correct, because when I remove `<Module path="$(InPath)\ConsoleApp1.dll" />` from it, obfuscation done as well (obfuscate nothing of course, but anyway). So the issue isn't in the config file.

**Comment by lextm** [comment]
`<Module path="$(InPath)\ConsoleApp1.dll" />` is exactly an invalid tag. Can you read the documentation page once again? The correct syntax is demonstrated.

**Comment by GeorgeAlexandria** [comment]
My bad! I took `path` for `Module` as similar for `AssemblySearchPath`. I'm sorry and thanks for your helping.
