### ISSUE TITLE
PresentationFramework, Version=5.0.0.0

### ISSUE THREAD

**Issue by jcbeppler** [obfuscar/obfuscar#336]
Hello,

I was trying to use the software in a .NET Core 3.1 (WPF), but I get the following issue which is probably related to 2 libraries I am using:
> 1>Unable to find assembly:  D:\SVN\sia\xxx\bin\Release\net5.0-windows\MyApp.dll
> 1>Failed to resolve assembly: 'PresentationFramework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

Probably this is due to some nuget libraries referencing PresentationFramework, Version=5.0.0.0 (.NET 5).

Do you have any tip on how could I fix this?

**Comment by gijunhan** [comment]
```
<AssemblySearchPath path="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\5.0.0\ref\net5.0\"/>
```
In my case, after adding the above settings, it works fine.

**Comment by meesoft** [comment]
Same problem with WPF app targeting .net6.0-windows - it fails with
`  Failed to resolve assembly: 'PresentationFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'`
but setting
`<AssemblySearchPath path="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.0\ref\net6.0\"/>`
doesn't solve it

**Comment by lextm** [comment]
Related to #553.
