### ISSUE TITLE
SuppressIldasm Doesn't Appear To Be Working

### ISSUE THREAD

**Issue by protegesolutions** [obfuscar/obfuscar#344]
I upgraded from 2.2.14 to 2.2.31 today and am finding that - as useless as it is supposed to be - _SuppressIldasm_ isn't being honoured in config.

If I add the attribute directly to my assembly file, I get the expected message when trying to open the resultant dll in IL DASM.

If I ad the config line "<Var name="SuppressIldasm" value="true" />" ILL DASM open the dll no problems.

I tested by downgrading to 2.2.16 and it worked as-advertised.

I checked the doco and could see no mention of it being deprecated.

**Comment by protegesolutions** [comment]
Still not working - tho seemingly not deprecated - in 2.2.33. I understand that it's pretty useless but please either deprecate it or honour the directive. Otherwise it's just junk code.

**Comment by protegesolutions** [comment]
Can someone please comment on this? Is this working for anyone else? I know the feature isn't robust but it is useful for anyone casually wanting to look at your assembly. I'm sticking with 2.2.28 until I hear something. Thanks.

**Comment by lextm** [comment]
This feature is not available in many cases because .NET Core/.NET Standard assemblies do not allow this attribute to be inserted easily via Mono Cecil.

Since it is a useless feature, no more effort is going to be put on it.
