### ISSUE TITLE
.NET 6 framework target support

### ISSUE THREAD

**Issue by fabriciomurta** [obfuscar/obfuscar#347]
This may not really add anything technical-wise, but it would at least allow obfuscar commandline tool to be run on GitHub CI without the need to install .NET 5 when testing .NET 6 application that is obfuscated by it.

This is particularly true for CI running on linux and macos, where we need to install the Obfuscar.GlobalTool in order to use it.

**Comment by lextm** [comment]
2.2.32 release is now out with the fix.
