### ISSUE TITLE
 I can't generate an obfuscated .exe on 64-bit architecture

### ISSUE THREAD

**Issue by joe-mut** [obfuscar/obfuscar#348]
I was wondering if there is a setting for the generated .exe to run with 64 bit architecture. In the visual studio I select any cpu and this would have to generate an .exe that can be executed in 64 bits.

**Comment by joe-mut** [comment]
To be more exactly, after ofuscate the .exe, the ofuscation make that the .exe preffer 32 bits. If i force in visual studio to make only the .exe in 64 bits this works.

**Comment by GilesDMiddleton** [comment]
@joe-mut I can't see anything in the code that's purposefully doing this, but have you tried using corflags to see if the setting can be removed post obfuscation? [corflags](https://docs.microsoft.com/en-us/dotnet/framework/tools/corflags-exe-corflags-conversion-tool).

It looks like you might be able to detect what's happening by debugging obfuscar in obfuscator.cs `SaveAssemblies` and looking at `ModuleAttributes.Preferred32Bit`, 

e.g.
`info.Definition.MainModule.Attributes.HasFlag(ModuleAttributes.Preferred32Bit)`

But maybe there's a bug in Cecil like [this one](https://github.com/jbevain/cecil/issues/753).

**Comment by joe-mut** [comment]
thanks for the reply, it was our mistake, a bad enviroment configuration.
