### ISSUE TITLE
Should upgrate to newer version of .NET Framework

### ISSUE THREAD

**Issue by donhuvy** [obfuscar/obfuscar#350]
![image](https://user-images.githubusercontent.com/1328316/142656514-20842685-f4ec-4aae-bc95-74794f9859e2.png)

**Comment by lextm** [comment]
VS starts to prompt latest .NET Framework release but that does not mean you should upgrade any project.

Obfuscar might upgrade when .NET Framework 4.6.2 becomes the new minimal in a few months, but not now.
