### ISSUE TITLE
.net 6 Error

### ISSUE THREAD

**Issue by pulmuone** [obfuscar/obfuscar#353]
Visual Studio 2022 
Obfuscar Version : 2.2.32

Error Message :
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "C:\Users\gwise\.nuget\packages\obfuscar\2.2.32\build\..\tools\Obfuscar.Console.exe obfuscar.xml" exited with code 1.	WinFormsApp3	C:\Users\gwise\source\repos\WinFormsApp3\WinFormsApp3\WinFormsApp3.csproj	31

**Comment by lextm** [comment]
You can help yourself by running the command at a command prompt. That does not only reproduce the exit code 1 but also tells you what exactly the error is.

The console app exits with 1 in several locations, https://github.com/obfuscar/obfuscar/blob/master/Console/Program.cs and in your case, the most likely reason is an exception during processing.

**Comment by lextm** [comment]
To learn the exact log entries to troubleshoot, you need to follow #397 

https://github.com/obfuscar/obfuscar/issues/397#issuecomment-1343903147
