### ISSUE TITLE
Not able to Obfuscated the Method Body.... could you please correct me if am doing anything wrong 

### ISSUE THREAD

**Issue by 2007jaga** [obfuscar/obfuscar#354]
Hi Team ,
Thanks in Advance.

I am trying Obfuscate the Method body below are the step which I have followed
Could you please suggest me , where I am doing wrong.

![image](https://user-images.githubusercontent.com/54856309/146351806-8f8cb48f-ad17-4d38-a952-7d7e94a00b57.png)

![image](https://user-images.githubusercontent.com/54856309/146351937-ff86b433-3b69-401a-8760-011dd93e1ae1.png)
 
![image](https://user-images.githubusercontent.com/54856309/146352192-e9eeda5f-4e67-49bc-855a-8441451c2d61.png)

**Comment by lextm** [comment]
For simple functions, obfuscation almost has nothing to do. A good enough decompiler like ILSpy can easily reconstruct the whole function body as MSIL provides that rich metadata. This applies to not only Obfuscar, but other .NET obfuscation tools.

Therefore, if your goal is to evaluate an obfuscation tool, please use a complex enough project (ideally a real world open source project with hundreds of classes and thousands of methods) and then you see how effective obfuscation can be.

**Comment by 2007jaga** [comment]
Thank you Lextm
