### ISSUE TITLE
i meet a question when use command line "Obfuscar.Console.exe config.xml"

### ISSUE THREAD

**Issue by echocxl** [obfuscar/obfuscar#355]
it is the first time i use this software, then i met a question like:

Note that Rollbar API is enabled by default to collect crashes. If you want to opt out, please run with -s switch
Loading project config.xml...Processing assembly: CodedUITestBuilder, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Loading assemblies...Extra framework folders:
An error occurred during processing:
Unable to resolve dependency:  Microsoft.VisualStudio.QualityTools.CodedUITestFramework

how can i do to solve it?
thanks! it is very important.

**Comment by lextm** [comment]
https://docs.obfuscar.com/support/faq.html#how-to-troubleshoot-resolutionexception-or-assemblyresolutionexception

**Comment by echocxl** [comment]
> https://docs.obfuscar.com/support/faq.html#how-to-troubleshoot-resolutionexception-or-assemblyresolutionexception

Ok，thank you very much,I had solve this problem.But I occurred another problem seems like this:

Loading project config.xml...Processing assembly: CodedUITestBuilder, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Loading assemblies...Extra framework folders: Done.
Hiding strings...
Renaming:  fields...Parameters...Properties...Events...Methods...Types...Done.
Saving assemblies...
An error occurred during processing:
Obfuscating a signed assembly would result in an invalid assembly:  CodedUITestBuilder; use the KeyFile or KeyContainer property to set a key to use

It seems my CodedUITestBuilder version is not suitable(I use visual studio 2019 enterprise now).
Should I Change my visual studio version(does Obfuscar.2.2.32 command line tools must running on specific vs vision?) or other to solve this problem?

**Comment by lextm** [comment]
Please try to spend enough time going through the whole documentation site, as it has been documented,

https://docs.obfuscar.com/getting-started/configuration.html#signing-of-strongly-named-assemblies
