### ISSUE TITLE
Can you skip obfuscation of derived types with an ObfuscationAttribute?

### ISSUE THREAD

**Issue by brinkdinges** [obfuscar/obfuscar#356]
I have moved my exceptions to the top-level namespace in my product, but I like them to not be obfuscated so the stack traces at least show the exception type. Is this possible by creating a parent exception type and decorating it with an ObfuscationAttribute? I tried, but it doesn't seem to work by default.

Since the exceptions are at the top-level namespace, I'd rather not exclude that namespace in the Obfuscar config.

My current workaround is adding the attribute to each type.
![image](https://user-images.githubusercontent.com/15387410/148913039-7c6b3ad1-86dd-4a49-84c1-3e05091d7dd7.png)

**Comment by lextm** [comment]
To me, Microsoft didn't design the Obfuscation attribute to be automatically passed on to derived types, so the current behavior of Obfuscar is by design.

Like you discovered, to obfuscate derived classes, you need to add this attribute to them individually.
