### ISSUE TITLE
 IL virtualization

### ISSUE THREAD

**Issue by Jacellen** [obfuscar/obfuscar#359]
Is it planned to add IL virtualization like in agile.net CSVM?

**Comment by lextm** [comment]
Pull requests are welcome, but no plan to work on this feature. Buy a commercial obfuscation tool is you need such advanced features.

**Comment by Jacellen** [comment]
> Pull requests are welcome, but no plan to work on this feature. Buy a commercial obfuscation tool is you need such advanced features.


What can you advise?
