### ISSUE TITLE
exited with code 1

### ISSUE THREAD

**Issue by CeaserFLY** [obfuscar/obfuscar#360]
Net Framework 4.8 I am using. (Visual Studio 2019)

<?xml version="1.0"?>
<Obfuscator>
	<Var name="InPath" value=".\obj\Debug\" />
	<Var name="OutPath" value=".\Obfuscator_Output" />
	<Var name="KeepPublicApi" value="false" />
	<Var name="HidePrivateApi" value="true" />
	<Module file="$(InPath)\Login.exe" />
</Obfuscator>

Error: https://i.ibb.co/8PWb6yv/error.png

I searched in the issues section but couldnt find a solution.

**Comment by lextm** [comment]
https://docs.obfuscar.com/support/faq.html#how-to-understand-the-return-code

**Comment by CeaserFLY** [comment]
> 

no solution here

**Comment by tarekxxx** [comment]
yea there no help

**Comment by pulmuone** [comment]
obfuscar.xml Copy always

**Comment by lextm** [comment]
https://github.com/obfuscar/obfuscar/issues/397#issuecomment-1343903147 Follow that to learn the actual log entries.
