### ISSUE TITLE
Firebase obfuscation Error

### ISSUE THREAD

**Issue by boardpen** [obfuscar/obfuscar#363]
Instead of this dialog, just-in-time debugging (JIT) is called.
For more information on how, see the latter part of this message.

************** Exception text *********
System.ArgumentNullException: StringReference is not set as an instance of a string.
Parameter name: s
   Location: System.DateTimeParse.Parse (Strings, DateTimeFormatInfodfi, DateTimeStyles)
   Location: System.DateTime.Parse(Strings)
   Location: Kakao Story Solution.Form2.a.f()
--- End of stack tracking at the previous location where the exception was rolled ---
   Location: System.Runtime.CompilerServices.Async MethodBuilderCore.<>c.<ThrowAsync>b__6_0 (Object state)

************** Loaded assembly ***********
mscorlib
    Assembly version: 4.0.0.0
    Win32 version: 4.8.4470.0 build by: NET48REL1LAST_C
    Codebase: file://C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Kakao Story Solution.
    Assembly version: 1.0.0.0
    Win32 version: 1.0.0.0
    Code base: file://C:/Users/SongSengHyun/Desktop/%EC%A0%95%EB6%AC/%EA%B0%9C%EC%9D%B8/%ED%81%AC%EB%AA%B/C%23/%EC%A0%95%EB9%EB9%EBC95%
----------------------------------------
Microsoft.VisualBasic
    Assembly version: 10.0.0.0
    Win32 version: 14.8.4084.0 build by: NET48REL1
    Codebase: file://C:/Windows/Microsoft.Net/assumbly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dllllllll
----------------------------------------
System
    Assembly version: 4.0.0.0
    Win32 version: 4.8.4488.0 build by: NET48REL1LAST_C
    Codebase: file://C:/Windows/Microsoft.Net/assumbly/GAC_MSIL/System/v4.0_4.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly version: 4.0.0.0
    Win32 version: 4.8.4470.0 build by: NET48REL1LAST_C
    Codebase: file://C:/Windows/Microsoft.Net/assumbly/GAC_MSIL/System.Core/v4.0_4.0.0_4.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly version: 4.0.0.0
    Win32 version: 4.8.4488.0 build by: NET48REL1LAST_C
    Codebase: file://C:/Windows/Microsoft.Net/assumbly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0_4.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly version: 4.0.0.0
    Win32 version: 4.8.4390.0 build by: NET48REL1LAST_C
    Codebase: file://C:/Windows/Microsoft.Net/ACT_MSIL/System.Drawing/v4.0_4.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly version: 4.0.0.0
    Win32 version: 4.8.4190.0 build by: NET48REL1LAST_B
    Codebase: file://C:/Windows/Microsoft.Net/assumbly/GAC_MSIL/System.Configuration/v4.0_4.0.0__4.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly version: 4.0.0.0
    Win32 version: 4.8.4084.0 build by: NET48REL1
    Codebase: file://C:/Windows/Microsoft.Net/assumbly/GAC_MSIL/System.Xml/v4.0_4.0.0_4.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly version: 4.0.0.0
    Win32 version: 4.8.4084.0 build by: NET48REL1
    Codebase: file://C:/Windows/Microsoft.Net/assumbly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
WebDriver
    Assembly version: 3.141.0.0
    Win32 version: 3.141.0.0
    Code base: file://C:/Users/SongSengHyun/Desktop/%EC%A0%95%EB6%AC/%EA%B0%9C%EC%9D%B8/%ED%81%AC%EB%AA%B/C%23/%EC%A0%95%EB9%EB9%EBC95%
----------------------------------------
FireSharp
    Assembly version: 1.1.0.0
    Win32 version: 1.1.0
    Code base: file://C:/Users/SongSengHyun/Desktop/%EC%A0%95%EB6%AC/%EA%B0%9C%EC%9D%B8/%ED%81%AC%EB%AA%B/C%23/%EC%A0%95%EB9%EB9%EBC95%
----------------------------------------
RestSharp
    Assembly version: 104.4.0.0
    Win32 version: 104.4.0.0
    Code base: file://C:/Users/SongSengHyun/Desktop/%EC%A0%95%EB6%AC/%EA%B0%9C%EC%9D%B8/%ED%81%AC%EB%AA%B/C%23/%EC%A0%95%EB9%EB9%EBC95%
----------------------------------------
mscorlib.resources
    Assembly version: 4.0.0.0
    Win32 version: 4.8.4084.0 build by: NET48REL1
    Codebase: file://C:/Windows/Microsoft.Net/assumbly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0_4.0.0.0_ko_b77a5c561934e089/mscorlib.resources.dllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll
----------------------------------------
System.Windows.Forms.resources
    Assembly version: 4.0.0.0
    Win32 version: 4.8.4084.0 build by: NET48REL1
    Code base : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** **************, debugging jit
Jit (just in time) To use the debugging of the application or machine.
(a machine config) File config of the value of the jitdebugging 
System windows, forms should be set in the section.
Debugging applications can also be compiled.
I am doing.

E.g.

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

All exceptions are not processed, the debugging jit.
This dialog box, not been processed and registered in the computer jit. 
Be sent to the debugger.

**Comment by lextm** [comment]
Without a sample project, it is impossible to guess what might be wrong.
