### ISSUE TITLE
AssemblySearchPath

### ISSUE THREAD

**Issue by coader** [obfuscar/obfuscar#364]
Is possible tools can auto find dll in:
C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.2\ref\net6.0
C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\6.0.2\ref\net6.0

I put it in configuration file and works ok, but if upgrade .net version, have to edit each xml file for all projects

**Comment by coader** [comment]
also this:
C:\Users\progame\.nuget\packages\system.configuration.configurationmanager\5.0.0\ref\netstandard2.0
System.Configuration.ConfigurationManager.dll

many third party dll use this dll

**Comment by lextm** [comment]
Developers have too many ways (MSBuild/VS T4/PowerShell) to detect what's needed to be added to search paths in their CI/CD pipelines and generate Obfuscar configuration on the fly, so it is not a must for Obfuscar to perform such detection.

**Comment by Rufus31415** [comment]
> I put it in configuration file and works ok, but if upgrade .net version, have to edit each xml file for all projects

Same problem, and I would add:
- If your assembly is compiled in several versions of .NET, you need to create different configuration XMLs that point to different AssemblySearchPath 🤮 
- Github runner regularly updates .NET SDKs, so it's almost impossible to keep up to date.
