### ISSUE TITLE
 anonymous type in linq, the ctor parameter name is null

### ISSUE THREAD

**Issue by coader** [obfuscar/obfuscar#366]
var q = from e in _uow.Template.Set
                    where e.TemplateId > 0
                    select new { e.TemplateId, e.TemplateName };

for the new { e.TemplateId, e.TemplateName } type, when use:
ParameterInfo[] parameters = constructorInfo.GetParameters();

and parameter name is null

**Comment by lextm** [comment]
Not clear what you meant. Can you provide more details?
