### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by Pulkitsoft** [obfuscar/obfuscar#368]
Dear Team,
        I am using vb.net. When trying to build gets an error.

The command ""**C:\Users\RamAnjana\.nuget\packages\obfuscar\2.2.33\build\..\tools\Obfuscar.Console.exe" obfuscar.xml" exited with code 1**

`<Obfuscator>
<Var name="InPath" value="D:\test\Project\bin\x86\Debug" />
<Var name="OutPath" value="D:\test\Project\bin\x86\Debug\Obfuscator_Output" />
<Var name="HidePrivateApi" value="true" />
<Module file="$(InPath)\DigitalSigner.exe" />
</Obfuscator>`

![error](https://user-images.githubusercontent.com/69751133/157430296-31433f80-7669-4ca3-8a19-ee33cee4c149.JPG)

**Comment by lextm** [comment]
https://docs.obfuscar.com/support/faq.html#how-to-understand-the-return-code

**Comment by lextm** [comment]
https://github.com/obfuscar/obfuscar/issues/397#issuecomment-1343903147 Follow this to learn the actual log entries.
