### ISSUE TITLE
any more rename strategy for user select?

### ISSUE THREAD

**Issue by coader** [obfuscar/obfuscar#369]
now, many fields has the same name 'A' , in linq and reflect,  this name is very import to me and it must be unique, also it's better ignore case sensitive

**Comment by lextm** [comment]
Contrarily a good obfuscation tool should generate ambiguity to raise the bar of reverse engineering. Thus, Obfuscar only provides three settings on how names should be picked up, https://docs.obfuscar.com/getting-started/configuration.html#settings

No plan to add any more as they are not likely to offer any more value.
