### ISSUE TITLE
Extra framework folders: Still in pool when the type inherit it's nested interface

### ISSUE THREAD

**Issue by lindexi** [obfuscar/obfuscar#371]
### Problem description:

The obfuscar will throw the ObfuscarException `Cannot clean pool` when the type inherit it's nested interface.

Such as the code:

```csharp
public class F1 : F1.IF2
{
    interface IF2
    {

    }
}
```

Because the node in the pool in AssemblyInfo.Graph.CleanPool method will loop reference.

Minimal repro:

See https://github.com/lindexi/lindexi_gd/tree/a83194b39bcddfe4a4ccc780049123db35cba270/BajereleehaNalleedihechear

**Comment by lextm** [comment]
It's a nice catch. The old C# compilers will reject such a class, but Roslyn seems to allow it. That's why such an issue was not identified in the past.

**Comment by lindexi** [comment]
Thank you @lextm
