### ISSUE TITLE
Unable to resolve dependency:  Microsoft.AspNetCore.Mvc.Core

### ISSUE THREAD

**Issue by hy-net** [obfuscar/obfuscar#375]
I need to put this into the Obfuscar.xml

    <AssemblySearchPath path="C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\5.0.9" />

This is troublesome, because we might not aware the library been updated by Visual Studio in future.

And since this is part of the standard libraries used by Visual Studio, in my opinion Obfuscar should be able to locate them without the need to explicitly specify in AssemblySearchPath

**Comment by lextm** [comment]
Related to #553 but might not be resolved in vNext yet.
