### ISSUE TITLE
How do i compile

### ISSUE THREAD

**Issue by tarekxxx** [obfuscar/obfuscar#376]
its saying on visual basic 2019

Severity	Code	Description	Project	Path	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.	GlobalTools	C:\Program Files\dotnet\sdk\5.0.407\Sdks\Microsoft.NET.Sdk\targets	C:\Program Files\dotnet\sdk\5.0.407\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	141	

Severity	Code	Description	Project	Path	File	Line	Suppression State
Warning		The project 'Obfuscar' cannot be referenced. The referenced project is targeted to a different framework family (.NETCoreApp)	Obfuscar.Console				

Severity	Code	Description	Project	Path	File	Line	Suppression State
Warning		The project 'Obfuscar' cannot be referenced.	ObfuscarTests				

any help please what i should download or what i should i do ???

**Comment by lextm** [comment]
Due to the global tool project, you need to use the latest VS release (2022 at this moment) to compile the whole code base.

**Comment by tarekxxx** [comment]
okay iam testing to download VS2022 i hope you help me until i finish this problem

**Comment by tarekxxx** [comment]
i cant run it even install VS2022 missing files Obfuscar not in file i dont know how try to download it nothing bytheway

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project Obfuscar.GlobalTool is not compatible with net462 (.NETFramework,Version=v4.6.2) / win. Project Obfuscar.GlobalTool supports:
  - net5.0 (.NETCoreApp,Version=v5.0)
  - net6.0 (.NETCoreApp,Version=v6.0)
  - netcoreapp3.1 (.NETCoreApp,Version=v3.1)	Obfuscar.Console	C:\Users\Administrator\Desktop\obfuscar-2.2.33\Console\Obfuscar.Console.csproj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The project 'Obfuscar' cannot be referenced. The referenced project is targeted to a different framework family (.NETCoreApp)	ObfuscarTests			


Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'System.Xml' could not be found.	Obfuscar.Console			


Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'System.Windows.Forms' could not be found.	Obfuscar.Console			


there even no builder or exe file god

**Comment by tarekxxx** [comment]
no saying 


Severity	Code	Description	Project	File	Line	Suppression State
Warning		The project 'Obfuscar' cannot be referenced. The referenced project is targeted to a different framework family (.NETCoreApp)	Obfuscar.Console

**Comment by tarekxxx** [comment]
even Obfuscar dont need installed by nuget

**Comment by lextm** [comment]
Not quite understand what you mean, but if you want to use Obfuscar to obfuscate your assemblies, you should get started from https://docs.lextudio.com/obfuscar/tutorials/basics
