### ISSUE TITLE
Signed obfuscated Dll throwing error (System.IO.FileNotFoundException: 'Could not load file or assembly 'Mapping, Version=1.1.0.0, Culture=neutral, PublicKeyToken=f75898652364'. The system cannot find the file specified."

### ISSUE THREAD

**Issue by Mitkari** [obfuscar/obfuscar#380]
Application build with strongname(i.e signing) in Visual studio2019.
then obfuscated those signed DLLs.
then those dlls are given as reference into another application.
when we try to run application it throwing below error,
"System.IO.FileNotFoundException: 'Could not load file or assembly 'Mapping, Version=1.1.0.0, Culture=neutral, PublicKeyToken=f7586df183956336'. The system cannot find the file specified.'"

**Comment by lextm** [comment]
I can see that you changed the public key token in the title, which is rather strange for an issue raised.

You didn't provide much other information, so I can only guess that you don't have a dedicated key to sign the assemblies during the initial build, and don't have such a key for obfuscation either. Then all kinds of issues can happen.

Can you use a single key to sign during initial build and also use the same key for obfuscation? Then I think this issue will go away.
