### ISSUE TITLE
Obfuscar .NET 6 error with System.Configuration.ConfigurationManager

### ISSUE THREAD

**Issue by KapsbergerS** [obfuscar/obfuscar#384]
I'm trying to obfuscate (Obfuscar NuGet) a .NET 6 app, but I'm getting an error

`Loading assemblies...Extra framework folders:
An error occurred during processing:
Unable to resolve dependency: System.Configuration.ConfigurationManager`

I tried to add NuGet package System.Configuration.ConfigurationManager, but it did not help.
I also tried to install Obfuscar.GlobalTool, but it did not install:

`NU1212: Invalid combination of project and package for Obfuscar.GlobalTool 2.2.33. The DotnetToolReference project style only allows references of type DotnetTool Package "Obfuscar.GlobalTool 2.2.33" has package type "DotnetTool" which is not supported by the project`

**Comment by lextm** [comment]
Duplicate to #357 and #336

**Comment by KapsbergerS** [comment]
You are right, the solution was to add this line:
`<AssemblySearchPath path="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.8\ref\net6.0\"/>`
