### ISSUE TITLE
Unable to resolve assembly

### ISSUE THREAD

**Issue by ketanmehra30** [obfuscar/obfuscar#385]
I am using  Microsoft.CodeAnalysis in my project and I want to obfuscate my custom roslyn rules but when I build the project obfuscar throw this error

 1>An error occurred during processing:
1>Unable to resolve dependency:  Microsoft.CodeAnalysis (it is a nuget package)

how can I make sure the obfuscar find the above dependency? Thanks

**Comment by lextm** [comment]
From MSBuild bin log you can find out the location of that assembly used by C# compiler, https://msbuildlog.com/

Then you can add the folder to Obfuscar XML config file so that this dependency can be resolved properly.
