### ISSUE TITLE
VirusTotal -  Cynet  Malicious (score: 100)  SecureAge APEX  Malicious

### ISSUE THREAD

**Issue by BigFatO** [obfuscar/obfuscar#386]
Hello, I'd like to ask that I created an empty WPF application and protected it with obfuscar,  the verification report I submitted to VirusTotal shows two errors "**2 security vendors and no sandboxes flagged this file as malicious**". So I would like to ask how to solve this problem?

Following are behavior from VirusTotal:

[Defense Evasion](https://www.virustotal.com/gui/search/attack_technique%253ATA0005) TA0005
[Timestomp](https://www.virustotal.com/gui/search/attack_technique%253AT1070.006) T1070.006
 Binary contains a suspicious time stamp

[Virtualization/Sandbox Evasion](https://www.virustotal.com/gui/search/attack_technique%253AT1497) T1497
 Uses Windows timers to delay execution

 Sample may be VM or Sandbox-aware, try analysis on a native machine

[Disable or Modify Tools](https://www.virustotal.com/gui/search/attack_technique%253AT1562.001) T1562.001
 Creates guard pages, often used to prevent reverse engineering and debugging

[Discovery](https://www.virustotal.com/gui/search/attack_technique%253ATA0007) TA0007
[System Information Discovery](https://www.virustotal.com/gui/search/attack_technique%253AT1082) T1082
 Queries the cryptographic machine GUID

 Reads software policies

 Queries the volume information (name, serial number etc) of a device

[System Time Discovery](https://www.virustotal.com/gui/search/attack_technique%253AT1124) T1124
 Potential time zone aware malware

[Virtualization/Sandbox Evasion](https://www.virustotal.com/gui/search/attack_technique%253AT1497) T1497
 Uses Windows timers to delay execution

 Sample may be VM or Sandbox-aware, try analysis on a native machine

**Comment by lextm** [comment]
Duplicate to #166
