### ISSUE TITLE
There is no obfuscation in fields, classes and methods in my WPF obfuscated exe result

### ISSUE THREAD

**Issue by francescmp** [obfuscar/obfuscar#388]
First of all thanks for this amazing project and let us use it.

I'm trying to obfuscate a WPF/C# project.
By testing the configuration I get these issues:
  <Var name="KeepPublicApi" value="false" /> -> NotImplementedException
  <Var name="HidePrivateApi" value="true" /> -> ArgumentException: Ya se ha agregado el elemento. Clave en el diccionario: ' '  Clave agregada: ' ' as #137

So I tried to leave KeepPublicApi true and HidePrivateApi false.
And the rest of the configuration is like this:

 ```
 <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="UseUnicodeNames" value="true" />
  <Var name="HideStrings" value="true" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="true" />

```
But the obfuscated result is not very obfuscated. I mean, the fields keep the same name, the methods also and even the classes' names didn't change. Is it because of the assigned values to KeepPublicApi and HidePrivateApi? Or I'm missing something?

Strings are properly hidden. But not the rest of the classes.

I hope you can give me some clarity or a similar question because I couldn't find it.

Thanks in advance.

**Comment by lextm** [comment]
https://docs.obfuscar.com/support/faq#how-to-troubleshoot-typeloadexception-during-reflection

Please refer to "Important" section to learn more.

**Comment by lextm** [comment]
Duplicate to #551
