### ISSUE TITLE
SkipProperty is not working

### ISSUE THREAD

**Issue by amarbadir** [obfuscar/obfuscar#389]
How I can exclude the following property DeveloperKey from obfuscation?

namespace A
{
    public partial class U
    {
         [Browsable(false)]
        public static string DeveloperKey { get; set; }
    }
}

all in "test.dll"

**Comment by lextm** [comment]
You can refer to the unit test cases for guides on how to use certain features, https://github.com/obfuscar/obfuscar/blob/2.2.35/Tests/SkipPropertyTests.cs
