### ISSUE TITLE
Installing Obfuscar  2.2.33 in Visual Studio 2022 CE does not add Obfuscar to Tools menu

### ISSUE THREAD

**Issue by dbaechtel** [obfuscar/obfuscar#393]
Installing Obfuscar  2.2.33 in Visual Studio 2022 CE does not add Obfuscar to Tools menu

**Comment by lextm** [comment]
This is out of scope. Components from this open source project never add anything to Visual Studio Tools menu.

If you used to use something else to integrate Obfuscar with Visual Studio, contact its vendor please, not here.

**Comment by lextm** [comment]
This repo only ships artifacts via a NuGet.org package, so there is nothing to be added to the Tools menu, unlike other obfuscation tools.

The recommended way to use it has been documented in https://docs.obfuscar.com/tutorials/basics
