### ISSUE TITLE
 Installing Obfuscar 2.2.33 in Visual Studio 2022 CE does not add Obfuscar to Tools menu 

### ISSUE THREAD

**Issue by dbaechtel** [obfuscar/obfuscar#394]
Installing Obfuscar 2.2.33 in Visual Studio 2022 CE does not add Obfuscar to Tools menu 
How do I add Obfuscar  to the Visual Studio 2022 CE Tools menu?

**Comment by lextm** [comment]
Duplicate to #393.

Please stop creating duplicate items, or you will be blocked.
