### ISSUE TITLE
Give an Example usage of obfuscar [Options] [project_file] [project_file] with ,Net core

### ISSUE THREAD

**Issue by dbaechtel** [obfuscar/obfuscar#395]
Give an Example usage of obfuscar [Options] [project_file] [project_file] with ,Net core in Documentation.
Show completed example of how to use this command line with an example Visual Studi project.

**Comment by lextm** [comment]
No plan at this moment to support passing project files via command line parameter. The XML file will be the only supported way.

No plan to add .NET Core specific example. The same post build event approach can be used to obfuscate assemblies.

**Comment by lextm** [comment]
Note that you can read previous .NET Core related discussions to learn more, https://github.com/obfuscar/obfuscar/issues?q=label%3A%22area%3A.NET+Core%22+is%3Aclosed
