### ISSUE TITLE
How to specify assemblies that start with specific Names e.g. MyCompany.?

### ISSUE THREAD

**Issue by ahmedtolba1984** [obfuscar/obfuscar#398]
Dears,
This is the first time I checked this fantastic package and my requirements are:-

- Is it possible to use it in an Integration Server Build CI?
- Is it support .NET Core 6.0?
- Is there any way to specify assemblies **that start with specific Name** e.g. **MyCompany.**Assembly1 or **MyCompany.**Assembly2, **MyCompany.**......... instead of specifying each one explicitly as it will be nightmare?

**Comment by lextm** [comment]
If you perform some evaluation you will see the answers.

The documentation is at https://docs.obfuscar.com

**Comment by ahmedtolba1984** [comment]
@lextm I already checked the documentation before posting my question but i checked the AssemblySearchPath but can't find a clear answer about my question
**Search Assemblies that start with specific Name**

**Comment by lextm** [comment]
Sounds like `<Modules>` was not yet added to the configuration, but you can take a look, https://github.com/obfuscar/obfuscar/pull/254#issuecomment-581113846 But that's not a must-have feature.

You can use a simple PowerShell script to easily generate a list of `<Module>` tags and then use in your config file.
