### ISSUE TITLE
Xamarin System.NotSupportedException after obfuscation

### ISSUE THREAD

**Issue by AlexanderTretyackov** [obfuscar/obfuscar#399]
Hello!

Android app crashes when places a Renderer in a folder and obfuscate it then build APK and deploy. If the Renderer is in a project folder then App works correctly.

App without obfuscation works correctly.

I created a small [repository](https://github.com/AlexanderTretyackov/ObfuscarBug) with error.

[Log](https://github.com/obfuscar/obfuscar/files/10004399/log.txt) with error

Visual Studio 2022 Version 17.4.0

How can I fix this error?

**Comment by lextm** [comment]
https://docs.obfuscar.com/tutorials/xamarin#troubleshooting

You might follow the guide to debug on your own.

The rule of thumb is that you cannot obfuscate everything and certain names must be kept due to dependency injection, XAML/AXML references, or other possible ways.
