### ISSUE TITLE
Crash when obfuscating large enterprise application

### ISSUE THREAD

**Issue by ahmedtolba1984** [obfuscar/obfuscar#400]
Dears,
I got an exception when trying to obfuscate my large enterprise application
My Configurations 
```
<?xml version="1.0" encoding="utf-8" ?>
<Obfuscator>
  <Var name="InPath" value="." />
  <Var name="OutPath" value=".\Obfuscator_Output" />
  <Var name="HidePrivateApi" value="true" />
  <AssemblySearchPath path="$(InPath)\refs" />
  <LogFile value=".\Obfuscator_Output\Log.xml" />
  <Modules>
    <IncludeFiles>$(InPath)\AlWefaq.*.dll</IncludeFiles>
  </Modules>
</Obfuscator>
```

I got this error and the obfuscar.console got crashed
Saving assemblies...Unhandled exception. System.ArgumentException: Member 'System.String <PrivateImplementationDetails>{7232B00A-3237-45BD-A8D5-BA8B9EF468C5}.C6BB5D3D-C03E-4D43-82CD-7FC7BB693D18::A()' is declared in another module and needs to be imported
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
![ObfusIssue](https://user-images.githubusercontent.com/6592222/202258773-9498314f-e9e9-4d65-a156-49870e72551b.png)

**Comment by ahmedtolba1984** [comment]
@lextm 
Any help as I stuck with this issue?

**Comment by lextm** [comment]
`<AssemblySearchPath path="$(InPath)\refs" />` is suspicious. Can you move that entire `ref` folder out of `InPath` and try again?

**Comment by ahmedtolba1984** [comment]
@lextm 
Thanks for your quick action, I already did your guide and removed <AssemblySearchPath path="$(InPath)\refs" />
but i got another exception
Loading assemblies...Extra framework folders:
An error occurred during processing:
Unable to resolve dependency:  Microsoft.AspNetCore.Identity

**Comment by lextm** [comment]
You might come across many issues if this is the first time you try it out, but I won't be able to guide you through all corner cases. Try to learn from previous threads like https://github.com/obfuscar/obfuscar/issues?q=is%3Aissue+is%3Aopen+label%3A%22area%3A.NET+Core%22 and https://docs.obfuscar.com.

**Comment by ahmedtolba1984** [comment]
@lextm 
Unfortunately, i checked all of these issues before posting my question
