### ISSUE TITLE
Rename the private variable in the public method

### ISSUE THREAD

**Issue by Jimex** [obfuscar/obfuscar#404]
``` xml
<Var name="KeepPublicApi" value="true" />
<Var name="HidePrivateApi" value="true" />
```

When I use the above settings, I also want to rename the private variable in the public method, may I know is there any way to do it?

**Comment by lextm** [comment]
Do you mean "local variable" in public methods? I don't think "private variable" is a term in C# language,

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/

**Comment by Jimex** [comment]
> Do you mean "local variable" in public methods? I don't think "private variable" is a term in C# language,
> 
> https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/

Yes, you are right. I was referring to the variables in the public method, sorry for the confusion.

**Comment by lextm** [comment]
Local variables lost their names when C# compiler generates the assemblies. You can use any tool (ildasm or ILSpy) to analyze the generated MSIL (not C#) and confirm what I said.

**Comment by Jimex** [comment]
However,  I still can see the original variable names from the ILSpy. My app is a WinUi 3 desktop app built with .net 6.

![image](https://user-images.githubusercontent.com/3145858/210159934-57a8c922-7b01-4e30-abef-889f60bbe5db.png)

**Comment by lextm** [comment]
Like I said, switch to MSIL view and see what is there. ILSpy or another decompiler is smart enough to generate variable names based on their types, so I am not surprised.

**Comment by p-vogt** [comment]
@lextm Are you sure about the renaming? I am facing the same issue at the moment (.NET7).
Not sure if I am missing something:

Code:
![image](https://user-images.githubusercontent.com/32958488/224644475-b695ec36-ecda-409e-bfe4-89bd7c136854.png)

ILSpy:
![image](https://user-images.githubusercontent.com/32958488/224644423-530fd398-6062-49a6-8dc0-4ef3d45951e7.png)

![image](https://user-images.githubusercontent.com/32958488/224644306-27fefa09-ea5b-42cd-8f61-b381eb2bcc37.png)
