### ISSUE TITLE
Private method

### ISSUE THREAD

**Issue by MuNet** [obfuscar/obfuscar#407]
Good afternoon, I would like to ask if there is a switch that can be set to confuse only variables without confusing methods, whether it is public or private.

**Comment by lextm** [comment]
What kind of variable? You probably should go back to C# language guide to study what are the right terms to use,

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/

**Comment by MuNet** [comment]
> 
I want to obfuscate only the code inside the method, not the method name, for example:
private void RegisterCustom(string dsad758asd78d5f4ds)
{
 var ffg7df545j7= dsf5ds6f5ds.h7f5g4(dsad758asd78d5f4ds);
 ....
}

**Comment by MuNet** [comment]
> What kind of variable? You probably should go back to C# language guide to study what are the right terms to use,
> 
> https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/

I want to obfuscate only the code inside the method, not the method name, for example:
private void RegisterCustom(string dsad758asd78d5f4ds)
{
var ffg7df545j7= dsf5ds6f5ds.h7f5g4(dsad758asd78d5f4ds);
....
}

**Comment by lextm** [comment]
Like discussed in #404, local variables in methods are processed by C# compiler and the names are lost during compilation.

You seem to also want to obfuscate fields, and then you can use `ForceField` rules, which is the inverse of `SkipField`,

https://docs.obfuscar.com/getting-started/configuration#inclusion-rules-by-configuration-new
