### ISSUE TITLE
"Key containers are not supported for Mono" error, but I'm not using key containers

### ISSUE THREAD

**Issue by tekhedd** [obfuscar/obfuscar#408]
Obfuscar versions greater than 2.2.4 fail to obfuscate strong-signed assemblies under mono with the message that "key containers are not supported", even when signed with a simple SNK. Judging from the source code (Project.KeyValue), this error is only emitted when using RSA under Mono, so there's definitely a bug here, one of these two:

1) Key containers are not supported, in which case I should not be seeing an error, and this code is incorrectly emitting an error (because I'm just using a generic SNK generated using mono's SN), or

2) RSA is not supported under Mono, in which case the error message should probably say this. Also, it really looks like RSA is actually supported. :)

Maybe I'm the only person left in the world using Obfuscar under Mono?

Other notes:

 * Error occurs even if I don't specify KeyFile in obfuscar.xml
 * Error does not occur with Obfuscar 2.2.4 (and 2.1.11), obfuscates fine
 * mono 6.12.0.182

Hope this helps!

**Comment by lextm** [comment]
Very likely that you are one of the tiny group of users on Mono.

This project is targeting .NET Framework and .NET Core, with almost zero test cases specific to Mono. So, even a patch has been included in release 2.2.37, I am certain whether this Mono specific issue has been fully fixed.

You can give it a try and report back.
