### ISSUE TITLE
HideStrings not working

### ISSUE THREAD

**Issue by BlackMagicCoding** [obfuscar/obfuscar#409]
Obfuscar version: 2.2.36.0
.NET runtime version: Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Hello,

first time Obfuscar user here :)
I managed to obfuscate my application's dll so far, but the variable HideStrings  seems to not have any effect at all.
![image](https://user-images.githubusercontent.com/57157966/209245439-c015a040-5f81-4cd9-81ea-d41ebc96cf57.png)

My `config.xml` looks like this:
```
<?xml version='1.0'?>
<Obfuscator>
  <AssemblySearchPath path="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.12\ref\net6.0\"/>
  <Var name="InPath" value=".\ObfuscarInput" />
  <Var name="OutPath" value=".\ObfuscarOutput" />
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="RenameProperties" value="false" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="UseUnicodeNames" value="false" />
  <Var name="HideStrings" value="true" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="true" />
  <Module file="$(InPath)\thatsmy.dll" />
</Obfuscator>
```

I have read on other issues, that it has something to do with Encoding not being able to be resolved, but unfortunately I haven't really understood.
Could you elaborate in more detail what one has to do to make this work?
There isn't any errors or warnings thrown, and I also do not see any --verbose mode.
Let me know if there is any more information you need from my side, sine I am eager to help... this will be an issue for a lot of other people too.

Kind regards

**Comment by lextm** [comment]
When you are sure others might face the same issue, you should spend some time searching in closed issues.
