### ISSUE TITLE
RenameProperties leads to application no longer working

### ISSUE THREAD

**Issue by BlackMagicCoding** [obfuscar/obfuscar#410]
Obfuscar version: 2.2.36.0
.NET runtime version: Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Hello,

I have another issue:
Obfuscation works fine, as long as I do not obfuscate Enums (I have disabled those via SkipEnums, that's fine) or use RenameProperties.

`<Var name="RenameProperties" value="true" />`
The above line leads to my app simply not starting anymore, no exception or any hint at all.
ILSpy tells me that the obfuscation of the Properties worked out.
Is there a common / good way how to debug this issue, so that I know what's wrong?
With the Enums the issue was, that I am parsing some Strings into those, but I don't parse any Properties.

My config.xml looks like this:
```
<?xml version='1.0'?>
<Obfuscator>
  <AssemblySearchPath path="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.12\ref\net6.0\"/>
  <Var name="InPath" value=".\ObfuscarInput" />
  <Var name="OutPath" value=".\ObfuscarOutput" />
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="UseUnicodeNames" value="true" />
  <Var name="HideStrings" value="true" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="true" />
  <Module file="$(InPath)\thatsmy.dll">
	<SkipEnums value="true" />
  </Module>
</Obfuscator>
```

Kind regards

**Comment by lextm** [comment]
Typical .NET debugging still applies. You can use a debugger from VS or WinDbg to launch the executable and step through the obfuscated code.

However, this requires intermediate to advanced level knowledge of .NET. So, if you are not familiar with the area, hire a consultant or switch to a commercial product with technical support.
