### ISSUE TITLE
In .NET CORE 6, user strings are not obfuscated.

### ISSUE THREAD

**Issue by pulmuone** [obfuscar/obfuscar#414]
In .NET CORE 6, user strings are not obfuscated.

my source : 
https://github.com/pulmuone/WinFormsApp6

Screen-shot :
https://github.com/pulmuone/WinFormsApp6/blob/master/Obfuscator.png

test : 
\bin\Debug\net6.0-windows>Obfuscar.Console.exe -s obfuscar.xml

**Comment by pulmuone** [comment]
obfuscar.xml
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value="." />
  <Var name="OutPath" value=".\Obfuscator_Output" />
  <Var name="KeepPublicApi" value="false" /> 
  <Var name="HidePrivateApi" value="true" />

  <AssemblySearchPath path="c:\progra~1\dotnet\shared\microsoft.netcore.app\6.0.14" />
  <Module file="$(InPath)\WinFormsApp6.dll" />
</Obfuscator>


<AssemblySearchPath path="c:\progra~1\dotnet\shared\microsoft.netcore.app\6.0.14" />
I added this and saw that it obfuscates normally.
However, in .net framework 4.8, this line was not required.

**Comment by lextm** [comment]
Duplicate to #318

**Comment by tomsyc** [comment]
In .NET CORE 6 you can try to add

<AssemblySearchPath path="C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089" />
it works for me
