### ISSUE TITLE
Programatically create xml file on PostBuild with path to assemblies

### ISSUE THREAD

**Issue by CarlosDuranVisionTIR** [obfuscar/obfuscar#415]
Good day,

My solution contains several .NET 6.0 projects (WPF and libraries) and nuget packages. In total, there are more than 60. Configuring a xml file for each with its assembly paths would be hellish.

What I'm trying to achieve: on release post build, create a xml programatically with a console program, and then execute obfuscar with it. While this procedure works, the problem is obfuscar is missing many assembly references (Unable to resolve dependecy: X).

I tried passing the ReferencePaths macro as an argument to the program, but created a command too long to run. 

I then tried to add some paths manually ([PROGRAMFILES]\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.14\ref\net6.0 and [USERS]\[USERNAME]\.nuget\packages), but it seems obfuscator is not able gather the dlls from these folders.

Any suggestions or indications would be appreciated,
Thank you beforehand

**Comment by lextm** [comment]
A solution with >60 projects does not need all of them to be obfuscated separately. You just need to perform obfuscation as the last step of building the actual executable and then I guess you only need a few config files to be manually written.

**Comment by CarlosDuranVisionTIR** [comment]
I understand your point, but on practice I found that when I create an installer with a VS Installer Project, it takes the output from each library project and the output from the wpf project separately, and the bundle them together into an msi. And I don't seem to be able to obfuscate them for example on the installer project prebuild event. That's why the only solution I find is to obfuscate each of them separately. (If I'm wrong or you have a better way please share it)

Nevertheless, I managed to get it working: Even tho there were many many dll references in ReferencePath macro, the folders were actually not that many (3 or 4). So, adding an extra argument to my program to accept these folders and adding them as an assembly reference in the xml configuration file did the trick.

 Thank you!

**Comment by lextm** [comment]
If you ever tried tools like WiX Toolset, probably you would abandon the installer project type. Note that VS itself used WiX for its installer as well.

Obfuscar was not designed to work with the installer project type, and not likely in the future.

**Comment by CarlosDuranVisionTIR** [comment]
Honestly, with all of the troubles and headaches VS has given me, I may just do. Thank you!
