### ISSUE TITLE
Obfuscar not work in dot net 6

### ISSUE THREAD

**Issue by Manshadi1359** [obfuscar/obfuscar#416]
Hi.
I use below config for asp dot net core 6 and not work for me.

<?xml version='1.0'?>
<Obfuscator>

	<AssemblySearchPath path="C:\Users\Manshadi\Desktop\WebApplication1\WebApplication1\bin\Release\net6.0\win-x64" />

	<Var name="InPath" value="." />
	<Var name="OutPath" value=".\Obfuscator_Output" />

	

	<Var name="KeepPublicApi" value="true" />
	<Var name="HidePrivateApi" value="true" />
	<Var name="RenameProperties" value="true" />
	<Var name="RenameEvents" value="true" />
	<Var name="RenameFields" value="true" />
	<Var name="UseUnicodeNames" value="true" />
	<Var name="HideStrings" value="true" />
	<Var name="OptimizeMethods" value="true" />
	<Var name="SuppressIldasm" value="true" />

 	<Module file="$(InPath)\WebApplication1.dll" />

	
</Obfuscator>

**Comment by Manshadi1359** [comment]
I added below tag to csproj file file and it work fine 

<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="&quot;$(Obfuscar)&quot; obfuscar.xml" />
	</Target>

**Comment by lextm** [comment]
Thanks for sharing.
