### ISSUE TITLE
obfuscar + .net 7.0

### ISSUE THREAD

**Issue by NomaratheF** [obfuscar/obfuscar#417]
does obfuscar works with .net 7.0 + wpf?
"exited with code 1" doesnt tell anything.

Unable to find assembly:. its there but app cant see it.

**Comment by JulanDeAlb** [comment]
Make obfuscar.xml CopyToOutputDirectory to always or if newer. Thats what helped me

**Comment by navidkhalilian** [comment]
Apparently it works with version 7. But there are several  problems with Microsoft.AspNetCore namespaces.
Unable to resolve dependency:  Microsoft.AspNetCore.Mvc.ViewFeatures

Some nuget package was moved to asp.net core 6 framework and now obfuscar could not be find them.

Any solution?

**Comment by lextm** [comment]
@navidkhalilian this issue is strictly about WPF. For ASP.NET Core issues, please open a new one.

**Comment by PatrickHofman** [comment]
Yes, it does, however you need to supply the SearchPath to the WPF assemblies yourself. And there are some other caveats, for some of them there are already some pull requests.

**Comment by lextm** [comment]
Duplicate to #551
