### ISSUE TITLE
 Dispose method is skipped during obfuscation in .NET Core 1.1 while it works in .NET Core 2.0.

### ISSUE THREAD

**Issue by MalleshGS** [obfuscar/obfuscar#422]
I am using the latest version of obfuscar , and created a test app to check the obfuscation.
I am using  Stream class and used IDisposable interface for some of the classes to test the behaviour . but when i saw the mapping file , i have seen the difference wrt [.Netcore1.1 and Netcore2.0] mapping files.

.NetCore1.1:

`[ObfuscarTestApp]ObfuscarTestApp.TestStream::Dispose[1]( [System.Runtime]System.Boolean ) skipped:  external base class or interface`

.NetCore2.0:

`[ObfuscarTestApp]ObfuscarTestApp.TestStream::Dispose[1]( [System.Runtime]System.Boolean ) -> a`

XML file  :

```
<?xml version='1.0'?>
<Obfuscator>
  <!--<Var name="InPath" value=".\bin\Debug\netcoreapp1.1" />
  <Var name="OutPath" value=".\bin\Obfuscated\netcoreapp1.1" />-->
  <Var name="InPath" value=".\bin\Debug\netcoreapp2.0" />
  <Var name="OutPath" value=".\bin\Obfuscated\netcoreapp2.0" />
  <Var name="KeepPublicApi" value="true" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="OptimizedMethods" value="true" />
  <Var name="RegenerateDebugInfo" value="true" />
  <Var name="ReuseNames" value="true" />
  <Var name="SuppressIldasm" value="true" />
  <Var name="HideStrings" value="false" />
  <Module file="$(InPath)\ObfuscarTestApp.dll">
  </Module>
</Obfuscator>
```

**Comment by lextm** [comment]
Deprecated platforms are not supported.

**Comment by MalleshGS** [comment]
@lextm , ok thank you , but does this causes memory leak issues , i am seeing some leakages in my application while running with .Net-core 2.0 , but for .Net-core 1.1 there is no memory leak observed.
