### ISSUE TITLE
gitversion error 

### ISSUE THREAD

**Issue by modz2014** [obfuscar/obfuscar#423]
hi im not sure what the go is with this error Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""C:\Users\J\.nuget\packages\gitversion.msbuild\5.11.1\tools\net48/gitversion.exe" "C:\Users\J\Downloads\obfuscar-master\Console"  -output file -outputfile obj\gitversion.json" exited with code 1.	Obfuscar.Console		gitversion work s though so i dont know

**Comment by lextm** [comment]
https://gitversion.net/docs/reference/requirements#repository

This repo uses GitVersion. So, if you want to compile the source code successfully you need to do a full clone, but just download the ZIP package from GItHub.

**Comment by modz2014** [comment]
i tried both and still get same error

**Comment by lextm** [comment]
It is impossible to get "the same error" when you use Git clone (at least the file path and error message should change).

Without further information on what exactly happened after you switched, no assistance can be provided.
