### ISSUE TITLE
Global Tools not working for ASP.NET Core 5.0 app (Obfuscation under Linux)

### ISSUE THREAD

**Issue by jonhucs** [obfuscar/obfuscar#424]
On windows the obfuscation within my build process is working correctly.
<PostBuildEvent>"$(Obfuscar)" obfuscar.xml</PostBuildEvent>

I got the problem, that i want to use the Obfuscar.Console.exe within a Linux Docker container, which doesn't work as expected.
Instead of the normal obfuscar nuget package i saw in solved issues section, that i should use the Global Tools to fix this problem.
But when i tryed to install the newest version of the Global Tools nuget package, i got the message that my project does not have the package type "DotnetTool", so i can't use it this way.
 
I also tried to just use the executable instead, which works in windows too.
<PostBuildEvent>Obfuscar.Console.exe obfuscar.xml</PostBuildEvent>

To execute the executable file within the Linux Docker container, i wanted to use wine, where i got the following error: 0009:err:file:init_redirects cannot open L"C:\\windows" (c000000f). 
<PostBuildEvent>wine Obfuscar.Console.exe obfuscar.xml</PostBuildEvent>

Does anyone knows a possible way to obfuscate my ASP.NET Core 5.0 app with Obfuscar when i need to use a Linux OS?

**Comment by lextm** [comment]
.NET 5 support was removed in Nov 2022. You will have to upgrade to .NET 6 and then use the Global Tool version of Obfuscar.

**Comment by jonhucs** [comment]
Is .NET 7 supported too?

**Comment by jonhucs** [comment]
> .NET 5 support was removed in Nov 2022. You will have to upgrade to .NET 6 and then use the Global Tool version of Obfuscar.

I get the following error in my asp .net project, after i updated to net6.0. I also tried net7.0 too. 

Error NU1202 The package Obfuscar.GlobalTool 2.2.37 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). The package Obfuscar.GlobalTool 2.2.37 supports the following:
  - net6.0 (.NETCoreApp,Version=v6.0)/any
  - net7.0 (.NETCoreApp,Version=v7.0)/any

**Comment by qq362220083** [comment]
I also have this issue.
Is there any new progress on this issue?

.NET 7 compile on Docker

![image](https://github.com/obfuscar/obfuscar/assets/7076606/488c6178-c445-46d7-b012-07aea4588fdd)
![image](https://github.com/obfuscar/obfuscar/assets/7076606/027b0ddd-1de1-41cb-a605-bba1cc0a3ae6)
