### ISSUE TITLE
How to obfusar only confuse method names without confusing implementations in methods

### ISSUE THREAD

**Issue by Tony-Peteryu** [obfuscar/obfuscar#425]
Using a route attribute to implement routing configuration, using an [Action] token token in the configuration, the corresponding route cannot be found after confusion. Therefore, I want to skip the confusion of method names, but I do not want to skip the confusion of method implementations. The corresponding configuration was not found in the provided documentation

example
~~~C#
[Route("api/[Controller]/[Action]")]
public class HomeController : Controller
{
    
}
~~~

**Comment by lextm** [comment]
Obfuscar in general does not modify implementations of methods, as that can change the logic of your program or introduce hard-to-track issues. That's why the documentation doesn't even talk about that.
