### ISSUE TITLE
how to configure obfuscar for complex project setup

### ISSUE THREAD

**Issue by gertvranken** [obfuscar/obfuscar#426]
Hi,

We would like to use obfuscar for our 4.6.1 .NET windows solution.

The solution consists of several projects.

3 'executable' projects P1, P2, P3
several library projects L1, L2, ... L N
several test projects (using the library projects L)

The projects P have several dependencies to library projects Lx.
The L projects are shared for the projects P.

We would like to obfuscate the full solution (the 3 projects P) but do not know how to setup the configuration.
Do we setup an obfuscar xml file for the 3 projects? And which modules do we specify?
We would like to configure KeepPublicApi option to false (to gain more obfuscation).
Do we also need to setup an obfuscar.xml for the library projects?

How can we guarantee that the right obfuscated APIs are used from the projects P ?

Can you please give us some guideline?

Thanks in advance.

Regards

**Comment by lextm** [comment]
Try and come back with more specific questions. Clearly some of them above can be answered by yourself through simple experiments.

**Comment by gertvranken** [comment]
Hi, we experimented a lot yet with obfuscar. Still not clear how to configure the obfuscar.xml and on which projects (application projects or library projects). We started with the library projects and applied also obfuscation on the public API, but then, how get the client projects to know the obfuscated interface?
