### ISSUE TITLE
Obfuscar breaks Task<JObject>

### ISSUE THREAD

**Issue by Yehh22** [obfuscar/obfuscar#427]
Obfuscar breaks Task<JObject> even tho I skipped everything. Skipped renames, skipped properties, skipped string obfuscation... yet it still does something with JObject

Original
```
await LIB.page.Client.SendAsync("Page.setDownloadBehavior", new
{
	behavior = "allow",
	downloadPath = Path.GetDirectoryName(libPath)
}, true);
```

Obfuscar
```
await LIB.page.Client.SendAsync("Page.setDownloadBehavior", new A<string, string>("allow", Path.GetDirectoryName(libPath)), true);
```

This causes the following error:
`PuppeteerSharp.MessageException: Protocol error (Page.setDownloadBehavior): Invalid parameters Failed to deserialize params.behavior - BINDINGS: mandatory field missing at position 8`

**Comment by lextm** [comment]
Duplicate to #130. You might try the solution there.
