### ISSUE TITLE
No documentation for generating obfuscated exe App file

### ISSUE THREAD

**Issue by livan3li** [obfuscar/obfuscar#429]
hi, i couldn't find any documentation step by step for generating obfuscated exe application file. Though, i found documentation how to set configuration and settings up but no explanation anywhere on official web site to obtain/build obfuscated exe file.

Can you help? Thanks.

**Comment by lextm** [comment]
https://github.com/obfuscar/example

**Comment by livan3li** [comment]
i found it later on but i was not explaning that the obfuscar.console.exe lives in packages/tools/ under project folder. I've found by searching. 

After all, i tried to obfucate and it couldn't do it. After obfuscation application doest start and i tried to decompile by dotPeek so that i can know whats going on and it decompiled back. 
And as a result what i see is as much as my understanding there is bunch of bug such as;

1.  There were same variable names that actualy was different. Obfucar named some different variables/fields/properties as same one name.
2. Some variables were starting with numbers?
3. you can see them below image. 
![img1433](https://github.com/obfuscar/obfuscar/assets/46044710/38ecf969-aa5c-40f9-ac04-003fb386789a)
a image about these below .
