### ISSUE TITLE
Same variable names for different ones.

### ISSUE THREAD

**Issue by livan3li** [obfuscar/obfuscar#430]
Hi i've tried to obfuscate and found some bugs. After obfuscation application doest start and i tried to decompile by dotPeek so that i can know whats going on and it decompiled back. 
And as a result what i see is as much as my understanding there is bunch of bug such as;

1.  There were same variable names that actualy was different. Obfucar named some different variables/fields/properties as same one name.
2. Some variables were starting with numbers?
3. you can see them below image. 
![img1433](https://github.com/obfuscar/obfuscar/assets/46044710/38ecf969-aa5c-40f9-ac04-003fb386789a)

**Comment by lextm** [comment]
That's exactly what obfuscation means.
