### ISSUE TITLE
Dot Net 7.0 dependency

### ISSUE THREAD

**Issue by navidkhalilian** [obfuscar/obfuscar#431]
Apparently it works with version 7. But there are several  problems with Microsoft.AspNetCore namespaces.
Unable to resolve dependency:  Microsoft.AspNetCore.Mvc.ViewFeatures

Some nuget package was moved to asp.net core 6 framework and now obfuscar could not be find them.

Any solution?
Thanks

**Comment by lextm** [comment]
Duplicate to #357. For ASP.NET Core 7, the path should be something like `C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\7.0.5\ref\net7.0`.
