### ISSUE TITLE
Use obfuscated DLL in PublishSingleFile

### ISSUE THREAD

**Issue by OssieFromDK** [obfuscar/obfuscar#437]
Hello,

I'm trying to obfuscate my .NET Core 6 WPF Project with Obfuscar, and I'm having some trouble, when I build the project with the following command from CMD: `dotnet publish -r win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true` I get the <projectname>.dll in the /Obfuscater_Output folder and my <projectname>.exe in the /publish folder. I need the .dll to be embedded within the .exe, how would I manage that, I tried adding the Module file in the obfuscater.xml to the .exe, but that didn't work, and I got the https://docs.obfuscar.com/support/faq#how-to-troubleshoot-badimageformatexception error.

So how would I manage to have the .dll obfuscated and embedded within the .exe?

Thanks

**Comment by lextm** [comment]
Duplicate to #301

**Comment by OssieFromDK** [comment]
Oh, I didn't notice, thanks :)

**Comment by dabalciunas** [comment]
See this answer in Stackoverflow:
[How to use Obfuscar in the publish process of .NET Applications](https://stackoverflow.com/questions/69973447/how-to-use-obfuscar-in-the-publish-process-of-net-applications)
