### ISSUE TITLE
.net webapi configuration rules

### ISSUE THREAD

**Issue by zeroonestring** [obfuscar/obfuscar#440]
.net webapi use this configuration
```
<Var name="KeepPublicApi" value="false" />
<Var name="HidePrivateApi" value="true" />
```

This configuration can confuse the class name, but the route name will change and the program will run incorrectly 
I want to confuse the class names and ensure that the program runs normally 
How to configure it?

**Comment by lextm** [comment]
You cannot obfuscate many types, as the ASP.NET framework itself uses reflection and needs those names to remain,

https://docs.obfuscar.com/support/faq#how-to-troubleshoot-typeloadexception-during-reflection
