### ISSUE TITLE
Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve System.IO.SearchOption

### ISSUE THREAD

**Issue by SanjivPossible** [obfuscar/obfuscar#441]
I'm using .NET 7 to build a Windows desktop app, and I'm using 2.2.38 version to obfuscate the assembly, however, I'm getting the exception :

1>Loading assemblies...Extra framework folders: Done.
1>Hiding strings...
1>Renaming:  fields...Parameters...Properties...Events...Methods...Types...Done.
1>
1>Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve System.IO.SearchOption
1>   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
1>   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
1>   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
1>   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
1>   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildModule()
1>   at Mono.Cecil.MetadataBuilder.BuildMetadata()
1>   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
1>   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
1>   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Obfuscar.Obfuscator.SaveAssemblies(Boolean throwException)
1>   at Obfuscar.Obfuscator.RunRules()
1>   at Obfuscar.Program.Main(String[] args)
1>Saving assemblies...

**Comment by lextm** [comment]
Duplicate to #390
