### ISSUE TITLE
.Net 5 WPF failed to build if set KeepPublicApi false. 

### ISSUE THREAD

**Issue by ChangyeWei** [obfuscar/obfuscar#442]
I got an error **..\tools\Obfuscar.Console.exe" obfuscar.xml" exited with code -532462766**  if I set KeepPublicApi false. 
It will be success if KeepPublicApi  = true. Any idea why it's fail and what's the -532462766 means.

**Comment by jomNext** [comment]
KeepPublicApi = false will not work on a WPF-App! Tests with dnSpy show me, that the BAML-Resource from Obfuscar not changed. So all Events or Reference to another class broken.

**Comment by lextm** [comment]
@ChangyeWei You need to read https://github.com/obfuscar/obfuscar/issues/397#issuecomment-1343903147 and learn how to reproduce the error with simple commands at command prompt. That will print out more information and tell what's up.

@jomNext https://docs.obfuscar.com/support/faq#how-to-troubleshoot-typeloadexception-during-reflection Known issue for WPF.

**Comment by lextm** [comment]
Duplicate to #551
