### ISSUE TITLE
Error when using obfuscar

### ISSUE THREAD

**Issue by Ghostfire08** [obfuscar/obfuscar#443]
i'm writing a program in C# in Visual Studio 2022 and I need to obfuscate this project. I installed the Obfuscar package via NuGet and created a file (obfuscar.xml) in my project and added this code there:

`
<Obfuscator>
    <Var name="InPath" value="."/>
    <Var name="OutPath" value="Obfuscator"/>

    <Var name="RenameProperties" value="true"/>
    <Var name="RenameEvents" value="true"/>
    <Var name="RenameFields" value="true"/>
    <Var name="KeepPublicApi" value="false"/>
    <Var name="HidePrivateApi" value="true"/>
    <Var name="UseUnicodeNames" value="true"/>
    <Var name="HideStrings" value="true"/>
    <Var name="OptimizeMethods" value="true"/>
    <Var name="SuppressIldasm" value="true"/>

    <Module file="$(InPath)\File.exe" />
</Obfuscator>
`

and also in the "Build Events" of this file I entered this text:
`
if $(ConfigurationName) == Release "$Obfuscar" ....\obfuscar.xml
`

I have an error in my output:
`
""$Obfuscar"" is not internal or external 1> command, executable program, or batch file.

C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5760,5): error MSB3073: leaving the team "if Release == Release "$Obfuscar" ....\obuscar.xml" with code 9009.
`

How can I properly obfuscate this code?

**Comment by lextm** [comment]
You didn't use the right MSBuild syntax, so those errors are expected. You might take a look at our example repo to see what the right approach might be, https://github.com/obfuscar/example But you need to learn more about MSBuild if you want more advanced setup.
