### ISSUE TITLE
Not working for ASP.NET 7.0 app (Obfuscation under Linux or Docker)

### ISSUE THREAD

**Issue by qq362220083** [obfuscar/obfuscar#444]
Hi, I also have this problem #424 .

Is there any new progress on this issue? Thank you.

.NET 7 compile on Docker

![image](https://github.com/obfuscar/obfuscar/assets/7076606/488c6178-c445-46d7-b012-07aea4588fdd)
![image](https://github.com/obfuscar/obfuscar/assets/7076606/027b0ddd-1de1-41cb-a605-bba1cc0a3ae6)

**Comment by lextm** [comment]
.NET projects should use the Global Tool instead.

**Comment by qq362220083** [comment]
Dockerfile:
```Dockerfile
RUN dotnet tool install --global Obfuscar.GlobalTool
RUN export PATH="\$PATH:/root/.dotnet/tools" && obfuscar.console obfuscar.xml
```
