### ISSUE TITLE
Feature suggestion: cross-solution public api renaming

### ISSUE THREAD

**Issue by moltco** [obfuscar/obfuscar#446]
Thank you for developing Obfuscar and keeping it alive! I have a feature suggestion that I wanted to share.

I have a solution with several projects that are all interlinked. The projects are used exclusively within the solution so having a "public API" does not have any value outside of the solution. In the current per-project deployment of Obfuscar, to preserve calls between cross-project libraries I need to keep the public API as-is, without obfuscation. This is not great as a large portion of code remains not obfuscated.

I was wondering if obfuscar could work across the solution, and in this mode have an option to cross-map public API between projects. This would allow public methods to be renamed (obfuscated) and the correct reference to be placed in another project that is consuming that method. I noticed Obfuscar already maintains a Mapping.txt file so it feels viable that this could be implemented. 

I think this would be a great feature and would improve protection greatly; I hope others will find this feature useful too.

**Comment by lextm** [comment]
While feature requests are welcome, I am writing to see if you consider existing alternatives.

Visual Studio 2019 and above has solution filtering, so that instead of maintaining multiple solutions you can just keep one,

https://learn.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2019

And then inside a solution, you can have multiple configuration files on different projects (for example, the library and the top executable) so that you can perform different obfuscation processes for different goals (keeping public API surface or not). The results are totally up to you.

**Comment by moltco** [comment]
Hi, thanks for suggestion but I was actually flagging another issue.

So, within one VS solution there are multiple projects - let's say one is exe and others are dependencies - class libraries/DLL. Let's assume that the DLLs are used exclusively in our exe. There are no other exe's needing to reference these DLLs, eg no third party apps need or DLLs.

What happens in the standard scenario (the one you described above) is that all methods marked as 'public' in DLLs will retain their original name so that exe can reference these names. This is sort of OK if you plan to use the same dll with multiple EXEs of which some may be third party apps. 

But if your exe and dll are not really public / to be used by other apps then Obfuscar could rename even public methods in such DLLs and insert obfuscated names in the (dependant) exe as they are part of the same solution. 

This way you get much stronger obfuscation in real-world projects/solutions. Most class libraries are used internally within the solution and are not designed for this party access so their public API could be obfuscated without breaking the exe in the solution that sits on top of DLLs.

**Comment by lextm** [comment]
> What happens in the standard scenario (the one you described above) is that all methods marked as 'public' in DLLs will retain their original name so that exe can reference these names. This is sort of OK if you plan to use the same dll with multiple EXEs of which some may be third party apps.
> 
> But if your exe and dll are not really public / to be used by other apps then Obfuscar could rename even public methods in such DLLs and insert obfuscated names in the (dependant) exe as they are part of the same solution.

I wonder if you have tried out the basic configuration documented in https://docs.obfuscar.com/getting-started/configuration#keeppublicapi-and-hideprivateapi, as obfuscating everything is no doubt a supported scenario since 2.2.0.

**Comment by moltco** [comment]
I have tried it and it broke the exe as soon as any dll was called. I will play with it a little longer, perhaps I did something wrong.

Should I obfuscate individual DLL projects or the final output of the solution (ie Exe and DLLs once they are copied in the final Release folder)? I did the latter as test and it broke the exe at first dll call.

**Comment by lextm** [comment]
You will have to define what is "it broke the exe". Any obfuscation tool can prevent your app from running in certain scenarios, so you do need to review the documentation carefully,

https://docs.obfuscar.com/support/faq#how-to-troubleshoot-typeloadexception-during-reflection

You can purchase commercial support if that's what you want.

https://support.lextudio.com/services/consulting#
