### ISSUE TITLE
net 8 and blazor server side ?

### ISSUE THREAD

**Issue by stoora** [obfuscar/obfuscar#449]
Can I obfuscate a net 8 blazor ssr code?
In my case the server will be distributed and run on the client machine.
Obfuscating only one class will do for me.

**Comment by lextm** [comment]
There can be quite a few issues if you obfuscate classes that must be resolved by names at runtime,

https://docs.lextudio.com/obfuscar/support/faq#how-to-troubleshoot-typeloadexception-during-reflection
