### ISSUE TITLE
Is it possible to loop over subfloders for AssemblySearchPath

### ISSUE THREAD

**Issue by NikoCat233** [obfuscar/obfuscar#450]
My project uses huge nupackages references, and I cant afford to add them into AssemblySearchPath one by one
Is there a way to include a single path and also its sub folders to search for Assembly reference?

GPT told me to use this but it never works
<img width="292" alt="image" src="https://github.com/obfuscar/obfuscar/assets/139348239/dd036f6d-94ac-4a10-a610-a2e5f8ac8f5c">

**Comment by lextm** [comment]
This was brought up in the past several times, but no plan to implement it.

You can write your own script to generate the config file on the fly where the loop can be inside your own script, not Obfuscar itself.
