### ISSUE TITLE
Different configuration for each module

### ISSUE THREAD

**Issue by MichaelSvejcar** [obfuscar/obfuscar#451]
Hello,

my app consists of multiple projects, that have dependencies on each other.
Is it possible to set Obfuscar in such a way, so that for each of these projects, Obfuscar will use different settings (different level of obfuscation), while still keeping the dependencies between those project working in the output?

So far, I have tried setting the **KeepPublicApi** and **HidePrivateApi** different for each < module > specified in the obfuscar.xml settings file, where each <module> is referring to dll of one project. However, after examining the output in DotPeek, it looks like that the same setting, defined at the top level of the xml file, gets used for every module, regardless how the parameters are set under it's xml node.

Is there some way to achieve what I am describing, or is using different obfuscation settings for each module not possible at this time?

Thank you,
wish you nice Christmas holidays!

**Comment by lextm** [comment]
You might try to give each project a different configuration file to control obfuscation settings.

Just don't put everything in a single configuration file with the main executable, as that's not supported.
