### ISSUE TITLE
Obfuscation results are differents if you build from VS2022 or from MSBuild (2022)

### ISSUE THREAD

**Issue by stephane-laurans** [obfuscar/obfuscar#453]
I have been working for a few days on the migration of a .csproj project from the old format to the new one using the sdk(<Project Sdk="Microsoft.NET.Sdk">) which uses Obfuscar.

I'm having a problem with obfuscation when I do it using MsBuild. This works great since Vs2022 but when I integrate the compilation into my delivery script, the obfuscation results are different.

While with Visual Studio 2022, the Winforms resources are well obfuscated, it is not the same with the MsBuild compilation.

MSBUILD obfuscation
![image](https://github.com/obfuscar/obfuscar/assets/10567051/44efc9f5-78f1-4a94-af4b-70c17eff0f49)

VS2022 obfuscation
![image](https://github.com/obfuscar/obfuscar/assets/10567051/a4bb837e-0d32-4fec-8f09-fe3b720598fd)

In both cases, there is no error in build log.

**Comment by lextm** [comment]
You need to explain what exactly you meant by "when I do it using MsBuild". How does the .csproj file look like?
