### ISSUE TITLE
How to package a ipa after obfusca ?

### ISSUE THREAD

**Issue by dingxiaolong** [obfuscar/obfuscar#456]
Dear 
     I am try to using this lib to obfusca my dotnet6.iOS project .
I can do it with this "obfuscar.console Obfuscar.xml".     
![image](https://github.com/obfuscar/obfuscar/assets/21192107/267c9920-3a78-4966-9029-cf5145a03d21)

This can generate a new dll, (On mac ,I don't find the exe file to obfusca..)

My question is how I can package a ipa file with it ?

I try to replace this dll after generate an ipa ,    but faield.

Could you help check the step please ?

I can't find useful info for the iOS on mac.

Many thanks .

**Comment by lextm** [comment]
Duplicate to #159
