### ISSUE TITLE
Error: "The ' ' character, hexadecimal value 0x2004, cannot be included in a name."

### ISSUE THREAD

**Issue by idenchev** [obfuscar/obfuscar#458]
I am developing a VB app, which depicts statistical information with charts. This app has multiple WinForms for different categories of charts. Each WinForm has the possibility to zoom each user-clicked chart in a bigger version of this same chart displayed in a new WinForm. This is done with XML serialization. My problem is that when execution reaches following line an exception is thrown "The ' ' character, hexadecimal value 0x2004, cannot be included in a name."
```
parentObject.Serializer.Save(stream)
```
What is interesting is that this exception happens in my complete solution after obfuscation. But if I create a very small project just to simulate the issue there is no problem.

It would be great to know how to work-around this issue? Should I set an exclusion rule in configuration file? I tried several options according to the documentation, but with no luck. What should be the correct syntax for exclusion provided that namespace is "WinFormsApp1", the WinForms class is "Form1" and the method name is "ZoomChartInNewWindowToolStripMenuItem_Click"?

Below is the code of "ZoomChartInNewWindowToolStripMenuItem_Click". After user right clicks on a chart there is toolstrip menu from which user clicks on "Zoom Chart" item. The the Sub is called, which detects which chart was clicked, then the chart is saved as stream with serialization and finally this stream is loaded on the zoomed chart in a new WinForm.
```
Public Class Form1
    Private Sub ZoomChartInNewWindowToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles ZoomChartInNewWindowToolStripMenuItem.Click

        Dim myItem As ToolStripMenuItem = CType(sender, ToolStripMenuItem)
        Dim cms As ContextMenuStrip = CType(myItem.Owner, ContextMenuStrip)

        Dim parentObject As New Windows.Forms.DataVisualization.Charting.Chart

        Try
            parentObject = CType(Me.Controls.Find(cms.SourceControl.Name, True)(0), Windows.Forms.DataVisualization.Charting.Chart)
        Catch ex As Exception

        End Try

        Dim stream As New System.IO.MemoryStream
        parentObject.Serializer.Save(stream)

        Form2.Chart600.Serializer.Load(stream)
        Form2.enlarge(500, 600)
        Form2.Show()

    End Sub
End Class
```
Part of the exception thrown by my app is following:
```
...
at System.Windows.Forms.DataVisualization.Charting.Utilities.XmlFormatSerializer.SerializeObject(Object objectToSerialize, Object parent, String elementName, XmlNode xmlParentNode, XmlDocument xmlDocument)
   at System.Windows.Forms.DataVisualization.Charting.Utilities.XmlFormatSerializer.Serialize(Object objectToSerialize, Object writer)
   at System.Windows.Forms.DataVisualization.Charting.ChartSerializer.Save(Stream stream)
   at  .•.․(Object, EventArgs)
```

**Comment by lextm** [comment]
You might have read from the documentation that issues like that are expected in many scenarios,

https://docs.obfuscar.com/support/faq#id8

We did keep a few examples on how to use skip rules when we wrote the unit test cases, https://github.com/obfuscar/obfuscar/tree/2.2.38/Tests

**Comment by idenchev** [comment]
I forgot to mention that obfuscation process finishes without any issues. The exception happens during execution of obfuscated code. Most of my software, which is quite big works properly, but only the mentioned function cannot be executed due to this exception. If I create a simple project with just this function there are no issues after obfuscation. But in the main project the problem is laways there. I cannot figure out what exactly is wrong, why only in this function and why only in the big project. Again I am posting the exception text. I can't find the exact object, which is renamed. Probably this will be possible with the mapping file provided that normal characters/string could be used for obfuscation (don't know if this is possible, I tried with unicode and korean) and if replacing is not repeated (this is possible).
```
System.Xml.XmlException: The ' ' character, hexadecimal value 0x2004, cannot be included in a name.
   at System.Xml.XmlDocument.CheckName(String name)
   at System.Xml.XmlElement..ctor(XmlName name, Boolean empty, XmlDocument doc)
   at System.Xml.XmlDocument.CreateElement(String prefix, String localName, String namespaceURI)
   at System.Xml.XmlDocument.CreateElement(String name)
   at System.Windows.Forms.DataVisualization.Charting.Utilities.XmlFormatSerializer.SerializeObject(Object objectToSerialize, Object parent, String elementName, XmlNode xmlParentNode, XmlDocument xmlDocument)
   at System.Windows.Forms.DataVisualization.Charting.Utilities.XmlFormatSerializer.Serialize(Object objectToSerialize, Object writer)
   at System.Windows.Forms.DataVisualization.Charting.ChartSerializer.Save(Stream stream)
   at  .―. (Object, EventArgs)
```
In the last line the first character is probably the hex 0x2004 character and I assume there stays the name of the Namespace, but I can't force renaming not to happen only for the name and not for everything else in the namespace.

**Comment by lextm** [comment]
The FAQ section explains that certain parts of .NET simply don't work well with obfuscation.

This applies to other obfuscation tools as well, so we are unable to provide any additional assistance. 

You have to identify and exclude the relevant code from obfuscation.

**Comment by idenchev** [comment]
Solution was found. Apparently the XML Serializer was not accepting as name the ghost unicode symbols without graphical representation. What solved the problem was the Korean names in configuration file:
```
<Var name="UseKoreanNames" value="true" />
```
Setting the ```ReuseNames``` to false was irrelevant to my issue and didn't help.
