### ISSUE TITLE
Unable to regenerate debug info

### ISSUE THREAD

**Issue by vchelamkuri** [obfuscar/obfuscar#459]
On Windows, I'm trying to use `Obfuscar.Console.exe` to generate obfuscated assembly, and I have also set `RegenerateDebugInfo` to true in the input xml file. The input .pdb file is present alongside the input .dll file.

It successfully obfuscates the input assembly, but it generates an empty .pdb file (203 KB in size) which does not have any symbols in it. 

Inspecting the generated .pdb file using [cvdump.exe](https://github.com/microsoft/microsoft-pdb/blob/master/cvdump/cvdump.exe) just displays the following information and nothing else:

```
Microsoft (R) Debugging Information Dumper  Version 14.00.23611
Copyright (C) Microsoft Corporation.  All rights reserved.
```

Why is the debug info not getting regenerated? Am I missing something in the configuration?

Here is my input XML file:

```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value="." />
  <Var name="OutPath" value=".\ObfuscarOutput" />
  <Var name="KeepPublicApi" value="true" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="KeyFile" value="<path to .snk file>" />
  <Var name="RegenerateDebugInfo" value="true" />
  <AssemblySearchPath path="<referenced assembly search path>" />

  <Module file="<assembly name>" />
</Obfuscator>

```

**Comment by vchelamkuri** [comment]
It successfully generates a non-empty .pdb file if I delete the `windir` environment variable.

But should I delete that env var? Shouldn't it generate the right .pdb file even that that env var is set?

**Comment by lextm** [comment]
The actual symbol generation is done by Mono Cecil and its dependencies (Windows PDB API). So it's not possible to get an answer on your question from this repo.

**Comment by vchelamkuri** [comment]
I think the problem is in line 210 in Obfuscator.cs:

https://github.com/obfuscar/obfuscar/blob/master/Obfuscar/Obfuscator.cs

If I flip the `if` condition (i.e., change it to `if (!IsOnWindows)`), then it successfully generates the PDB file on Windows.
