### ISSUE TITLE
E_INVALIDARG 0x80070057 at VS2022 with .NET 6.0

### ISSUE THREAD

**Issue by MarCsharpElo** [obfuscar/obfuscar#460]
hi guys,

i installed the tool V1.2.0 into VS 2022 on Win10 Pro, the tool was installed succesfully.

i have more projecst into the solution i.e WPF, C# Libraries, WPF Libraries, i'm using .NET 6.0
after press the menu item Tools > Protected Using Obfuscar propmt the Window Error Message Box, i tried with all projects, prompt the saem error at all projects.

Wrong parameter Exception HResult E_INVALIDARG 0x80070057

could you help me

**Comment by lextm** [comment]
There is no V1.2.0 from this repo. You probably use another tool and should report to its authors.
