### ISSUE TITLE
Some string can't hide?

### ISSUE THREAD

**Issue by dangdkhanh** [obfuscar/obfuscar#461]
Hi,
Is it possible to hide the names of dllimports?
I have declared hidden variables and method names hidden but they are still displayed.
Do I need to find the right assemblypath?

![image](https://github.com/obfuscar/obfuscar/assets/99936463/ff21e800-6ba3-4366-9a68-3d645d2d598c)

Thanks you!

**Comment by lextm** [comment]
No plan to investigate further on such.

Pull requests are welcome.
