### ISSUE TITLE
how to obfuscate multi-projects togather

### ISSUE THREAD

**Issue by sijiehudragonplus** [obfuscar/obfuscar#462]
``i got a sln with many class library projects, and different project are referenced each.
for example: A project referenced B & C, B referenced C.
i want obfuscate them togather, now i created a project referenced all of them, and add \<PostBuildEvent>mono "$(Obfuscar)" obfuscar.xml\</PostBuildEvent> to this project.
but it dosen't work. because different project dll api are renamed to an same name.
also, i want to obfuscate everthing, include public API or types.
```html
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value="." />
  <Var name="OutPath" value="./Output1" />
  <Var name="KeyFile" value="./key.snk" />
  <Var name="RenameProperties" value="true"/>
  <Var name="RenameEvents" value="true"/>
  <Var name="RenameFields" value="true"/>
  <Var name="KeepPublicApi" value="false"/>
  <Var name="HidePrivateApi" value="true" />
  <Var name="HideStrings" value="true"/>
  <Var name="ReuseNames" value="true"/>
  <Var name="UseKoreanNames" value="false"/>
  <Var name="OptimizeMethods" value="true"/>

  <Module file="$(InPath)/ClassLibrary1.dll" />
  <Module file="$(InPath)/ClassLibrary2.dll" />
  <Module file="$(InPath)/ConsoleApplication1.exe" />
</Obfuscator>

``` 

and my test sln after obfuscate is like this
-ClassLibrary1
--Class1.cs => obfuscated to A
---DoClass1() => obfuscated to A
-ClassLibrary2
--Class2.cs => obfuscated to A
---DoClass2() => obfuscated to A
-ConsoleApplication1 (using ClassLibrary1 & ClassLibrary2) and i call obfuscate after this project build
--Program.cs => i skiped this
---Main(string[] args)
`{new Class1().DoClass1();  new Class2().DoClass2();}`
after obfuscated, it became =>
`{new A().A(); newA().A();}`

i think maybe obfuscar dosen't consider different dll togather, so made them same name, how can i tell obfuscar to obfuscate them togather?

**Comment by Ashokkumar-RV** [comment]
For single assembly :
```
<Module file="$(InPath)Lean.Wrapper.Core.dll">
                  ....
</Module>
```

For multiple assemblies:
[in version-2.2.33](https://github.com/obfuscar/obfuscar/pull/254#issuecomment-581113846)
```
<Modules>    // NOTE: plural 
          <IncludeFiles>"$(InPath)Lean.CRM.dll"</IncludeFiles>
          <ExcludeFiles>$(InPath)\Lean.*.Tests.dll</ExcludeFiles>
          ...
</Modules>
```

**Comment by sijiehudragonplus** [comment]
i know why, my misstake, it workd by set  `<Var name="UseKoreanNames" value="false"/>` to flase.

but now i got another exception : 
`[ERROR] FATAL UNHANDLED EXCEPTION: Mono.Cecil.ResolutionException: Failed to resolve B.m`

**Comment by lextm** [comment]
The sample repo already  how to obfuscate multiple projects together.
