### ISSUE TITLE
Is Obfuscar.Console.exe supposed to be ran on Windows only?

### ISSUE THREAD

**Issue by sadomovalex** [obfuscar/obfuscar#463]
There is Obfuscar.Console.exe tool which is included to Obfuscar nuget package (under /tools) and can be used in build pipeline. In [Obfuscar.Console.csproj](https://github.com/obfuscar/obfuscar/blob/master/Console/Obfuscar.Console.csproj) file it currently targets only .Net Framework 4.6.2:
```
<TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
```
Does it mean that it is supposed to be run only on Windows or I missed something? (i.e. it is not possible to use it when build on Linux or inside Docker)

**Comment by lextm** [comment]
Please use the Global Tool with .NET SDK.
