### ISSUE TITLE
Can you use the name of the build configuration in the Obfuscar XML?

### ISSUE THREAD

**Issue by brinkdinges** [obfuscar/obfuscar#464]
I'm adding a third build configuration to my .NET Framework project, next to Debug and Release. I would like the files to be obfuscated in this configuration, without having to add a nearly identical XML configuration file. Is it possible to use the configuration name as a parameter in the XML?

My attempts:
- Adding the ConfigurationName parameter to the XML. This does not work.
![image](https://github.com/obfuscar/obfuscar/assets/15387410/9c629d4d-7714-433c-9b4b-5d267f95ee18)
- Adding the configuration name as a command line argument. But Obfuscar only accepts the XML path as the only argument.

I could create a nearly identical configuration file, but I'd like to avoid it if I can.

**Comment by lextm** [comment]
Please use MSBuild tasks to generate/manipulate the configuration on the fly, before calling Obfuscar. That literally achieves the same.
