### ISSUE TITLE
WPF applicatio stop working after the code obfuscation by obfuscar

### ISSUE THREAD

**Issue by liangming2003** [obfuscar/obfuscar#465]
I have a WPF application which displays Windows system information on a window. After run the ""$(Obfuscar)" obfuscar.xml", the application cannot get all the system information.

The application's target framework is .Net Framework 4.8.1.

`<TargetFrameworkVersion>v4.8.1</TargetFrameworkVersion>`

Obfuscar version: .2.2.38

obfuscar.xml:
```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value="." />
  <Var name="OutPath" value=".\Obfuscator_Output" />
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="HideStrings" value="false" />
  <Var name="OptimizeMethods" value="false" />
  <Var name="SuppressIldasm" value="false" />
 
  <Module file="$(InPath)\WindowsSysInfo.exe" />
</Obfuscator>
```

Here is the code example to get the IP address that stop working after obfuscation:

View:
`<TextBlock Grid.Row="12" Grid.Column="1" TextWrapping="Wrap" Text="{Binding IPAddresses}" Margin="2" HorizontalAlignment="Left" VerticalAlignment="Top"/>`

Model:
`
public IList<string> LstIPAddresses { get; set; }`

ViewModel:
```
strBuilder.Clear();
int ipCount = sysInfo.LstIPAddresses.Count;
if (ipCount > 0)
    strBuilder.Append(sysInfo.LstIPAddresses[0]);
i = 1;
while (i < ipCount)
{
    strBuilder.Append(Environment.NewLine + sysInfo.LstIPAddresses[i]);
    ++i;
}
IPAddresses = strBuilder.ToString();
```

DataAccess:

 ```
 public static IList<string> GetIPAddress()
  {
      List<string> lstIPs = new List<string>();
      IPAddress[] ips = null;
      try
      {
          ips = Dns.GetHostAddresses(Dns.GetHostName());
      }
      catch (Exception ex)
      {
          Debug.Assert(false, "SystemInfoWMIDataLayer::GetIPAddress() failed");
          throw ex;
      }
      if (ips != null)
      {
          foreach (IPAddress ip in ips)
          {
              lstIPs.Add(ip.ToString());
          }
      }

      return lstIPs;
  }
```

**Comment by liangming2003** [comment]
@lextm  Thanks. I also try Obfuscar on a WinUI 3 application, the obfuscation also caused the application failing to launch.
So, I guess Obfuscar does not support WinUi 3 Application either. Could you recommend a obfuscation tool that supports WPF and WinUI 3 application?

**Comment by lextm** [comment]
You might refer to https://docs.lextudio.com/obfuscar/support/faq#how-to-troubleshoot-typeloadexception-during-reflection

There might be obfuscation tools that work well with XAML, but not us to recommend.

**Comment by monty241** [comment]
Similar: 

- https://github.com/invantive/dot-blur/issues/6
- https://github.com/obfuscar/obfuscar/issues/305

**Comment by monty241** [comment]
Patch on Dot Blur with commit b1b86937d093c21f935efc3df57886d80bacb89d in case someone wants to port to Obfuscar.

**Comment by lextm** [comment]
Duplicate to #551
