### ISSUE TITLE
How to donot obfuscar anonymous types?

### ISSUE THREAD

**Issue by jianliulin** [obfuscar/obfuscar#467]
obfuscar.xml

  <Var name="KeepPublicApi" value="true" />
  <Var name="HidePrivateApi" value="true" />  
  <Var name="SkipAnonymous" value="true" /> 
  <SkipType name="*AnonymousType*" skipProperties="true" skipMethods="true" skipFields="true" skipEvents="true" skipStringHiding="true" />

![image](https://github.com/obfuscar/obfuscar/assets/4531974/792b89da-c756-4e1e-b176-731327072e47)

![image](https://github.com/obfuscar/obfuscar/assets/4531974/120f0d07-b61f-42ee-8fc7-858184e7c489)

**Comment by lextm** [comment]
I have no idea what you want to ask, as neither the title nor the screen shots pointed that out clearly.

You might use a modern AI to translate the original question from your native language to English. That usually works better.
