### ISSUE TITLE
obfuscar + .net 7.0 + PublishSingleFile + SignAssembly

### ISSUE THREAD

**Issue by deakintsang** [obfuscar/obfuscar#468]
My solution includes Project A, Project B, Project C, and Project D. After obfuscation with Obfuscar and compiling into a single EXE file, it functions normally. However, upon adding strong names to each project, the generation fails. Why is this happening?

I want to add strong names to each project and implement code obfuscation.

`5>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2401,5): 错误 MSB4018: “ResolveAssemblyReference”任务意外失败。
5>System.Security.SecurityException: Invalid assembly public key. (Exception from HRESULT: 0x8013141E)
5>   在 System.Reflection.AssemblyName.nToString()
5>   在 System.Reflection.AssemblyName.get_FullName()
5>   在 Microsoft.Build.Tasks.ReferenceTable.GetReferenceItems(ITaskItem[]& primaryFiles, ITaskItem[]& dependencyFiles, ITaskItem[]& relatedFiles, ITaskItem[]& satelliteFiles, ITaskItem[]& serializationAssemblyFiles, ITaskItem[]& scatterFiles, ITaskItem[]& copyLocalFiles)
5>   在 Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetRegistrySubKeyNames getRegistrySubKeyNames, GetRegistrySubKeyDefaultValue getRegistrySubKeyDefaultValue, GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, OpenBaseKey openBaseKey, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader)
5>   在 Microsoft.Build.Tasks.ResolveAssemblyReference.Execute()
5>   在 Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
5>   在 Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
5>失败的程序集的区域是:
5>MyComputer`

**Comment by MichaelSvejcar** [comment]
Hello,
how did you make obfuscar work with single file publish?
If I obfuscate files in the bin/release directory, final published exe file still contains non-obfuscated code.

**Comment by lextm** [comment]
Duplicate to #301

**Comment by deakintsang** [comment]
> Hello, how did you make obfuscar work with single file publish? If I obfuscate files in the bin/release directory, final published exe file still contains non-obfuscated code.

copy the obfuscated assemblies

`  <Target Name="CopyObfuscation" AfterTargets="PostBuildEvent" Condition="'$(Configuration)' == 'Release'">
  <Exec Command="COPY $(SolutionDir)OutPath\bin\Release\net8.0-windows7.0\Obfuscar\$(TargetFileName) $(SolutionDir)OutPath\obj\Release\net8.0-windows7.0\win-x86\$(TargetFileName)" />
  <Exec Command="COPY $(SolutionDir)OutPath\bin\Release\net8.0-windows7.0\Obfuscar\Client.Models.dll $(SolutionDir)OutPath\bin\Release\net8.0-windows7.0\Client.Models.dll" />
 
</Target>`

**Comment by dabalciunas** [comment]
See this answer in Stackoverflow:
[How to use Obfuscar in the publish process of .NET Applications](https://stackoverflow.com/questions/69973447/how-to-use-obfuscar-in-the-publish-process-of-net-applications)
