### ISSUE TITLE
Obfuscation does not work

### ISSUE THREAD

**Issue by RubySword** [obfuscar/obfuscar#471]
Good afternoon! I'm trying to protect my build by setting the following parameters:
`<Var name="KeepPublicApi" value="true" />
<Var name="HidePrivateApi" value="true" />
<Var name="HideStrings" value="false" />
<Var name="UseUnicodeNames" value="true" />
<Var name="ReuseNames" value="true" />
<Var name="RenameFields" value="true" />`

But dotPeek64 easily opens the code of my build:
![2024-07-12_16-48-23](https://github.com/user-attachments/assets/6750a2f7-15a0-4b1d-8622-05511b8ae09f)

**Comment by lextm** [comment]
That's what "keepPublicApi" is all about. Besides, the simpler your methods are, the easier decompilers guess out. So what you observed is by design.

**Comment by RubySword** [comment]
Will the protected library work loaded with RTTI in the application?
