### ISSUE TITLE
Avalonia include style

### ISSUE THREAD

**Issue by RubySword** [obfuscar/obfuscar#473]
Good afternoon!
 I'm doing protecting an application written on the Avalonia framework, the style in App.axam is connected to the application: <style include source="avares://MeterTools/styles/light.axaml"/>
When trying to find the requested link, "No precompiled XAML was found for". It is necessary to connect this file separately to Obfuscar.xml ?

**Comment by lextm** [comment]
We have no plan to develop features specific to WPF/UWP/Avalonia and other similar frameworks.

Pull requests are welcome though.

**Comment by lextm** [comment]
Duplicate to #551
