### ISSUE TITLE
Is Obfuscar still maintained?

### ISSUE THREAD

**Issue by joanlofe** [obfuscar/obfuscar#474]
We are planning to use Obfuscar for an important project and I've seen the last commit to the repository was almost a year ago. Is the project still maintained? This is important, because as Microsoft releases new versions of Net new features are added and some may require updating obfuscar to keep up with the progress. We need to know if the project is no longer actively maintained to take the decision of using it or not.

**Comment by lextm** [comment]
It's still being used widely and no report on significant issues with latest .NET releases.

Bug reports and pull requests are welcome.
