### ISSUE TITLE
Control flow obfuscation?

### ISSUE THREAD

**Issue by marss72** [obfuscar/obfuscar#478]
I've been using Obfuscar for my smaller projects now, and it's great, except for one thing, which is like control flow obfuscation.

I don't see any option for that and the obfuscator seems only to rename things (and hide strings), which can be powerful, but not that much. Since Obfuscar is probably one of very few free, open-source, and working obfuscators for the latest .NET, it would be great to see a feature like that. I was considering a pull request, but don't want to mess things up.

So, are there any plans to implement more obfuscation techniques/modules in the future? Thanks!

**Comment by lextm** [comment]
No plan to implement such a feature. But pull requests are welcome.

**Comment by bxjg1987** [comment]
try: https://github.com/dcsoft-yyf/JIEJIE.NET
