### ISSUE TITLE
Obfuscate signed assembly

### ISSUE THREAD

**Issue by marss72** [obfuscar/obfuscar#479]
How do I obfuscate a dependency (dll) like Humanizer? I'm getting `An error occurred during processing:
Obfuscating a signed assembly would result in an invalid assembly:  Humanizer; use the KeyFile or KeyContainer property to set a key to use`, but don't know what to do next (never signed any executable, I have no experience about signed executables)

And is it even a good idea to do this? Thanks.

**Comment by lextm** [comment]
To learn how to sign assemblies, you need to resort to Microsoft docs, https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name

Then to sign the assemblies during obfuscation, use the correct Obfuscar settings, https://docs.lextudio.com/obfuscar/getting-started/configuration#settings
