### ISSUE TITLE
How to Obfuscate a Single-File Avalonia Application

### ISSUE THREAD

**Issue by yangf85** [obfuscar/obfuscar#487]
I am in the process of releasing a small Avalonia application. In release mode, Obfuscar correctly obfuscates the DLL files, and the application runs without issues. However, in single-file publish, the resulting EXE still contains unobfuscated DLLs. Upon inspecting the DLL files in the obj/release directory, I noticed they are not obfuscated.

Does the publish mode inherently use these unobfuscated DLLs? Despite searching through existing issues, I have not found a viable solution. Is there a more straightforward approach to ensure that the DLLs within the single-file EXE are obfuscated? 
Any assistance would be greatly appreciated. 
Thank you.

**Comment by lextm** [comment]
Duplicate to #301

**Comment by dabalciunas** [comment]
See this answer in Stackoverflow:
[How to use Obfuscar in the publish process of .NET Applications](https://stackoverflow.com/questions/69973447/how-to-use-obfuscar-in-the-publish-process-of-net-applications)
