### ISSUE TITLE
Obfuscar exited with code 1 for .Net sdk style Android project

### ISSUE THREAD

**Issue by SejalHarsoda** [obfuscar/obfuscar#491]
Obfuscar command run successfully in xamarin but now we have migrated the app to .Net style project as xamarin support removed by microsoft. 

Now in migrated project the obfuscar command always exited with code 1 so not able to findout the actual rootcause.

Does the obfuscar works with .NEt SDK style Android and iOS project and if yes then provide the steps for it

**Comment by lextm** [comment]
We have no plan to address Xamarin/MAUI specific issues.

Pull requests to this repo as well as [our documentation](https://github.com/obfuscar/docs) are welcome if anyone figures out the needed steps.
