### ISSUE TITLE
Template constraints changed from unmanaged to struct, causing errors

### ISSUE THREAD

**Issue by paw9000Unity** [obfuscar/obfuscar#492]
### Expected behavior

I expected obfuscation process to preserve template constraints, but it is not.  Specifically, if I have a method with a template constraint like this "where T1 : unmanaged" I'd expect it to stay that way after obfuscation.  Instead I'm seeing it output "where T1 : struct"  which is causing this error:
error CS0570: 'T1' is not supported by the language 

### Actual behavior

But a bug happened like this,
after obfuscation "where T1 : unmanaged" is changed to "where T1 : struct".

### Detailed steps

The steps are, after obfuscation I get:

This is error: 
error CS0570: 'T1' is not supported by the language 

Here is the line of code with the error: 
PolySpatialArgs.ExtractArgs(argCount, argValues, argSizes, out PolySpatialInstanceID* id, out PolySpatialFrameData* frameData); 

This is what the definition of ExtractArgs looks like in C# code before obfuscation: 
internal static unsafe void ExtractArgs<T1, T2>(int argCount, void** args, int* argSizes, out T1* arg1, out T2* arg2) where T1 : unmanaged where T2 : unmanaged 

This is what the definition looks like after decompiling the obfuscated DLL: 
internal static unsafe void ExtractArgs<[a] T1, [a] T2>( int argCount, void** args, int* argSizes, out T1* arg1, out T2* arg2) where T1 : struct where T2 : struct 

I'm assuming the error is the result of Obfuscar changing "where T1 : unmanaged" to "where T1 : struct" 

### Obfuscar version information

2.2.39

### Operating system information

macOS

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.

**Comment by paw9000Unity** [comment]
Note it does this even when the method is skipped due to attribute markup.  
When I check the mapping file I can see:
...ExtractArgs[5]( [netstandard]System.Int32, [netstandard]System.Void**, [netstandard]System.Int32*, [PolySpatial.Core]T1*&, [PolySpatial.Core]T2*& ) skipped:  attribute

**Comment by lextm** [comment]
If we limit the scope of this issue to `T: unmanaged` support, then it is already there in Obfuscar, and you can just use

``` xml
<Module file='AssemblyWithUnmanagedGenerics.dll'>
   <SkipType name='System.Runtime.CompilerServices.IsUnmanagedAttribute' />
</Module>
```
to ensure after obfuscation the generic types remain unmanaged.

Without this extra skip rule, however, the obfuscation process modifies the compiler-injected type, so that the generic types are recognized by .NET runtime as `T: struct` instead of `T: unmanaged`.
