### ISSUE TITLE
DOES NOT BUILD AS MENTION PER INSTRUCTIONS ON YOUR SITE!!!!!!

### ISSUE THREAD

**Issue by ItsJokerZz** [obfuscar/obfuscar#493]
### Expected behavior

I expected this,

### Actual behavior

But a bug happened like this,

### Detailed steps

The steps are,

### Obfuscar version information

NO CLUE

### Operating system information

WIN11

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.

**Comment by lextm** [comment]
Duplicate to #96
