### ISSUE TITLE
Obfuscar.Console reports wrong version in 2.2.39

### ISSUE THREAD

**Issue by dabalciunas** [obfuscar/obfuscar#494]
### Expected behavior

Obfuscar.Console.exe -V
2.2.39.0

### Actual behavior

Obfuscar.Console.exe -V
0.0.0.0

### Detailed steps

Open console window and type:
Obfuscar.Console.exe -V

### Obfuscar version information

2.2.39

### Operating system information

Windows

### Relevant log output (optional)

```shell
Obfuscar.Console.exe -V
0.0.0.0
```

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.
