### ISSUE TITLE
Should support reversible / unique naming

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obfuscar/obfuscar#5]
```
Currently, Obfuscar supports only renaming methods/types/etc. using a
minimal, non-unique set of names.  This makes debugging difficult, since
stack traces can easily be ambiguous (see discussion at
http://code.google.com/p/obfuscar/issues/detail?id=4).

Obfuscar should support a non-default option to instead assign unique names
to the methods/types/etc so that stack traces can be more easily reversed.
```

Original issue reported on code.google.com by `drcfor...@gmail.com` on 15 May 2007 at 12:53

**Comment by evaldsurtans** [comment]
This would be excellent feature like in EAZ Obfuscator:

![image](https://user-images.githubusercontent.com/1777062/42680202-f370fa30-868c-11e8-8e23-a04cf0829fce.png)

**Comment by lextm** [comment]
You can check the FAQ. There is another open source project to achieve that,

http://docs.obfuscar.com/en/latest/support/faq.html#how-to-analyze-exception-call-stack-if-obfuscated
