### ISSUE TITLE
Obfuscated WPF application crashed

### ISSUE THREAD

**Issue by lextudio-support** [obfuscar/obfuscar#511]
Class names are hard coded in XAML files for Window and so on. Such strings are embedded in the resource section of the assembly in BAML format. 

Thus, obfuscation should correctly rename the items in BAML, or automatically skip any types that appear in BAML.

**Original Reported Date**: 2013-05-01T01:06:53.813-07:00
**Planned For Release**: 2.0
**Original CodePlex ID**: 1

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Reused ILSpy's logic to decompile BAML to XAML. Now we know which names are there.

As I am not sure yet how to convert XAML to BAML and embed back to the assembly, all types appear in BAML are skipped.

Will further investigate.

**Original Posted Date**: 2013-05-01T01:08:18.08-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:




** Closed by lextm 03/25/2014 1:23AM

**Original Posted Date**: 2014-03-25T01:23:34.897-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

There are more types in BAML than I originally thought, so more effort is required before WPF is fully supported.

**Original Posted Date**: 2014-07-03T05:43:32.057-07:00

**Comment by monty241** [comment]
Workaround is to decorate private methods used in WPF by the XAML:
```
[Obfuscation(Feature = "renaming", Exclude = true)]
```

**Comment by monty241** [comment]
Patch on Dot Blur with commit b1b86937d093c21f935efc3df57886d80bacb89d in case someone wants to port to Obfuscar.

**Comment by lextm** [comment]
Duplicate to #551
