### ISSUE TITLE
MAUI iOS looking for obfuscar imeplementation doesn't works

### ISSUE THREAD

**Issue by rubenmorameneses** [obfuscar/obfuscar#536]
### Description
I want use the Obfuscar Extension (https://marketplace.visualstudio.com/items?itemName=AvinabMalla.obfuscarvs). I reach the goal on MAUI Android, but iOS is a little bit difficult because I'm trying look for the extension Obfuscar in Visual Studio for Macos, there is no such extension.

### Actual behavior

In iOS there is no such extension, and in the old way I made in Xamarin and I remember it worked fine.  

### Detailed steps

The steps are,### Steps to Reproduce

1- Install Visual Studio for Macos
2- Create a basic MAUI app for iOS
3- Click on Visual Studio/ Extensions/

![image](https://github.com/user-attachments/assets/b9f06354-849c-43f8-9d0a-bf65fa83eec2)

4- Look for "Obfuscar" extension:

![image](https://github.com/user-attachments/assets/71c1157f-d537-422f-a1b9-e8b9c2bab380)

This is my VS version:

![image](https://github.com/user-attachments/assets/ee08135c-9ace-4e00-8e54-3e4105076771)

### Obfuscar version information

2.2.40

### Operating system information

macOS Sonoma 14

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.

**Comment by lextm** [comment]
We are not in filiation with any of such extensions/external projects, and we have no plan to work on MAUI specific features at this moment.
