### ISSUE TITLE
Unhandled Exception (System.NotSupportedException) when an icon was set in a Windows Form

### ISSUE THREAD

**Issue by wh7r4bb17** [obfuscar/obfuscar#537]
### Expected behavior

The build (.NET 8.0 class library) should run through without errors, when obfucar is enabled.

### Actual behavior

As soon as an icon has been defined, the build always terminates with an error.
If no icon is defined or obfuscar is deactivated, the build runs through without errors.

### Detailed steps

Set an icon for a windows form, activate obfuscar and build solution.

The obfuscar settings are:
<Include>
	<Var name="RegenerateDebugInfo" value="false" />
	<Var name="MarkedOnly" value="false" />
	<Var name="RenameProperties" value="false" />
	<Var name="RenameEvents" value="true" />
	<Var name="RenameFields" value="false" />
	<Var name="KeepPublicApi" value="true" />
	<Var name="HidePrivateApi" value="true" />
	<Var name="ReuseNames" value="false" />
	<Var name="HideStrings" value="true" />
	<Var name="OptimizeMethods" value="true" />
	<Var name="SuppressIldasm" value="true" />
	<Var name="AnalyzeXaml" value="true" />
	<Var name="UseUnicodeNames" value="true" />
	<Var name="UseKoreanNames" value="true" />
  <Module file="$(InPath)\XXX.Application.dll">
    <SkipType name="*AnonymousType*" skipProperties="true" skipMethods="true" skipFields="true" skipEvents="true" skipStringHiding="true" />
  </Module>
  <AssemblySearchPath path="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.10\ref\net8.0\" />
  <AssemblySearchPath path="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.10\ref\net8.0\" />
  <AssemblySearchPath path="C:\ProgramData\Autodesk\ApplicationPlugins\VaultInventor2025.bundle\Contents\" />
  <AssemblySearchPath path="C:\Users\XXX\.nuget\packages\serilog.sinks.console\5.0.1\lib\net7.0\" />
  <AssemblySearchPath path="C:\Users\XXX\.nuget\packages\serilog.sinks.eventlog\3.1.0\lib\netstandard2.0\" />
  <AssemblySearchPath path="C:\Users\XXX\.nuget\packages\serilog.sinks.file\4.1.0\lib\netstandard2.0\" />
  <AssemblySearchPath path="C:\Users\XXX\.nuget\packages\serilog\3.1.1\lib\net7.0\" />
  <AssemblySearchPath path="C:\Users\XXX\.nuget\packages\wh7r4bb17.base\1.0.6.2\lib\net8.0-windows7.0\" />
  <AssemblySearchPath path="C:\Users\XXX\.nuget\packages\wh7r4bb17.forms\1.0.3\lib\net8.0-windows7.0\" />
  <AssemblySearchPath path="C:\Users\XXX\.nuget\packages\wh7r4bb17.logging\1.0.2\lib\netstandard2.0\" />
</Include>

### Obfuscar version information

2.2.31.0

### Operating system information

Windows 11

### Relevant log output (optional)

```shell
1>Loading project XXX\_Obfuscar\obfuscar_Release_Any_CPU.xml...Processing assembly: XXX.Application, Version=25.0.0.3, Culture=neutral, PublicKeyToken=null
1>Loading assemblies...Extra framework folders: Done.
1>Hiding strings...
1>
1>Unhandled Exception: System.NotSupportedException: This .resources file should not be read with this reader. The resource reader type is "System.Resources.Extensions.DeserializingResourceReader, System.Resources.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51".
1>   at System.Resources.ResourceReader._ReadResources()
1>   at System.Resources.ResourceReader.ReadResources()
1>   at Obfuscar.Obfuscator.GetXamlDocuments(AssemblyDefinition library, Boolean analyzeXaml)
1>   at Obfuscar.Obfuscator.RenameTypes()
1>   at Obfuscar.Obfuscator.RunRules()
1>   at Obfuscar.Program.Main(String[] args)
1>Renaming:  fields...Parameters...Properties...Events...Methods...Types...
```

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.

**Comment by wh7r4bb17** [comment]
The error also occurs with version 2.2.40.0

**Comment by wh7r4bb17** [comment]
additionally the two resources files. 1x with icon the other one without icon

[resources files .zip](https://github.com/user-attachments/files/17645211/resources.files.zip)

**Comment by lextm** [comment]
Duplicate to #268

**Comment by wh7r4bb17** [comment]
Thanks for the hint.
Set AnalyzeXaml to false solved the problem.
