### ISSUE TITLE
Donate button fails with error

### ISSUE THREAD

**Issue by monty241** [obfuscar/obfuscar#538]
### Expected behavior

When I select the PayPal button at the end of https://github.com/obfuscar/obfuscar (`https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=TZATDDPGZUSPL`) it fails.

### Actual behavior

Possibility to make a donation.

### Detailed steps

Click on "donate".

### Obfuscar version information

main

### Operating system information

Windows

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.

**Comment by monty241** [comment]
Workaround is to use https://github.com/sponsors/obfuscar.

**Comment by monty241** [comment]
Thx!
