### ISSUE TITLE
Unable to read specified project file:  --suppress

### ISSUE THREAD

**Issue by monty241** [obfuscar/obfuscar#540]
### Expected behavior

When executing the command line on 2.2.40:
```
cd "PATH"
"C:\Users\...\.dotnet\tools\obfuscar.console.exe" --suppress "c:\temp\...\....24.0.414-net48.xml"
```
I expected Obfuscar to run normally as with 2.2.38.

### Actual behavior

However, an error appears:

```
Unable to read specified project file:  --suppress
```

### Detailed steps

N/A

### Obfuscar version information

22.2.40

### Operating system information

Windows 11

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.

**Comment by monty241** [comment]
Commit 3b44ab219d50bcd28e87598873ed05b2e6415a0d removed support for Rollbar ("* Removed Rollbar and fixed signing."). There is no backward compatibility mode for `--suppress`, nor is there an error given.

Solution is to remove `--suppress` altogether from the command line.

**Comment by lextm** [comment]
Like you discovered, this is a design change to get rid of Rollbar. The switch is no longer needed so removed.
