### ISSUE TITLE
After building, the datagridview does not show

### ISSUE THREAD

**Issue by pdev1968** [obfuscar/obfuscar#545]
### Expected behavior

After ofuscating with the Ofuscar 2.2.40 I hope my application works as it's before ofuscating.

### Actual behavior

But unfortunately the DatagridView does not show as normal.

### Detailed steps

Just from menu, I opened a a form which shows data from MS SQL Server on a datagridview. Datagridview show data before, but after ofuscating, it does not. I hope you may give me a hint how to solve this.

### Obfuscar version information

2.2.40

### Operating system information

Windows

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.

**Comment by lextm** [comment]
https://docs.lextudio.com/obfuscar/support/faq#how-to-troubleshoot-typeloadexception-during-reflection

.NET unfortunately uses name based resolution everywhere without explicitly warning you, and a minimal obfuscation tool like Obfuscar is unable to fill the gaps.

You have to locate and exclude relevant code from obfuscation so as to workaround such issues.
