### ISSUE TITLE
Does Obfuscar work with Android Xamarin?

### ISSUE THREAD

**Issue by alberk8** [obfuscar/obfuscar#97]
I have tried to adding this to my .csproj file.   The solution builded but error out on "Unable to resolve dependency:  Mono.Android".   How do I get this to work?  Thank you.

```
<Target Name="AfterBuild">
    <Exec Command="&quot;$(SolutionDir)packages\Obfuscar.2.2.3\tools\Obfuscar.Console.exe&quot;  $(SolutionDir)obfuscar.xml" />
  </Target>

```

Error Output
```
1>Target "AfterBuild" in project "D:\Project\App\App\TestApp.csproj" (target "Build" depends on it):
1>Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
1>Task "Exec"
1>  "D:\Project\App\packages\Obfuscar.2.2.3\tools\Obfuscar.Console.exe"  D:\Project\App\obfuscar.xml
1>  Loading project D:\Project\App\obfuscar.xml...Processing assembly: TestApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
1>  Loading assemblies...Extra framework folders: 
1>  An error occurred during processing:
1>  Unable to resolve dependency:  Mono.Android
1>D:\Project\App\App\TestApp.csproj(88,5): error MSB3073: The command ""D:\Project\App\packages\Obfuscar.2.2.3\tools\Obfuscar.Console.exe"  D:\Project\App\obfuscar.xml" exited with code 1.
1>Done executing task "Exec" -- FAILED.
1>Done building target "AfterBuild" in project "Http.csproj" -- FAILED.
1>
1>Build FAILED.
```

**Comment by alberk8** [comment]
Hi,
Is it possible to get Obfuscar to work with Xamarin ?  Thank you.

**Comment by lextm** [comment]
The current dependency assembly resolution is .NET Framework/PCL only. If you want to target Xamarin.Android, you can try to copy those dependencies manually to the output folder, then Obfuscar will be able to load them. That's a workaround you can try out.

**Comment by ZimM-LostPolygon** [comment]
@alberk8 
There is now a <AssemblySearchPath> tag that you can specify to add the Xamarin assemblies for assembly resolution.

**Comment by lextm** [comment]
As AOT is coming to Xamarin.Android (see Xamarin's announcement at Build 2017), you can safely use that to obfuscate your code in all necessary aspects without Obfuscar.

**Comment by ZimM-LostPolygon** [comment]
AOT for Android is just an option, and it can't be used for some cases, for example, dynamic code generation and expressions trees are only possible with JIT. So there is still value in this.

**Comment by alberk8** [comment]
I hope that the AOT feature will be made available to VS Community version.  :)

**Comment by softlion** [comment]
> @alberk8
> There is now a tag that you can specify to add the Xamarin assemblies for assembly resolution.

Which tag is it, not found in doc
